// Hand-maintained map of normalized user input -> canonical career title.
//
// Keys MUST already be in normalized form (see normalizeCareer): lowercase, no
// punctuation, single-spaced. Values are the canonical title we generate and
// cache the pathway under, in proper display casing.
//
// BE CONSERVATIVE when adding entries. Two careers only belong on the same
// canonical title if a student would follow the same MDC program, transfer,
// and licensing route. Nurse Practitioner and Nurse Anesthetist look similar
// but need different degrees and different exams, so they stay separate.
// Generating a near-duplicate pathway costs a fraction of a cent; showing
// someone the wrong plan costs them a semester.

export const CAREER_ALIASES: Record<string, string> = {
  // --- Healthcare ---------------------------------------------------------
  "rn": "Registered Nurse",
  "nurse": "Registered Nurse",
  "nursing": "Registered Nurse",
  "registered nurse": "Registered Nurse",
  "np": "Nurse Practitioner",
  "nurse practitioner": "Nurse Practitioner",
  "crna": "Certified Registered Nurse Anesthetist",
  "nurse anesthetist": "Certified Registered Nurse Anesthetist",
  "certified registered nurse anesthetist": "Certified Registered Nurse Anesthetist",
  "cnm": "Certified Nurse-Midwife",
  "midwife": "Certified Nurse-Midwife",
  "nurse midwife": "Certified Nurse-Midwife",
  "doctor": "Physician",
  "physician": "Physician",
  "md": "Physician",
  "medical doctor": "Physician",
  "pa": "Physician Assistant",
  "physician assistant": "Physician Assistant",
  "dental hygienist": "Dental Hygienist",
  "hygienist": "Dental Hygienist",
  "dentist": "Dentist",
  "pharmacist": "Pharmacist",
  "physical therapist": "Physical Therapist",
  "pt": "Physical Therapist",
  "pta": "Physical Therapist Assistant",
  "physical therapist assistant": "Physical Therapist Assistant",
  "occupational therapist": "Occupational Therapist",
  "ot": "Occupational Therapist",
  "respiratory therapist": "Respiratory Therapist",
  "radiologic technologist": "Radiologic Technologist",
  "radiographer": "Radiologic Technologist",
  "xray tech": "Radiologic Technologist",
  "x ray technician": "Radiologic Technologist",
  "sonographer": "Diagnostic Medical Sonographer",
  "ultrasound tech": "Diagnostic Medical Sonographer",
  "diagnostic medical sonographer": "Diagnostic Medical Sonographer",
  "emt": "Emergency Medical Technician",
  "paramedic": "Paramedic",
  "surgical tech": "Surgical Technologist",
  "surgical technologist": "Surgical Technologist",
  "veterinarian": "Veterinarian",
  "vet": "Veterinarian",
  "vet tech": "Veterinary Technician",
  "veterinary technician": "Veterinary Technician",

  // --- Computing ----------------------------------------------------------
  "swe": "Software Engineer",
  "software engineer": "Software Engineer",
  "software developer": "Software Engineer",
  "software dev": "Software Engineer",
  "developer": "Software Engineer",
  "programmer": "Software Engineer",
  "coder": "Software Engineer",
  "computer programmer": "Software Engineer",
  "web developer": "Web Developer",
  "web dev": "Web Developer",
  "frontend developer": "Web Developer",
  "front end developer": "Web Developer",
  "mobile developer": "Mobile Application Developer",
  "app developer": "Mobile Application Developer",
  "mobile application developer": "Mobile Application Developer",
  "ios developer": "Mobile Application Developer",
  "android developer": "Mobile Application Developer",
  "data scientist": "Data Scientist",
  "data analyst": "Data Analyst",
  "cybersecurity": "Cybersecurity Analyst",
  "cyber security": "Cybersecurity Analyst",
  "cybersecurity analyst": "Cybersecurity Analyst",
  "security analyst": "Cybersecurity Analyst",
  "infosec": "Cybersecurity Analyst",
  "network administrator": "Network Administrator",
  "network admin": "Network Administrator",
  "sysadmin": "Systems Administrator",
  "system administrator": "Systems Administrator",
  "systems administrator": "Systems Administrator",
  "it": "Information Technology Specialist",
  "it specialist": "Information Technology Specialist",
  "information technology": "Information Technology Specialist",
  "game developer": "Game Developer",
  "game dev": "Game Developer",
  "game designer": "Game Developer",

  // --- Engineering --------------------------------------------------------
  "mechanical engineer": "Mechanical Engineer",
  "civil engineer": "Civil Engineer",
  "electrical engineer": "Electrical Engineer",
  "biomedical engineer": "Biomedical Engineer",
  "chemical engineer": "Chemical Engineer",
  "computer engineer": "Computer Engineer",
  "industrial engineer": "Industrial Engineer",
  "aerospace engineer": "Aerospace Engineer",
  "architect": "Architect",
  "architecture": "Architect",
  "landscape architect": "Landscape Architect",
  "interior designer": "Interior Designer",
  "interior design": "Interior Designer",

  // --- Business -----------------------------------------------------------
  "accountant": "Accountant",
  "accounting": "Accountant",
  "cpa": "Certified Public Accountant",
  "certified public accountant": "Certified Public Accountant",
  "financial analyst": "Financial Analyst",
  "marketing": "Marketing Manager",
  "marketing manager": "Marketing Manager",
  "entrepreneur": "Entrepreneur",
  "business owner": "Entrepreneur",
  "hr": "Human Resources Specialist",
  "human resources": "Human Resources Specialist",
  "project manager": "Project Manager",
  "pm": "Project Manager",
  "real estate agent": "Real Estate Agent",
  "realtor": "Real Estate Agent",

  // --- Law & public service ----------------------------------------------
  "lawyer": "Lawyer",
  "attorney": "Lawyer",
  "law": "Lawyer",
  "paralegal": "Paralegal",
  "legal assistant": "Paralegal",
  "police officer": "Police Officer",
  "cop": "Police Officer",
  "law enforcement": "Police Officer",
  "detective": "Detective",
  "firefighter": "Firefighter",
  "fire fighter": "Firefighter",
  "crime scene investigator": "Crime Scene Investigator",
  "csi": "Crime Scene Investigator",
  "forensic scientist": "Forensic Scientist",
  "social worker": "Social Worker",
  "social work": "Social Worker",

  // --- Education ----------------------------------------------------------
  "teacher": "Teacher",
  "teaching": "Teacher",
  "elementary teacher": "Elementary School Teacher",
  "elementary school teacher": "Elementary School Teacher",
  "high school teacher": "High School Teacher",
  "professor": "Professor",
  "school counselor": "School Counselor",

  // --- Aviation, trades, hospitality, media -------------------------------
  "pilot": "Commercial Pilot",
  "commercial pilot": "Commercial Pilot",
  "airline pilot": "Commercial Pilot",
  "air traffic controller": "Air Traffic Controller",
  "aircraft mechanic": "Aircraft Mechanic",
  "aviation maintenance": "Aircraft Mechanic",
  "electrician": "Electrician",
  "hvac": "HVAC Technician",
  "hvac technician": "HVAC Technician",
  "welder": "Welder",
  "chef": "Chef",
  "culinary": "Chef",
  "cook": "Chef",
  "hotel manager": "Hospitality Manager",
  "hospitality": "Hospitality Manager",
  "graphic designer": "Graphic Designer",
  "graphic design": "Graphic Designer",
  "animator": "Animator",
  "animation": "Animator",
  "journalist": "Journalist",
  "journalism": "Journalist",
  "reporter": "Journalist",
  "photographer": "Photographer",
  "film maker": "Film Producer",
  "filmmaker": "Film Producer",
  "film producer": "Film Producer",
  "psychologist": "Psychologist",
  "psychology": "Psychologist",
  "therapist": "Mental Health Counselor",
  "counselor": "Mental Health Counselor",
  "mental health counselor": "Mental Health Counselor",
};
