// Layer 3 — a durable store for pathways generated by real traffic.
//
// apiCache.ts has two layers: the committed seed file (permanent) and an
// in-memory map (wiped on every cold start, unwritable on a read-only
// serverless filesystem). That means a pathway a student paid a Gemini call
// for is gone minutes later, and the next student pays for it again.
//
// This layer catches those generations and keeps them. Two payoffs:
//
//   1. Cold starts stop re-billing. A pathway is generated at most once, ever.
//   2. `npm run export-cache` pulls everything generated by real users into
//      data/seed-cache.json, so the seed file grows from actual demand without
//      re-running the generator against Gemini.
//
// Deliberately dependency-free. Vercel provisions KV_REST_API_URL and
// KV_REST_API_TOKEN pointing at an Upstash-compatible REST endpoint, which
// speaks plain JSON over fetch — so no client library to install, pin, or
// chase through a rename.
//
// EVERY function degrades to a no-op when those env vars are absent. Local dev
// and CI have no store configured and must behave exactly as they did before
// this file existed; a cache is an optimization, and an optimization that can
// take down a request is a liability. Failures are logged and swallowed.

const REST_URL = process.env.KV_REST_API_URL;
const REST_TOKEN = process.env.KV_REST_API_TOKEN;

// Namespaced so the store can be shared with anything else without collisions,
// and so export-cache can list only what belongs to this cache.
const PREFIX = "vocation:";

// Long enough that an entry survives until someone gets around to exporting
// it, short enough that a career nobody asks for again doesn't live forever.
const TTL_SECONDS = 60 * 60 * 24 * 30; // 30 days

// A hung store must not hang a student's request. The read sits in front of
// Gemini, so its budget is small: if the store can't answer fast, generating
// is the better outcome than stalling.
const TIMEOUT_MS = 2000;

/** True when a durable store is configured. False locally and in CI. */
export function durableCacheEnabled(): boolean {
  return Boolean(REST_URL && REST_TOKEN);
}

/**
 * Runs one Redis command over the REST API.
 *
 * Returns undefined on any failure — unconfigured, network error, timeout, or
 * non-2xx. Callers treat that as a cache miss.
 */
async function command(args: (string | number)[]): Promise<unknown> {
  if (!durableCacheEnabled()) return undefined;

  try {
    const response = await fetch(REST_URL!, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${REST_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(args),
      signal: AbortSignal.timeout(TIMEOUT_MS),
      cache: "no-store",
    });

    if (!response.ok) {
      console.error(`[durable-cache] ${args[0]} failed: HTTP ${response.status}`);
      return undefined;
    }

    const payload = (await response.json()) as { result?: unknown };
    return payload.result;
  } catch (error) {
    // Includes AbortError on timeout. Never rethrow: a degraded cache is a
    // slower app, but a throwing cache is a broken one.
    const reason = error instanceof Error ? error.message : String(error);
    console.error(`[durable-cache] ${args[0]} failed: ${reason}`);
    return undefined;
  }
}

/** A previously generated value, or undefined on miss/failure/unconfigured. */
export async function getDurable<T>(key: string): Promise<T | undefined> {
  const raw = await command(["GET", PREFIX + key]);
  if (typeof raw !== "string") return undefined;

  try {
    return JSON.parse(raw) as T;
  } catch {
    // A value we can't parse is worse than none — drop it rather than let a
    // corrupt entry keep being served.
    console.error(`[durable-cache] unparseable entry at ${key}`);
    return undefined;
  }
}

/** Stores a generated value. Silently does nothing when unconfigured. */
export async function setDurable(key: string, value: unknown): Promise<void> {
  await command(["SET", PREFIX + key, JSON.stringify(value), "EX", TTL_SECONDS]);
}

/**
 * Every stored entry, keyed the same way as the seed file.
 *
 * Used only by scripts/export-cache.mjs. KEYS is O(n) and normally discouraged,
 * but this runs from a local script against a store holding hundreds of
 * entries, not in a request path.
 */
export async function listDurable(): Promise<Record<string, unknown>> {
  const keys = await command(["KEYS", PREFIX + "*"]);
  if (!Array.isArray(keys) || keys.length === 0) return {};

  const values = await command(["MGET", ...(keys as string[])]);
  if (!Array.isArray(values)) return {};

  const out: Record<string, unknown> = {};
  for (const [index, fullKey] of (keys as string[]).entries()) {
    const raw = values[index];
    if (typeof raw !== "string") continue;
    try {
      out[fullKey.slice(PREFIX.length)] = JSON.parse(raw);
    } catch {
      console.error(`[durable-cache] skipping unparseable entry at ${fullKey}`);
    }
  }
  return out;
}
