// Barry University degree catalog: program name -> official bulletin page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:barry
//
// Source (undergraduate): https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/programs-of-study
// Source (graduate):      https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/programs-of-study
// Scraped:    2026-07-27
// Programs:   84 (41 bachelor, 43 graduate)
//
// Barry is a four-year private university (like UM/Stetson/ERAU/UT/FIU/
// UCF/...), so pathways start at the bachelor's rather than an associate
// degree — see universitySystemPrompt in app/lib/pathwayPrompts.ts.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const BARRY_PROGRAMS: SchoolProgram[] = [
  { name: "Advertising and Public Relations (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-communication/advertising-and-public-relations-b-a", level: "bachelor", area: "Department of Communication" },
  { name: "Art (B.F.A., B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/art-b-f-a", level: "bachelor", area: "Department of Fine Arts" },
  { name: "B.S. in Education", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-education-and-leadership/b-s-in-education-with-m-s-option", level: "bachelor", area: "Department of Education and Leadership" },
  { name: "Bachelor of Arts (B.A.) in Art (120 credits)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/copy-of-bachelor-of-arts-ba-in-art-120-credits", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Bachelor of Arts (B.A.) in Photography (120 credits)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/bachelor-of-arts-ba-in-photography-120-credits", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Bachelor of Fine Arts (B.F.A.) in Art (120 credits)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/copy-of-bachelor-of-fine-arts-b-f-a-in-art-120-credits", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Bachelor of Fine Arts (B.F.A.) in Photography (120 credits)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/bachelor-of-fine-arts-bfa-in-photography-120-credits", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Bachelor of Public Administration (B.P.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/adult-learner-degree-completion-school-of-business/bachelor-of-public-administration-b-p-a", level: "bachelor", area: "Adult Learner Degree Completion School of Business" },
  { name: "Bachelor of Science in Nursing Program", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/bachelor-of-science-in-nursing-program", level: "bachelor", area: "School of Nursing" },
  { name: "Bachelor of Social Work (B.S.W.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/social-work/bachelor-of-social-work-b-s-w", level: "bachelor", area: "Social Work" },
  { name: "Biology (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-biology/biology-b-s", level: "bachelor", area: "Department of Biology" },
  { name: "Chemistry (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-chemistry-and-physics/chemistry-b-s", level: "bachelor", area: "Department of Chemistry and Physics" },
  { name: "Clinical Laboratory Sciences (B.S.)- Histotechnology Specialization", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/clinical-laboratory-sciences-program/clinical-biology-b-s-histotechnology-specialization", level: "bachelor", area: "Clinical Laboratory Sciences Program" },
  { name: "Clinical Laboratory Sciences (B.S.)- Medical Laboratory Sciences", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/clinical-laboratory-sciences-program/clinical-biology-b-s-medical-laboratory-science-specialization", level: "bachelor", area: "Clinical Laboratory Sciences Program" },
  { name: "Clinical Laboratory Sciences Completion Program (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/clinical-laboratory-sciences-program/clinical-laboratory-sciences-completion-program", level: "bachelor", area: "Clinical Laboratory Sciences Program" },
  { name: "Communication and Media Studies (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-communication/communication-and-media-studies-b-a", level: "bachelor", area: "Department of Communication" },
  { name: "Computer Information Sciences (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-mathematics-and-computer-science/computer-information-sciences-b-s", level: "bachelor", area: "Department of Mathematics and Computer Science" },
  { name: "Computer Science (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-mathematics-and-computer-science/computer-science-b-s", level: "bachelor", area: "Department of Mathematics and Computer Science" },
  { name: "Criminology (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-sociology-and-criminology/criminology-b-s", level: "bachelor", area: "Department of Sociology and Criminology" },
  { name: "Emergency Management (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/emergency-management-services-academy/emergency-management-b-s", level: "bachelor", area: "Emergency Management Services Academy" },
  { name: "English (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-english-and-foreign-languages/english-b-a", level: "bachelor", area: "Department of English and Foreign Languages" },
  { name: "English (B.A.) With A Literature Specialization", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-english-and-foreign-languages/english-ba-with-a-literature-specialization", level: "bachelor", area: "Department of English and Foreign Languages" },
  { name: "English (B.A.) With A Professional Writing Specialization", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-english-and-foreign-languages/english-ba-with-a-professional-writing-specialization", level: "bachelor", area: "Department of English and Foreign Languages" },
  { name: "General Studies (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-arts-and-sciences/general-studies-b-a", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "History (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-history-and-political-science/history-b-a", level: "bachelor", area: "Department of History and Political Science" },
  { name: "International Studies (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-history-and-political-science/international-studies-b-a", level: "bachelor", area: "Department of History and Political Science" },
  { name: "Kinesiology and Sport Sciences (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/kinesiology-and-sport-sciences-b-s", level: "bachelor", area: "Sport and Exercise Sciences" },
  { name: "Mathematical Sciences (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-mathematics-and-computer-science/mathematical-sciences-b-s", level: "bachelor", area: "Department of Mathematics and Computer Science" },
  { name: "Music (B.M., B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/music-b-m-b-a", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Organizational Leadership (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/adult-learner-degree-completion-school-of-business/organizational-leadership-bs", level: "bachelor", area: "Adult Learner Degree Completion School of Business" },
  { name: "Philosophy (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-theology-and-philosophy/philosophy-b-a", level: "bachelor", area: "Department of Theology and Philosophy" },
  { name: "Photography (B.F.A., B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/photography-b-f-a-b-a", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Political Science (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-history-and-political-science/political-science-b-s", level: "bachelor", area: "Department of History and Political Science" },
  { name: "Pre-Law (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-history-and-political-science/pre-law-b-a", level: "bachelor", area: "Department of History and Political Science" },
  { name: "Psychology (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-psychology/psychology-b-s", level: "bachelor", area: "Department of Psychology" },
  { name: "Sociology (B.S.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-sociology-and-criminology/sociology-b-s", level: "bachelor", area: "Department of Sociology and Criminology" },
  { name: "Spanish (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-english-and-foreign-languages/spanish-b-a", level: "bachelor", area: "Department of English and Foreign Languages" },
  { name: "Television and Digital Media (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-communication/television-and-digital-media-b-a", level: "bachelor", area: "Department of Communication" },
  { name: "The Bachelor of Science in Business Administration (B.S.B.A.) Degree Program", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/d-inez-andreas-school-of-business-and-public-administration/the-bachelor-of-science-in-business-administration-b-s-b-a-degree-program", level: "bachelor", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Theatre (B.F.A., B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-fine-arts/theatre-b-f-a-b-a", level: "bachelor", area: "Department of Fine Arts" },
  { name: "Theology (B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/department-of-theology-and-philosophy/theology-b-a", level: "bachelor", area: "Department of Theology and Philosophy" },
  { name: "B.S. in Sport Management and Business Administration to M.S. in Sport Management", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/b-s-in-sport-management-and-business-administration-to-m-s-in-sport-management", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Clinical Laboratory Sciences (B.S.)- Medical Laboratory Sciences (B.S. to M.S. Option)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/clinical-laboratory-sciences-program/clinical-laboratory-sciences-bs-medical-laboratory-sciences-specialization-bs-to-ms-option", level: "graduate", area: "Clinical Laboratory Sciences Program" },
  { name: "Doctor of Education in Organizational Leadership", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-education-and-leadership/doctor-of-education-in-organizational-leadership", level: "graduate", area: "Department of Education and Leadership" },
  { name: "Doctor of Ministry Degree Program (D.MIN.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-theology-and-philosophy/doctor-of-ministry-degree-program-d-min", level: "graduate", area: "Department of Theology and Philosophy" },
  { name: "Doctor of Philosophy (Ph.D.) in Curriculum and Instruction", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-education-and-leadership/doctor-of-philosophy-ph-d-in-curriculum-and-instruction", level: "graduate", area: "Department of Education and Leadership" },
  { name: "Doctor of Philosophy in Counseling", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/counseling-and-school-psychology/doctor-of-philosophy-in-counseling", level: "graduate", area: "Counseling and School Psychology" },
  { name: "Doctor of Podiatric Medicine", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-podiatric-medicine/doctor-of-podiatric-medicine", level: "graduate", area: "School of Podiatric Medicine" },
  { name: "Doctor of Social Work (DSW)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/social-work/doctor-of-social-work-dsw", level: "graduate", area: "Social Work" },
  { name: "DPM/MBA Dual Degree", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-podiatric-medicine/d-p-m-m-b-a-dual-degree", level: "graduate", area: "School of Podiatric Medicine" },
  { name: "Entry Level Post Baccalaureate Doctor of Nursing Practice (DNP) with Specialization in Anesthesiology", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/post-baccalaureate-doctor-of-nursing-practice-dnp-with-specialization-in-anesthesiology", level: "graduate", area: "School of Nursing" },
  { name: "J.D./MBA Dual Degree", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/school-of-law/j-d-mba-dual-degree", level: "graduate", area: "School of Law" },
  { name: "Kinesiology and Sport Sciences (B.S. KHPUM to M.S. KHPM Seamless)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/kinesiology-and-sport-sciences-khpum-bs-to-khpm-ms-seamless", level: "graduate", area: "Sport and Exercise Sciences" },
  { name: "Kinesiology and Sport Sciences (B.S. KHPUS to M.S. KHPS SEPPG Seamless)", url: "https://barry.smartcatalogiq.com/en/2025-2026/undergraduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/kinesiology-and-sport-sciences-bs-khpus-to-ms-khps-seppg-seamless", level: "graduate", area: "Sport and Exercise Sciences" },
  { name: "M.S.N. Programs", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/m-s-n-programs", level: "graduate", area: "School of Nursing" },
  { name: "Master of Arts (M.A.) in Photography", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-fine-arts/master-of-arts-m-a-in-photography", level: "graduate", area: "Department of Fine Arts" },
  { name: "Master of Arts in Pastoral Ministry for Hispanics", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-theology-and-philosophy/master-of-arts-in-pastoral-ministry-for-hispanics", level: "graduate", area: "Department of Theology and Philosophy" },
  { name: "Master of Arts in Theology", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-theology-and-philosophy/master-of-arts-in-theology", level: "graduate", area: "Department of Theology and Philosophy" },
  { name: "Master of Business Administration", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-business-administration", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Fine Arts (M.F.A.) in Photography", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-fine-arts/master-of-fine-arts-m-f-a-in-photography", level: "graduate", area: "Department of Fine Arts" },
  { name: "Master of Public Administration (M.P.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-public-administration-m-p-a", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Public Health in Epidemiology (MPH-EPI)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-public-health-in-epidemiology-mph-epi", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science (M.S.) and Specialist (S.S.P.) in School Psychology", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/counseling-and-school-psychology/master-of-science-ms-and-specialist-ssp-in-school-psychology", level: "graduate", area: "Counseling and School Psychology" },
  { name: "Master of Science (M.S.) and Specialist in Education (Ed.S) in Educational Leadership", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-education-and-leadership/master-of-science-m-s-and-specialist-in-education-ed-s-in-educational-leadership", level: "graduate", area: "Department of Education and Leadership" },
  { name: "Master of Science (M.S.) in Curriculum and Instruction", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/department-of-education-and-leadership/master-of-science-ms-in-curriculum-and-instruction", level: "graduate", area: "Department of Education and Leadership" },
  { name: "Master of Science (M.S.) in Sport Management", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-m-s-in-sport-management", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science (M.S.) in Sport Management/Master of Business Administration (M.B.A.)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-m-s-in-sport-management-master-of-business-administration-m-b-a", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science in Biomedical Sciences (BMS)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/master-of-science-in-biomedical-sciences-bms", level: "graduate", area: "Department of Health Sciences and Clinical Practice" },
  { name: "Master of Science in Clinical Laboratory Sciences", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/master-of-science-in-clinical-laboratory-science", level: "graduate", area: "Department of Health Sciences and Clinical Practice" },
  { name: "Master of Science in Clinical Psychology (60 Credits)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/clinical-psychology/master-of-science-in-clinical-psychology-60-credit-option", level: "graduate", area: "Clinical Psychology" },
  { name: "Master of Science in Counseling", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/counseling-and-school-psychology/master-of-science-in-counseling", level: "graduate", area: "Counseling and School Psychology" },
  { name: "Master of Science in Health Services Administration (MS/HSA)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-in-health-services-administration-ms-hsa", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science in Health Services Administration and Master of Public Health Dual Degree Program (MS/HSA—MPH)", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-program-in-health-services-administration-and-master-of-public-health-dual-degree-program-ms-hsa-mph", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science in Human Resource Development", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-in-human-resource-development", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science in Kinesiology and Human Performance", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/master-of-science-in-kinesiology-and-human-performance", level: "graduate", area: "Sport and Exercise Sciences" },
  { name: "Master of Science in Kinesiology and Human Performance with Specialization in Sport, Exercise, and Performance Psychology", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/master-of-science-in-kinesiology-and-human-performance-with-specialization-in-sport-exercise-and-performance-psychology", level: "graduate", area: "Sport and Exercise Sciences" },
  { name: "Master of Science in Leadership and Innovation", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/d-inez-andreas-school-of-business-and-public-administration/master-of-science-in-leadership-and-innovation", level: "graduate", area: "D Inez Andreas School of Business and Public Administration" },
  { name: "Master of Science in Occupational Therapy", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/master-of-science-in-occupational-therapy", level: "graduate", area: "Department of Health Sciences and Clinical Practice" },
  { name: "Master of Social Work Degree Program", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-mental-health-and-social-work/social-work/master-of-social-work-degree-program", level: "graduate", area: "Social Work" },
  { name: "MS Kinesiology and Human Performance, SEPP/Master’s of Business Administration, Dual Degree", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/department-of-health-sciences-and-clinical-practice/sport-and-exercise-sciences/ms-kinesiology-and-human-performance-sepp-master-s-of-business-administration-dual-degree", level: "graduate", area: "Sport and Exercise Sciences" },
  { name: "Post Master’s Doctor of Nursing Practice, with a Specialization in Anesthesiology", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/post-master-s-doctor-of-nursing-practice-with-a-specialization-in-anesthesiology", level: "graduate", area: "School of Nursing" },
  { name: "Post-Baccalaureate Doctor of Nursing Practice— Nurse Practitioner", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/post-baccalaureate-doctor-of-nursing-practice-nurse-practitioner", level: "graduate", area: "School of Nursing" },
  { name: "Post-Master’s Doctor of Nursing Practice-Nurse Practitioner", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/college-of-health-professions-and-medical-sciences/school-of-nursing/post-master-s-doctor-of-nursing-practice-nurse-practitioner", level: "graduate", area: "School of Nursing" },
  { name: "School of Law Juris Doctorate Program", url: "https://barry.smartcatalogiq.com/en/2025-2026/graduate-catalog/school-of-law/school-of-law-juris-doctorate-program", level: "graduate", area: "School of Law" },
];

// Barry is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const barryCatalog = createProgramCatalog(BARRY_PROGRAMS, { preferred: "bachelor" });
