// Broward College program catalog.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:broward
//
// Source:   https://catalog.broward.edu/degree-finder/
// Scraped:  2026-07-25
// Programs: 211 (80 associate, 31 bachelor, 100 certificate)
//
// The plain Associate of Arts is added by the scraper: Broward's Degree Finder
// lists only the Honors variant, and the general A.A. is the degree most
// transfer students actually take.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const BROWARD_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting Technology", url: "https://catalog.broward.edu/programs-study/accounting-technology-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Accounting Technology Management", url: "https://catalog.broward.edu/technical-certificates/accounting-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Accounting Technology Operations", url: "https://catalog.broward.edu/technical-certificates/accounting-tech-operations/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Accounting Technology Specialist", url: "https://catalog.broward.edu/technical-certificates/accounting-tech-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Addiction Services", url: "https://catalog.broward.edu/technical-certificates/addiction-services/", level: "certificate", credential: "TC", area: "Social Behavioral Sciences and Human Services" },
  { name: "Aerospace Sciences - Aerospace Management", url: "https://catalog.broward.edu/programs-study/aerospace-sciences-aerospace-management-bs/", level: "bachelor", credential: "BS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aerospace Sciences - Professional Pilot", url: "https://catalog.broward.edu/programs-study/aerospace-sciences-professional-pilot-bs/", level: "bachelor", credential: "BS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aging Services", url: "https://catalog.broward.edu/technical-certificates/aging-services/", level: "certificate", credential: "TC", area: "Social Behavioral Sciences and Human Services" },
  { name: "Airport Operations Management", url: "https://catalog.broward.edu/technical-certificates/airport-operations-management/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Applied Artificial Intelligence", url: "https://catalog.broward.edu/programs-study/applied-artificial-intelligence-associate-science/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Applied Technology Management - Construction", url: "https://catalog.broward.edu/programs-study/applied-technology-management-construction-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Applied Technology Management - Management", url: "https://catalog.broward.edu/programs-study/applied-technology-management-management-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Artificial Intelligence Practitioner", url: "https://catalog.broward.edu/technical-certificates/artificial-intelligence-practitioner-technical-certificate/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Associate of Arts", url: "https://catalog.broward.edu/programs-study/aa-general-education-graduation-requirements/", level: "associate", credential: "AA", area: "Transfer" },
  { name: "Associate of Arts - Honors", url: "https://catalog.broward.edu/programs-study/associate-arts-honors/", level: "associate", credential: "AA", area: "" },
  { name: "Audio Technology", url: "https://catalog.broward.edu/technical-certificates/audio-technology/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Automation", url: "https://catalog.broward.edu/technical-certificates/automation/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Automotive Service Management Technology", url: "https://catalog.broward.edu/programs-study/automotive-service-management-technology-aas/", level: "associate", credential: "AAS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Automotive Service Technician", url: "https://catalog.broward.edu/technical-certificates/automotive-service-technician/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aviation Administration - Air Traffic Control", url: "https://catalog.broward.edu/programs-study/aviation-administration-air-traffic-control-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aviation Administration - Airport Operations Management", url: "https://catalog.broward.edu/programs-study/aviation-administration-airport-operations-management-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aviation Administration - Business", url: "https://catalog.broward.edu/programs-study/aviation-administration-business-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aviation Administration - Commercial Pilot", url: "https://catalog.broward.edu/programs-study/aviation-administration-commercial-pilot-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Aviation Maintenance Management", url: "https://catalog.broward.edu/programs-study/aviation-maintenance-management-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Avionics", url: "https://catalog.broward.edu/programs-study/avionics-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Avionics Technician", url: "https://catalog.broward.edu/technical-certificates/avionics-technician/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Building Construction Specialist", url: "https://catalog.broward.edu/technical-certificates/building-construction-specialist/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Building Construction Technology", url: "https://catalog.broward.edu/programs-study/building-construction-technology-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Business Administration - Entrepreneurship and Small Business Management", url: "https://catalog.broward.edu/programs-study/business-administration-entrepreneurship-small-business-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Business Administration - Human Resources", url: "https://catalog.broward.edu/programs-study/business-administration-human-resources-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Business Administration - Management", url: "https://catalog.broward.edu/programs-study/business-administration-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Business Analytics", url: "https://catalog.broward.edu/programs-study/business-analytics-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Business Development & Entrepreneurship", url: "https://catalog.broward.edu/technical-certificates/business-development--entrepreneurship/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Business Management", url: "https://catalog.broward.edu/technical-certificates/business-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Business Operations", url: "https://catalog.broward.edu/technical-certificates/business-operations/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Business Specialist", url: "https://catalog.broward.edu/technical-certificates/business-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Child Care Center Management", url: "https://catalog.broward.edu/technical-certificates/child-care-center-management/", level: "certificate", credential: "TC", area: "Education" },
  { name: "Cloud Engineering", url: "https://catalog.broward.edu/technical-certificates/cloud-engineering/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "CNC Machinist", url: "https://catalog.broward.edu/technical-certificates/cnc-machinist/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Commercial Flight Operations", url: "https://catalog.broward.edu/technical-certificates/commercial-flight-operations/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Computer Information Technology - Geographic Information Systems", url: "https://catalog.broward.edu/programs-study/computer-information-technology-geographic-information-systems-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Computer Information Technology - Information Technology", url: "https://catalog.broward.edu/programs-study/computer-information-technology-information-technology-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Computer Programmer", url: "https://catalog.broward.edu/technical-certificates/computer-programmer/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Computer Programming Specialist", url: "https://catalog.broward.edu/technical-certificates/computer-programming-specialist/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Correctional Officer Crossover to Florida Law Enforcement Officer Academy", url: "https://catalog.broward.edu/programs-study/correctional-officer-crossover-florida-law-enforcement-officer-academy/", level: "certificate", credential: "VC", area: "Public Safety" },
  { name: "Corrections Officer Academy Basic Recruit Training", url: "https://catalog.broward.edu/programs-study/corrections-officer-academy-basic-recruit-training/", level: "certificate", credential: "VC", area: "Public Safety" },
  { name: "Crime Scene Technician", url: "https://catalog.broward.edu/technical-certificates/crime-scene/", level: "certificate", credential: "TC", area: "Public Safety" },
  { name: "Crime Scene Technology", url: "https://catalog.broward.edu/programs-study/criminal-justice-crime-scene-emphasis-as/", level: "associate", credential: "AS", area: "Public Safety" },
  { name: "Criminal Justice", url: "https://catalog.broward.edu/programs-study/criminal-justice-as/", level: "associate", credential: "AS", area: "Public Safety" },
  { name: "Criminal Justice Technology Specialist", url: "https://catalog.broward.edu/technical-certificates/criminal-justice-technology/", level: "certificate", credential: "TC", area: "Public Safety" },
  { name: "Culinary Arts Management", url: "https://catalog.broward.edu/programs-study/culinary-arts-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Culinary Arts Management Operations", url: "https://catalog.broward.edu/technical-certificates/culinary-arts-management-operations/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Cybersecurity", url: "https://catalog.broward.edu/technical-certificates/cybersecurity/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Cybersecurity and Ethical Hacking", url: "https://catalog.broward.edu/technical-certificates/cybersecurity-ethical-hacking/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Data Analyst II", url: "https://catalog.broward.edu/technical-certificates/data-analyst/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Data Analytics", url: "https://catalog.broward.edu/programs-study/data-analytics-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Data Analytics", url: "https://catalog.broward.edu/technical-certificates/data-analytics/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Data Analytics & AI AA Graduate", url: "https://catalog.broward.edu/programs-study/data-analytics-ai-aabas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Data Analytics & AI AS Graduate", url: "https://catalog.broward.edu/programs-study/data-analytics-ai-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Dental Assisting", url: "https://catalog.broward.edu/programs-study/dental-assisting-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Dental Assisting", url: "https://catalog.broward.edu/programs-study/dental-assisting-atd/", level: "certificate", credential: "ATD", area: "Health Sciences" },
  { name: "Dental Hygiene", url: "https://catalog.broward.edu/programs-study/dental-hygiene-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Diagnostic Medical Sonography", url: "https://catalog.broward.edu/programs-study/diagnostic-medical-sonography-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Domestic Violence Services", url: "https://catalog.broward.edu/technical-certificates/domestic-violence-services/", level: "certificate", credential: "TC", area: "Social Behavioral Sciences and Human Services" },
  { name: "Early Childhood Development Specialization", url: "https://catalog.broward.edu/technical-certificates/early-childhood-development-specialization/", level: "certificate", credential: "TC", area: "Education" },
  { name: "Early Childhood Education", url: "https://catalog.broward.edu/programs-study/early-childhood-education-as/", level: "associate", credential: "AS", area: "Education" },
  { name: "Electronic Aide", url: "https://catalog.broward.edu/technical-certificates/electronic-aide/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Emergency Medical Services", url: "https://catalog.broward.edu/programs-study/emergency-medical-services-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Emergency Medical Technician", url: "https://catalog.broward.edu/programs-study/emergency-medical-technician-applied-technical-diploma/", level: "certificate", credential: "ATD", area: "Health Sciences" },
  { name: "Engineering Tech Support Specialist", url: "https://catalog.broward.edu/technical-certificates/engineering-tech-support-specialist/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Engineering Technology - Advanced Manufacturing", url: "https://catalog.broward.edu/programs-study/engineering-technology-advanced-manufacturing-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Engineering Technology - Biomedical", url: "https://catalog.broward.edu/programs-study/engineering-technology-biomedical-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Engineering Technology - Electronics", url: "https://catalog.broward.edu/programs-study/engineering-technology-electronics-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Engineering Technology - Mechanical Design and Fabrication", url: "https://catalog.broward.edu/programs-study/engineering-technology-mechanical-design-fabrication-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Engineering Technology - Supply Chain Automation", url: "https://catalog.broward.edu/programs-study/engineering-technology-supply-chain-automation-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Entrepreneurship", url: "https://catalog.broward.edu/technical-certificates/entrepreneurship/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Environmental Science - BC/UWF", url: "https://catalog.broward.edu/programs-study/environmental-science-bachelor-science-bcuwf/", level: "bachelor", credential: "BS", area: "Science, Technology, Engineering, and Math" },
  { name: "Environmental Science - Biosecurity", url: "https://catalog.broward.edu/programs-study/environmental-science-biosecurity-bs/", level: "bachelor", credential: "BS", area: "Science, Technology, Engineering, and Math" },
  { name: "Environmental Science - Biosecurity Teaching Focus", url: "https://catalog.broward.edu/programs-study/environmental-science-biosecurity-teaching-focus-bs/", level: "bachelor", credential: "BS", area: "Science, Technology, Engineering, and Math" },
  { name: "Environmental Science - Physical Science", url: "https://catalog.broward.edu/programs-study/environmental-science-physical-science-bs/", level: "bachelor", credential: "BS", area: "Science, Technology, Engineering, and Math" },
  { name: "Environmental Science - Physical Science Teaching Focus", url: "https://catalog.broward.edu/programs-study/environmental-science-physical-science-teaching-focus-bs/", level: "bachelor", credential: "BS", area: "Science, Technology, Engineering, and Math" },
  { name: "Environmental Science Technology", url: "https://catalog.broward.edu/programs-study/environmental-science-technology-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Event Management", url: "https://catalog.broward.edu/technical-certificates/event-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Exceptional Student Education Program", url: "https://catalog.broward.edu/programs-study/exceptional-student-education-program-bsed-program/", level: "bachelor", credential: "BS", area: "Education" },
  { name: "FAA Aircraft Airframe Mechanics", url: "https://catalog.broward.edu/technical-certificates/faa-aircraft-airframe-mechanics/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "FAA Aircraft Powerplant Mechanics", url: "https://catalog.broward.edu/technical-certificates/faa-aircraft-powerplant-mechanics/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "FAA General Mechanics", url: "https://catalog.broward.edu/technical-certificates/faa-general-mechanics/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Film Production Fundamentals", url: "https://catalog.broward.edu/technical-certificates/film-production-fundamentals/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Film Production Technology", url: "https://catalog.broward.edu/programs-study/film-production-technology-as/", level: "associate", credential: "AS", area: "Arts, Humanities, Communication, and Design" },
  { name: "Front-End Web Specialist", url: "https://catalog.broward.edu/technical-certificates/front-end-web-specialist/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "General Automotive Technician", url: "https://catalog.broward.edu/technical-certificates/general-automotive-technician/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Geographic Information Systems (GIS)", url: "https://catalog.broward.edu/technical-certificates/geographic-information-systems-gis-atc/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "GIS Specialist", url: "https://catalog.broward.edu/technical-certificates/gis-specialist/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Graphic Design", url: "https://catalog.broward.edu/programs-study/graphic-design-as/", level: "associate", credential: "AS", area: "Arts, Humanities, Communication, and Design" },
  { name: "Graphic Design Production", url: "https://catalog.broward.edu/technical-certificates/graphic-design-production/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Graphic Design Support", url: "https://catalog.broward.edu/technical-certificates/graphic-design-support/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Guest Services Specialist", url: "https://catalog.broward.edu/technical-certificates/guest-services-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Health Care Services", url: "https://catalog.broward.edu/technical-certificates/health-care-services/", level: "certificate", credential: "TC", area: "Health Sciences" },
  { name: "Health Information Technology", url: "https://catalog.broward.edu/programs-study/health-information-technology-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Navigator Specialist", url: "https://catalog.broward.edu/technical-certificates/health-navigator-specialist/", level: "certificate", credential: "TC", area: "Health Sciences" },
  { name: "Health Science Navigator - Generic", url: "https://catalog.broward.edu/programs-study/health-science-navigator-associate-science---generic/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Dental Hygiene", url: "https://catalog.broward.edu/programs-study/health-science-navigator-dental-hygiene-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Diagnostic Medical Sonography", url: "https://catalog.broward.edu/programs-study/health-science-navigator-diagnostic-medical-sonography-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Health Information Technology", url: "https://catalog.broward.edu/programs-study/health-science-navigator-associate-science---pre-health-information-technology/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Nuclear Medicine", url: "https://catalog.broward.edu/programs-study/health-science-navigator-nuclear-medicine-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Nursing", url: "https://catalog.broward.edu/programs-study/health-science-navigator-pre-nursing-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Physical Therapist Assistant", url: "https://catalog.broward.edu/programs-study/health-science-navigator-physical-therapist-assistant-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Radiation Therapy", url: "https://catalog.broward.edu/programs-study/health-science-navigator-radiation-therapy-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Radiography", url: "https://catalog.broward.edu/programs-study/health-science-navigator-radiography-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Respiratory Care", url: "https://catalog.broward.edu/programs-study/health-science-navigator-pre-respiratory-care-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Science Navigator - Pre-Vision Care", url: "https://catalog.broward.edu/programs-study/health-science-navigator-vision-care-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Health Services Management", url: "https://catalog.broward.edu/programs-study/health-services-management-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Homeland Security Specialist", url: "https://catalog.broward.edu/technical-certificates/homeland-security-specialist/", level: "certificate", credential: "TC", area: "Public Safety" },
  { name: "Hospitality and Tourism Management", url: "https://catalog.broward.edu/programs-study/hospitality-tourism-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Human Resources Manager", url: "https://catalog.broward.edu/technical-certificates/human-resources-manager/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Human Services", url: "https://catalog.broward.edu/programs-study/human-services-associate-science/", level: "associate", credential: "AS", area: "Social Behavioral Sciences and Human Services" },
  { name: "Human Services Generalist", url: "https://catalog.broward.edu/technical-certificates/human-services-generalist/", level: "certificate", credential: "TC", area: "Social Behavioral Sciences and Human Services" },
  { name: "Immersive Technologies", url: "https://catalog.broward.edu/technical-certificates/immersive-technologies/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Industry Operations Specialist", url: "https://catalog.broward.edu/technical-certificates/industry-operations-specialist/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Infant/Toddler Specialization", url: "https://catalog.broward.edu/technical-certificates/infanttoddler-specialization/", level: "certificate", credential: "TC", area: "Education" },
  { name: "Information Technology", url: "https://catalog.broward.edu/technical-certificates/information-technology-advanced/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Cybersecurity and Ethical Hacking AA Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-cybersecurity-ethical-hacking-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Cybersecurity and Ethical Hacking AS Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-cybersecurity-ethical-hacking-asbas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Immersive Technologies AA Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-immersive-technologies-aabas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Immersive Technologies AS Graduates", url: "https://catalog.broward.edu/programs-study/information-technology-immersive-technologies-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Network Systems Analyst AA Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-network-systems-analyst-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Network Systems Analyst AS Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-network-systems-analyst-basas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Project Management AA Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-project-management-aabas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Project Management AS Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-project-management-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Web Development AA Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-web-development-aabas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology - Web Development AS Graduate", url: "https://catalog.broward.edu/programs-study/information-technology-web-development-bas/", level: "bachelor", credential: "BAS", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology Analyst", url: "https://catalog.broward.edu/technical-certificates/information-technology-analyst/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Information Technology Support Specialist", url: "https://catalog.broward.edu/technical-certificates/information-technology-support-specialist/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Interactive Media Production", url: "https://catalog.broward.edu/technical-certificates/interactive-media-production-technical-certificate/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Interactive Media Support", url: "https://catalog.broward.edu/technical-certificates/interactive-media-support-/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Lean Manufacturing", url: "https://catalog.broward.edu/technical-certificates/lean-manufacturing/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Lean Six Sigma Green", url: "https://catalog.broward.edu/technical-certificates/lean-six-sigma-green/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Logistics & Transportation Specialist", url: "https://catalog.broward.edu/technical-certificates/logistics--transportation-specialist/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Mammography", url: "https://catalog.broward.edu/technical-certificates/mammography-advanced-technical-certificate/", level: "certificate", credential: "ATC", area: "Health Sciences" },
  { name: "Marine Electrician", url: "https://catalog.broward.edu/technical-certificates/marine-electrician/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Marine Engineering Management", url: "https://catalog.broward.edu/programs-study/marine-engineering-management-aas/", level: "associate", credential: "AAS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Marine Propulsion Technician", url: "https://catalog.broward.edu/technical-certificates/marine-propulsion-technician/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Marine Systems", url: "https://catalog.broward.edu/technical-certificates/marine-systems/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Marine Technology", url: "https://catalog.broward.edu/technical-certificates/marine-technology/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Marketing Management", url: "https://catalog.broward.edu/programs-study/marketing-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Marketing Operations", url: "https://catalog.broward.edu/technical-certificates/marketing-operations/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Mathematics Education - Middle Grades (5-9)", url: "https://catalog.broward.edu/programs-study/mathematics-education-middle-grades-bsed/", level: "bachelor", credential: "BS", area: "Education" },
  { name: "Mathematics Education - Secondary (6-12)", url: "https://catalog.broward.edu/programs-study/mathematics-education-secondary-mathematics-6-12-bsed/", level: "bachelor", credential: "BS", area: "Education" },
  { name: "Mechatronics", url: "https://catalog.broward.edu/technical-certificates/mechatronics/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Medical Laboratory Technology", url: "https://catalog.broward.edu/programs-study/medical-laboratory-technology-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Medical Office Management", url: "https://catalog.broward.edu/programs-study/medical-office-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Medical Office Management", url: "https://catalog.broward.edu/technical-certificates/medical-office-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Medical Office Specialist", url: "https://catalog.broward.edu/technical-certificates/medical-office-specialist-technical-certificate/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Medical Quality Systems", url: "https://catalog.broward.edu/technical-certificates/medical-quality-systems/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Motion Picture Post Production", url: "https://catalog.broward.edu/technical-certificates/motion-picture-post-production/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Motion Picture Production", url: "https://catalog.broward.edu/technical-certificates/motion-picture-production/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Motion Picture Production Management", url: "https://catalog.broward.edu/technical-certificates/motion-picture-production-management/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Music Technology", url: "https://catalog.broward.edu/programs-study/music-technology-as/", level: "associate", credential: "AS", area: "Arts, Humanities, Communication, and Design" },
  { name: "Network Admin", url: "https://catalog.broward.edu/technical-certificates/network-admin-advanced/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Network Infrastructure", url: "https://catalog.broward.edu/technical-certificates/network-infrastructure/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Network Server Administration", url: "https://catalog.broward.edu/technical-certificates/network-server-administration/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Network Systems Technology - Cloud Architecting", url: "https://catalog.broward.edu/programs-study/network-systems-technology-cloud-architecting-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Network Systems Technology - Network Administration", url: "https://catalog.broward.edu/programs-study/network-systems-technology-network-administration-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Network Systems Technology - Network Security/Cybersecurity", url: "https://catalog.broward.edu/programs-study/network-systems-technology-network-securitycybersecurity-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "New Media Communication", url: "https://catalog.broward.edu/programs-study/new-media-communication-as/", level: "associate", credential: "AS", area: "Arts, Humanities, Communication, and Design" },
  { name: "Nuclear Medicine Technology", url: "https://catalog.broward.edu/programs-study/nuclear-medicine-technology-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Nuclear Medicine Technology (Hospital-Based)", url: "https://catalog.broward.edu/programs-study/nuclear-medicine-technology-hospital-based-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Nursing", url: "https://catalog.broward.edu/programs-study/bachelor-science-nursing-bsn/", level: "bachelor", credential: "BSN", area: "Health Sciences" },
  { name: "Nursing (Generic-RN)", url: "https://catalog.broward.edu/programs-study/nursing-generic-rn-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Nursing (LPN-RN Transition)", url: "https://catalog.broward.edu/programs-study/nursing-lpn-rn-transition-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Office Management", url: "https://catalog.broward.edu/programs-study/office-management-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Office Management", url: "https://catalog.broward.edu/technical-certificates/office-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Office Specialist", url: "https://catalog.broward.edu/technical-certificates/office-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Office Support", url: "https://catalog.broward.edu/technical-certificates/office-support/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Ophthalmic Eyecare Technician", url: "https://catalog.broward.edu/technical-certificates/ophthalmic-eyecare-technician/", level: "certificate", credential: "TC", area: "Health Sciences" },
  { name: "Paralegal Studies", url: "https://catalog.broward.edu/programs-study/paralegal-studies-as/", level: "associate", credential: "AS", area: "Business" },
  { name: "Paramedic", url: "https://catalog.broward.edu/technical-certificates/paramedic/", level: "certificate", credential: "TC", area: "Health Sciences" },
  { name: "Physical Therapist Assistant", url: "https://catalog.broward.edu/programs-study/physical-therapist-assistant-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Pneumatics Hydraulics", url: "https://catalog.broward.edu/technical-certificates/pneumatics-hydraulics/", level: "certificate", credential: "TC", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Police Academy Basic Recruit Training", url: "https://catalog.broward.edu/programs-study/police-academy-basic-recruit-training/", level: "certificate", credential: "VC", area: "Public Safety" },
  { name: "Preschool Specialization", url: "https://catalog.broward.edu/technical-certificates/preschool-specialization/", level: "certificate", credential: "TC", area: "Education" },
  { name: "Professional Pilot Technology", url: "https://catalog.broward.edu/programs-study/professional-pilot-technology-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Project Management", url: "https://catalog.broward.edu/technical-certificates/project-management/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Project Management Associate", url: "https://catalog.broward.edu/technical-certificates/project-management-associate/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Radiation Therapy", url: "https://catalog.broward.edu/programs-study/radiation-therapy-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Radiation Therapy (Hospital-Based)", url: "https://catalog.broward.edu/programs-study/radiation-therapy-hospital-based-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Radiography", url: "https://catalog.broward.edu/programs-study/radiography-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Radiography (Hospital-Based)", url: "https://catalog.broward.edu/programs-study/radiography-hospital-based-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Real Estate Specialist", url: "https://catalog.broward.edu/technical-certificates/real-estate-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Respiratory Care", url: "https://catalog.broward.edu/programs-study/respiratory-care-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Rooms Division Management", url: "https://catalog.broward.edu/technical-certificates/rooms-division-management/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Rooms Division Operations", url: "https://catalog.broward.edu/technical-certificates/rooms-division-operations/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Rooms Division Specialist", url: "https://catalog.broward.edu/technical-certificates/rooms-division-specialist/", level: "certificate", credential: "TC", area: "Business" },
  { name: "Secondary Biology", url: "https://catalog.broward.edu/programs-study/secondary-biology-bsed-program/", level: "bachelor", credential: "BS", area: "Education" },
  { name: "Social Media Writing", url: "https://catalog.broward.edu/technical-certificates/social-media-writing-technical-certificate/", level: "certificate", credential: "TC", area: "Arts, Humanities, Communication, and Design" },
  { name: "Software Development - Computer Programming & Analysis", url: "https://catalog.broward.edu/programs-study/software-development-computer-programming--analysis-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Software Development - Web Development", url: "https://catalog.broward.edu/programs-study/software-development-web-development-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Supervision & Management - Applied Business Analytics", url: "https://catalog.broward.edu/programs-study/supervision--management-bachelor-applied-science---applied-business-analytics/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supervision & Management - Emergency Management Services", url: "https://catalog.broward.edu/programs-study/supervision-management-emergency-management-services-bas/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supervision & Management - Human Resources", url: "https://catalog.broward.edu/programs-study/supervision-management-human-resources-bas/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supervision & Management - Management", url: "https://catalog.broward.edu/programs-study/supervision-management-management-bas/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supervision & Management - Marketing and Sales", url: "https://catalog.broward.edu/programs-study/supervision-management--marketing-sales-bas/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supervision & Management - Project Management", url: "https://catalog.broward.edu/programs-study/supervision-management-project-management-bas/", level: "bachelor", credential: "BAS", area: "Business" },
  { name: "Supply Chain Management", url: "https://catalog.broward.edu/programs-study/supply-chain-management-bas/", level: "bachelor", credential: "BAS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Supply Chain Management Operations", url: "https://catalog.broward.edu/programs-study/supply-chain-management-operations-as/", level: "associate", credential: "AS", area: "Industry, Manufacturing, Construction, and Transportation" },
  { name: "Technology Project Management - Project Management", url: "https://catalog.broward.edu/programs-study/technology-project-management-pm-track-a-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Technology Project Management - Quality and Six Sigma", url: "https://catalog.broward.edu/programs-study/technology-project-management-pm-track-b-as/", level: "associate", credential: "AS", area: "Science, Technology, Engineering, and Math" },
  { name: "Technology Project Manager", url: "https://catalog.broward.edu/technical-certificates/technology-project-manager/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
  { name: "Vision Care Technology/Opticianry", url: "https://catalog.broward.edu/programs-study/vision-care-technologyopticianry-as/", level: "associate", credential: "AS", area: "Health Sciences" },
  { name: "Web Development", url: "https://catalog.broward.edu/technical-certificates/web-development/", level: "certificate", credential: "ATC", area: "Science, Technology, Engineering, and Math" },
  { name: "Web Programming Specialist", url: "https://catalog.broward.edu/technical-certificates/web-programming-specialist/", level: "certificate", credential: "TC", area: "Science, Technology, Engineering, and Math" },
];

// A state college's pathways start at an associate degree, so an unqualified
// program name should resolve there rather than to a bachelor's.
export const browardCatalog = createProgramCatalog(BROWARD_PROGRAMS, {
  preferred: "associate",
});
