// CF program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.cf.edu/content.php?catoid=24&navoid=2598 (Programs by Degree Type)
// Scraped:  2026-07-25
// Programs: 100 (31 associate, 58 certificate, 11 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const CF_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2336", level: "associate", credential: "A.S." },
  { name: "Agribusiness Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2341", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2344", level: "associate", credential: "A.S." },
  { name: "Cardiovascular Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2606", level: "associate", credential: "A.S." },
  { name: "Computer Information Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2353", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2360", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2594", level: "associate", credential: "A.S." },
  { name: "Diagnostic Medical Sonography Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2597", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2367", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2370", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Advanced Manufacturing Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2375", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Electronics Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2373", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Quality Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2374", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Supply Chain Automation Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2600", level: "associate", credential: "A.S." },
  { name: "Equine Studies - Business Management Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2382", level: "associate", credential: "A.S." },
  { name: "Equine Studies - Equine Exercise Physiology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2383", level: "associate", credential: "A.S." },
  { name: "Fire Science Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2593", level: "associate", credential: "A.S." },
  { name: "Graphics Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2602", level: "associate", credential: "A.S." },
  { name: "Hospitality and Tourism Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2858", level: "associate", credential: "A.S." },
  { name: "Medical Office Administration", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2389", level: "associate", credential: "A.S." },
  { name: "Nursing - L.P.N to A.D.N. Bridge", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2390", level: "associate", credential: "A.S." },
  { name: "Nursing - Paramedic to A.D.N. Bridge", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2391", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2337", level: "associate", credential: "A.S." },
  { name: "Office Administration - Legal Office Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2392", level: "associate", credential: "A.S." },
  { name: "Office Administration - Office Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2393", level: "associate", credential: "A.S." },
  { name: "Physical Therapist Assistant", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2398", level: "associate", credential: "A.S." },
  { name: "Precision Agriculture Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2861", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2399", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2599", level: "associate", credential: "A.S." },
  { name: "Supply Chain Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2387", level: "associate", credential: "A.S." },
  { name: "Surgical Services", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2576", level: "associate", credential: "A.S." },
  { name: "Accounting Technology Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2338", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Operations", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2339", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2340", level: "certificate", credential: "C.C.C." },
  { name: "Artificial Intelligence Awareness", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2852", level: "certificate", credential: "C.C.C." },
  { name: "Automation", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2378", level: "certificate", credential: "C.C.C." },
  { name: "Business Entrepreneurship", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2347", level: "certificate", credential: "C.C.C." },
  { name: "Business Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2345", level: "certificate", credential: "C.C.C." },
  { name: "Business Operations", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2346", level: "certificate", credential: "C.C.C." },
  { name: "Business Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2348", level: "certificate", credential: "C.C.C." },
  { name: "Child Care Center Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2368", level: "certificate", credential: "C.C.C." },
  { name: "Computer Information Data Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2359", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2358", level: "certificate", credential: "C.C.C." },
  { name: "Criminal Justice Technology Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2361", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media/Multimedia Authoring", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2363", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media/Multimedia Web Production", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2364", level: "certificate", credential: "C.C.C." },
  { name: "Digital Music Production", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2366", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Development Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2369", level: "certificate", credential: "C.C.C." },
  { name: "Emergency Medical Technician (Basic)", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2371", level: "certificate", credential: "C.C.C." },
  { name: "Engineering Technology Support Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2377", level: "certificate", credential: "C.C.C." },
  { name: "Equine Assistant Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2384", level: "certificate", credential: "C.C.C." },
  { name: "Equine Technician", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2385", level: "certificate", credential: "C.C.C." },
  { name: "Geographic Information Systems", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2850", level: "certificate", credential: "C.C.C." },
  { name: "Graphic Design Support", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2365", level: "certificate", credential: "C.C.C." },
  { name: "Guest Services Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2352", level: "certificate", credential: "C.C.C." },
  { name: "Help Desk Support Technician", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2356", level: "certificate", credential: "C.C.C." },
  { name: "Human Resources Administrator", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2349", level: "certificate", credential: "C.C.C." },
  { name: "Information Technology Analysis", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2354", level: "certificate", credential: "C.C.C." },
  { name: "Information Technology Support Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2355", level: "certificate", credential: "C.C.C." },
  { name: "Landscape and Horticulture Professional", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2342", level: "certificate", credential: "C.C.C." },
  { name: "Lean Six Sigma Green Belt", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2376", level: "certificate", credential: "C.C.C." },
  { name: "Livestock Production Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2343", level: "certificate", credential: "C.C.C." },
  { name: "Logistics and Transportation Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2388", level: "certificate", credential: "C.C.C." },
  { name: "Marketing Operations", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2351", level: "certificate", credential: "C.C.C." },
  { name: "Mechanical Designer and Programmer", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2381", level: "certificate", credential: "C.C.C." },
  { name: "Mechatronics", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2379", level: "certificate", credential: "C.C.C." },
  { name: "Network Security", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2586", level: "certificate", credential: "C.C.C." },
  { name: "Office Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2396", level: "certificate", credential: "C.C.C." },
  { name: "Office Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2395", level: "certificate", credential: "C.C.C." },
  { name: "Office Support", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2394", level: "certificate", credential: "C.C.C." },
  { name: "Paramedic", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2372", level: "certificate", credential: "C.C.C." },
  { name: "Pneumatics, Hydraulics and Motors for Manufacturing", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2380", level: "certificate", credential: "C.C.C." },
  { name: "Rapid Prototyping Specialist", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2856", level: "certificate", credential: "C.C.C." },
  { name: "Scientific Workplace Preparation", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2577", level: "certificate", credential: "C.C.C." },
  { name: "Dental Assisting Technology and Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2400", level: "certificate", credential: "A.T.D." },
  { name: "Correctional Officer", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2401", level: "certificate", credential: "C.T.C." },
  { name: "Crossover from Corrections to Law Enforcement", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2402", level: "certificate", credential: "C.T.C." },
  { name: "Crossover from Law Enforcement to Corrections", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2403", level: "certificate", credential: "C.T.C." },
  { name: "Florida Law Enforcement Academy", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2404", level: "certificate", credential: "C.T.C." },
  { name: "Welding Technology - Advanced", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2407", level: "certificate", credential: "C.T.C." },
  { name: "Welding Technology", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2406", level: "certificate", credential: "C.T.C." },
  { name: "Business and Organizational Management - Accounting Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2420", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Agribusiness Management Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2409", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Equine Studies Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2414", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Health Care Management Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2411", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Human Resources Management Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2579", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Logistics and Supply Chain Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2413", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Management Information Systems Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2410", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management - Public Safety Administration Specialization", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2412", level: "bachelor", credential: "B.A.S." },
  { name: "Business and Organizational Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2408", level: "bachelor", credential: "B.A.S." },
  { name: "Early Childhood Education", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2419", level: "bachelor", credential: "B.S." },
  { name: "Registered Nurse to Bachelor of Science in Nursing", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2418", level: "bachelor", credential: "B.S.N." },
  { name: "Accounting Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2590", level: "certificate", credential: "A.T.C." },
  { name: "Basic Health Care Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2417", level: "certificate", credential: "A.T.C." },
  { name: "Basics of Agribusiness", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2585", level: "certificate", credential: "A.T.C." },
  { name: "Compensation and Benefits", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2591", level: "certificate", credential: "A.T.C." },
  { name: "Data Security", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2415", level: "certificate", credential: "A.T.C." },
  { name: "Emergency Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2589", level: "certificate", credential: "A.T.C." },
  { name: "Equine Industry Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2588", level: "certificate", credential: "A.T.C." },
  { name: "Logistics and Supply Chain Management", url: "https://catalog.cf.edu/preview_program.php?catoid=24&poid=2416", level: "certificate", credential: "A.T.C." },
];
