// Embry-Riddle Aeronautical University (Daytona Beach campus) degree
// catalog: program name -> official bulletin page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:erau
//
// Source:     https://catalog.erau.edu/daytona-beach/academic-programs/
// Scraped:    2026-07-27
// Programs:   162 (29 bachelor, 133 graduate)
//
// ERAU runs separate catalogs per campus (Daytona Beach / Prescott /
// Worldwide / Asia); this catalog is Daytona Beach only, matching
// floridaSchools.ts. "Combined Program Pathways" and "Dual Masters" are real
// individually-linked accelerated/dual-degree tracks, not duplicates — see
// the scraper's header comment. Associate-level and certificate programs are
// excluded, the same call UCF's scraper made for its own associate track.
//
// ERAU is a four-year private university (like UM/Stetson/FIU/UCF/...), so
// pathways start at the bachelor's rather than an associate degree — see
// universitySystemPrompt in app/lib/pathwayPrompts.ts.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const ERAU_PROGRAMS: SchoolProgram[] = [
  { name: "B.S. in Aeronautical Science", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/aeronautical-science/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Aeronautics", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/aeronautics/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Aerospace Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/aerospace-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Aerospace Physiology", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/aerospace-physiology/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Air Traffic Management", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/air-traffic-management/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Astronomy and Astrophysics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/astronomy-astrophysics/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Aviation and Aerospace Safety", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/aviation-aerospace-safety/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Aviation Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/bachelors/aviation-business-administration/", level: "bachelor", area: "College of Business" },
  { name: "B.S. in Aviation Maintenance Science", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/aviation-maintenance-science/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/bachelors/business-administration/", level: "bachelor", area: "College of Business" },
  { name: "B.S. in Civil Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/civil-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Communication", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/communication/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Computational Mathematics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/computational-mathematics/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Computer Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/computer-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Computer Science", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/computer-science/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Data Science", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/data-science/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Electrical Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/electrical-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Engineering Physics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/engineering-physics/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Global Conflict Studies", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/global-conflict-studies/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Homeland Security and Intelligence", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/homeland-security/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Human Factors Psychology", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/human-factors-psychology/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Interdisciplinary Studies", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/interdisciplinary-studies/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Mechanical Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/mechanical-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Meteorology", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/meteorology/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Software Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/software-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Space Operations", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/spaceflight-operations/", level: "bachelor", area: "College of Aviation" },
  { name: "B.S. in Space Physics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/bachelors/space-physics/", level: "bachelor", area: "College of Arts and Sciences" },
  { name: "B.S. in Systems Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/bachelors/systems-engineering/", level: "bachelor", area: "College of Engineering" },
  { name: "B.S. in Uncrewed Aircraft Systems", url: "https://catalog.erau.edu/daytona-beach/aviation/bachelors/uncrewed-aircraft-systems", level: "bachelor", area: "College of Aviation" },
  { name: "Any B.S. in Engineering/M.S. in Computer Science", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-computer-science-option/", level: "graduate", area: "College of Engineering" },
  { name: "Any B.S. in Engineering/M.S. in Electrical and Computer Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/Accelerated-Electrical-Computer-Engineering-Option/", level: "graduate", area: "College of Engineering" },
  { name: "Any B.S. in Engineering/M.S. in Mechanical Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-mechanical-engineering-option/", level: "graduate", area: "College of Engineering" },
  { name: "Any B.S. in Engineering/M.S. in Software Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-software-engineering-option/", level: "graduate", area: "College of Engineering" },
  { name: "Any B.S. in Engineering/M.S. in Systems Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-systems-engineering-option/", level: "graduate", area: "College of Engineering" },
  { name: "Any B.S. in Engineering/M.S. in Uncrewed and Autonomous Systems Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/combined-uncrewed-and-autonomous-systems-engineering-option/index.html", level: "graduate", area: "College of Engineering" },
  { name: "B.S. in Aeronautical Science/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/as_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautical Science/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/accelerated_bsas_msav/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aeronautical Science/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/as_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautical Science/M.S. in Uncrewed Systems", url: "https://catalog.erau.edu/daytona-beach/aviation/bsas_msunc", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aeronautical Science/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/as_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautical Science/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/as_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautics/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsa-msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautics/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/acc-aeronautics/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aeronautics/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsa-msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautics/M.S. in Uncrewed Systems", url: "https://catalog.erau.edu/daytona-beach/aviation/bsa_msunc/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aeronautics/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/aeronautics_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aeronautics/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsa-mbaam", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Engineering/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/ae_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Engineering/M.S. in Aerospace Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-aerospace-engineering-option/", level: "graduate", area: "College of Engineering" },
  { name: "B.S. in Aerospace Engineering/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/ae_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Engineering/M.S. in Data Science", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsae_msds/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Aerospace Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/business/combined/aerospaceengineering_mshf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/aerospaceengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Engineering/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/ae_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Physiology/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsap-msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Physiology/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsap-msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Physiology/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsap_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Aerospace Physiology/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsap-mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aerospace Physiology/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsap-mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Astronomy and Astrophysics/M.S. in Data Science", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsaa_msds/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Aviation and Aerospace Safety/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/bsaas_msav/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aviation and Aerospace Safety/M.S. in Occupational Safety Management", url: "https://catalog.erau.edu/daytona-beach/aviation/bsaas_msosm/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aviation Business Administration/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsaba_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aviation Business Administration/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsaba_msfin/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aviation Business Administration/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsaba_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aviation Business Administration/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsaba_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Aviation Maintenance Science/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/ams_msa/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Aviation Maintenance Science/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/ams_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Business Administration/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsba_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Business Administration/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsba_msfin/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Business Administration/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/business-administration/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Business Administration/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsba_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Civil Engineering/M.S. in Civil Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/accelerated-civil-engineering-option/", level: "graduate", area: "College of Engineering" },
  { name: "B.S. in Civil Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsciv_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Civil Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/civilengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Communication/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/communication_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computational Math/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/computationalmath_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computational Math/M.S. in Data Science", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bscm_msds/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Computational Math/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/computationalmath_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Engineering/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsce_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Engineering/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsce_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsce_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Computer Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/computerengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Engineering/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsce_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Science/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bscs_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Science/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bscs_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Science/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bscs_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Computer Science/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/computerscience_mba/index.html", level: "graduate", area: "College of Business" },
  { name: "B.S. in Computer Science/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bscs_mbaam/index.html", level: "graduate", area: "College of Business" },
  { name: "B.S. in Electrical Engineering/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsee_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Electrical Engineering/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsee_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Electrical Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsee_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Electrical Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/electricalengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Electrical Engineering/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsee_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Engineering Physics/M.S. in Engineering Physics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/accelerated/engineeringphysics/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Engineering Physics/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsep_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Global Conflict Studies/M.S. in Human Security and Resilience", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/globalconflictstudies_mshsr/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Global Conflict Studies/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/globalconflictstudies_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Homeland Security and Intelligence/M.S. in Human Security and Resilience (Worldwide)", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/homelandsecurity_mshsr/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Homeland Security and Intelligence/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/homelandsecurity_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Human Factors Psychology/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/accelerated/humanfactorspsychology_mshf/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Human Factors Psychology/M.S. in Human Factors (Worldwide)", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/dbshfp_wmshf/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Human Factors Psychology/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/humanfactorspsychology_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Interdisciplinary Studies/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsis_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Interdisciplinary Studies/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/interdisciplinarystudies_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Mechanical Engineering/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsme_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Mechanical Engineering/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsme_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Mechanical Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsme_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Mechanical Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/mechanicalengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Mechanical Engineering/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsme_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Meteorology/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/accelerated_bsmet_msav/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Software Engineering/M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsse_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Software Engineering/M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsse_msaf/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Software Engineering/M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/combined/bsse_mshf/index.html", level: "graduate", area: "College of Arts and Sciences" },
  { name: "B.S. in Software Engineering/Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/combined/softwareengineering_mba/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Software Engineering/MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/combined/bsse_mbaam/", level: "graduate", area: "College of Business" },
  { name: "B.S. in Space Operations/M.S. in Space Operations", url: "https://catalog.erau.edu/daytona-beach/aviation/combined_bsso_msso/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Uncrewed Aircraft Systems/M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/bsunc_msav/", level: "graduate", area: "College of Aviation" },
  { name: "B.S. in Uncrewed Aircraft Systems/M.S. in Uncrewed Systems", url: "https://catalog.erau.edu/daytona-beach/aviation/bsunc_msunc/", level: "graduate", area: "College of Aviation" },
  { name: "Contact Us", url: "https://catalog.erau.edu/daytona-beach/contact/", level: "graduate", area: "Embry-Riddle Aeronautical University" },
  { name: "Doctor of Aviation Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/phd/aviation-business-adminstration/", level: "graduate", area: "College of Business" },
  { name: "Embry-Riddle Daytona Beach", url: "http://daytonabeach.erau.edu", level: "graduate", area: "Embry-Riddle Aeronautical University" },
  { name: "M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/masters/aerospace_business_analytics/", level: "graduate", area: "College of Business" },
  { name: "M.S. in Aerospace Business Analytics and M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/msaebuan_msav/", level: "graduate", area: "College of Business" },
  { name: "M.S. in Aerospace Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/aerospace-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/masters/aeronautics/", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Aviation and M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/aviation/dual-masters-programs/msav-msaebuan/", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Aviation and M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/aviation/dual-masters-programs/msav_msaf/", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Aviation and Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/aviation/dual-masters-programs/msav_mba/", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Aviation and MBA in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/aviation/dual-masters-programs/msav_mbaam/", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/masters/aviation-finance/", level: "graduate", area: "College of Business" },
  { name: "M.S. in Aviation Finance and M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/msaf_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "M.S. in Aviation Finance and M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/msaf_msav/", level: "graduate", area: "College of Business" },
  { name: "M.S. in Civil Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/civil-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Computer Science", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/computer-science/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Data Science", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/masters/data-science/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "M.S. in Electrical and Computer Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/computer-electrical-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Engineering and Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/dual-engineering-mba/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Engineering Physics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/masters/engineering-physics/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "M.S. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/masters/human-factors-systems/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "M.S. in Mechanical Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/mechanical-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Occupational Safety Management", url: "https://catalog.erau.edu/daytona-beach/aviation/masters/occupational-safety-management/index.html", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Software Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/software-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Space Operations", url: "https://catalog.erau.edu/daytona-beach/aviation/masters/space_operations", level: "graduate", area: "College of Aviation" },
  { name: "M.S. in Systems Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/systems-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Uncrewed and Autonomous Systems Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/masters/uncrewed-autonomous-systems-engineering", level: "graduate", area: "College of Engineering" },
  { name: "M.S. in Uncrewed Systems", url: "https://catalog.erau.edu/daytona-beach/aviation/masters/uncrewed_systems/", level: "graduate", area: "College of Aviation" },
  { name: "Master of Business Administration", url: "https://catalog.erau.edu/daytona-beach/business/masters/business-administration/", level: "graduate", area: "College of Business" },
  { name: "Master of Business Administration and M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mba_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "Master of Business Administration and M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mba_msav/", level: "graduate", area: "College of Business" },
  { name: "Master of Business Administration and M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mba_msaf/", level: "graduate", area: "College of Business" },
  { name: "Master of Business Administration in Aviation Management", url: "https://catalog.erau.edu/daytona-beach/business/masters/aviation-management/", level: "graduate", area: "College of Business" },
  { name: "MBA in Aviation Management and M.S. in Aerospace Business Analytics", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mbaam_msaebuan/", level: "graduate", area: "College of Business" },
  { name: "MBA in Aviation Management and M.S. in Aviation", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mbaam_msav/", level: "graduate", area: "College of Business" },
  { name: "MBA in Aviation Management and M.S. in Aviation Finance", url: "https://catalog.erau.edu/daytona-beach/business/dual-masters-programs/mbaam_msaf/", level: "graduate", area: "College of Business" },
  { name: "Ph.D. in Aerospace Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/phd/aerospace-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "Ph.D. in Aviation", url: "https://catalog.erau.edu/daytona-beach/aviation/phd/aviation/", level: "graduate", area: "College of Aviation" },
  { name: "Ph.D. in Electrical Engineering and Computer Science", url: "https://catalog.erau.edu/daytona-beach/engineering/phd/electrical-engineering-and-computer-science/", level: "graduate", area: "College of Engineering" },
  { name: "Ph.D. in Engineering Physics", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/phd/engineering-physics/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "Ph.D. in Human Factors", url: "https://catalog.erau.edu/daytona-beach/arts-sciences/phd/human-factors/", level: "graduate", area: "College of Arts and Sciences" },
  { name: "Ph.D. in Mechanical Engineering", url: "https://catalog.erau.edu/daytona-beach/engineering/phd/mechanical-engineering/", level: "graduate", area: "College of Engineering" },
  { name: "Terms of Use", url: "https://catalog.erau.edu/daytona-beach/terms-of-use/", level: "graduate", area: "Embry-Riddle Aeronautical University" },
];

// ERAU is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const erauCatalog = createProgramCatalog(ERAU_PROGRAMS, { preferred: "bachelor" });
