// FAU degree catalog: program name -> the program's COLLEGE catalog page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:fau
//
// Source:     https://www.fau.edu/registrar/university-catalog/catalog/degree-programs/
// Scraped:    2026-07-27
// Programs:   156 (74 bachelor, 82 graduate)
//
// FAU has no per-program catalog page at all — every major on this page
// links only to its COLLEGE's catalog page (e.g. "(College of Science)"), so
// that college link is what every program here points to. No WAF blocks
// this site, unlike FAMU/FlPoly/USF's Acalog catalogs.
//
// Excluded: "combined degree" headings (e.g. "B.A./M.A.") that mix two
// credential levels under one heading; A.A., B.S.E., and B.G.S. (no real
// college link); majors tagged suspended/not-accepting-students.
//
// FAU is a four-year university (like FIU/UCF/UF/FGCU/UWF/NCF/UNF/FlPoly/USF),
// so pathways start at the bachelor's rather than an associate degree.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const FAU_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Anthropology", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Art", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Art", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.F.A.", area: "College of Arts and Letters" },
  { name: "Bachelor of Architecture", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.Arch.", area: "College of Arts and Letters" },
  { name: "Bachelor of Business Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.B.A.", area: "College of Business" },
  { name: "Bachelor of Early Care and Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "bachelor", credential: "B.E.C.E.", area: "College of Education" },
  { name: "Bachelor of Music Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.M.E.", area: "College of Arts and Letters and College of Education" },
  { name: "Bachelor of Professional Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/interdis-programs/", level: "bachelor", credential: "B.P.S.", area: "Interdisciplinary Programs" },
  { name: "Bachelor of Public Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.P.M.", area: "College of Arts and Letters" },
  { name: "Bachelor of Public Safety Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.P.S.A.", area: "College of Arts and Letters" },
  { name: "Bachelor of Social Work", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "bachelor", credential: "B.S.W.", area: "College of Social Work and Criminal Justice" },
  { name: "Bachelor of Urban and Regional Planning", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.U.R.P.", area: "College of Science" },
  { name: "Bachelor of Urban Design", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.U.D.", area: "College of Science" },
  { name: "Biological and Physical Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/honors/", level: "bachelor", credential: "B.A.", area: "Honors College" },
  { name: "Biological and Physical Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/honors/", level: "bachelor", credential: "B.S.", area: "Honors College" },
  { name: "Biological Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Biological Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Biomedical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.", area: "College of Engineering and Computer Science" },
  { name: "Chemistry", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Chemistry", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Civil Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.C.V.", area: "College of Engineering and Computer Science" },
  { name: "Commercial Music", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.M.", area: "College of Arts and Letters" },
  { name: "Communication Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Computer Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.C.E.", area: "College of Engineering and Computer Science" },
  { name: "Computer Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.A.C.S.", area: "College of Engineering and Computer Science" },
  { name: "Computer Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.C.S.", area: "College of Engineering and Computer Science" },
  { name: "Criminal Justice", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "bachelor", credential: "B.A.", area: "College of Social Work and Criminal Justice" },
  { name: "Data Science and Analytics", url: "https://www.fau.edu/registrar/university-catalog/catalog/interdis-programs/", level: "bachelor", credential: "B.S.", area: "Interdisciplinary Programs" },
  { name: "Economics", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Electrical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.E.E.", area: "College of Engineering and Computer Science" },
  { name: "Elementary Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "bachelor", credential: "B.A.", area: "College of Education" },
  { name: "English", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Environmental Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.E.V.", area: "College of Engineering and Computer Science" },
  { name: "Exceptional Student Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "bachelor", credential: "B.A.", area: "College of Education" },
  { name: "Exercise Science and Health Promotion", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Finance", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "General Business", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.A.", area: "College of Business" },
  { name: "Geomatics Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.G.E.", area: "College of Engineering and Computer Science" },
  { name: "Geosciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Geosciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Global Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Health Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.H.S.", area: "College of Business" },
  { name: "Health Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "History", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Hospitality & Tourism", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.A.", area: "College of Business" },
  { name: "Hospitality & Tourism Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Interdisciplinary Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "International Business", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Jewish Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Languages, Linguistics and Comparative Literature", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Liberal Arts and Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/honors/", level: "bachelor", credential: "B.A.", area: "Honors College" },
  { name: "Liberal Arts and Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/honors/", level: "bachelor", credential: "B.S.", area: "Honors College" },
  { name: "Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Management Information Systems", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Marketing", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "bachelor", credential: "B.S.", area: "College of Business" },
  { name: "Mathematics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Mathematics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Mechanical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.M.E.", area: "College of Engineering and Computer Science" },
  { name: "Medical Biology", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Multimedia Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Music", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Music", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.M.", area: "College of Arts and Letters" },
  { name: "Neuroscience and Behavior", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Nursing", url: "https://www.fau.edu/registrar/university-catalog/catalog/nursing/", level: "bachelor", credential: "B.S.N.", area: "College of Nursing" },
  { name: "Ocean Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "bachelor", credential: "B.S.O.E.", area: "College of Engineering and Computer Science" },
  { name: "Philosophy", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.S.", area: "College of Science" },
  { name: "Political Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Psychology", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "bachelor", credential: "B.A.", area: "College of Science" },
  { name: "Sociology", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Theatre", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.A.", area: "College of Arts and Letters" },
  { name: "Theatre", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "bachelor", credential: "B.F.A.", area: "College of Arts and Letters" },
  { name: "Anthropology", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Anthropology", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.T.", area: "College of Arts and Letters" },
  { name: "Artificial Intelligence", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Biological Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Biological Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.T.", area: "College of Science" },
  { name: "Biomedical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Biomedical Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/biomedical/", level: "graduate", credential: "M.S.", area: "College of Medicine" },
  { name: "Business Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.B.A.", area: "College of Business" },
  { name: "Business Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "Ph.D.", area: "College of Business" },
  { name: "Business Analytics", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.S.", area: "College of Business" },
  { name: "Business Biotechnology", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "P.S.M.", area: "College of Science and College of Business" },
  { name: "Chemistry", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Chemistry", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.T.", area: "College of Science" },
  { name: "Chemistry", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "Civil Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Communication", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Comparative Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "Ph.D.", area: "College of Arts and Letters" },
  { name: "Complex Systems and Brain Sciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "Computer Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Computer Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "Computer Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Computer Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "Counseling", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "Ph.D.", area: "College of Education" },
  { name: "Creative Writing", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.F.A.", area: "College of Arts and Letters" },
  { name: "Criminology and Criminal Justice", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "graduate", credential: "M.S.", area: "College of Social Work and Criminal Justice" },
  { name: "Curriculum and Instruction", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "Ph.D.", area: "College of Education" },
  { name: "Data Science and Analytics", url: "https://www.fau.edu/registrar/university-catalog/catalog/interdis-programs/", level: "graduate", credential: "M.S.", area: "Interdisciplinary Programs" },
  { name: "Doctor of Medicine", url: "https://www.fau.edu/registrar/university-catalog/catalog/biomedical/", level: "graduate", credential: "M.D.", area: "College of Medicine" },
  { name: "Doctor of Nursing Practice", url: "https://www.fau.edu/registrar/university-catalog/catalog/nursing/", level: "graduate", credential: "D.N.P.", area: "College of Nursing" },
  { name: "DOCTOR OF SOCIAL WORK (D.S.W.)", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "graduate", credential: "Ph.D.", area: "College of Social Work and Criminal Justice" },
  { name: "Economics", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.S.", area: "College of Business" },
  { name: "Economics", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.S.T.", area: "College of Business" },
  { name: "Educational Leadership", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "Ph.D.", area: "College of Education" },
  { name: "Electrical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "English", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Environmental Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Exercise Science and Health Promotion", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Experimental Psychology", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "Geosciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Geosciences", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "History", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Information Technology and Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/interdis-programs/", level: "graduate", credential: "M.S.", area: "Interdisciplinary Programs" },
  { name: "Integrative Biology (College of Medicine and", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "International Business", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.S.", area: "College of Business" },
  { name: "Languages, Linguistics and Comparative Literature", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Marine Science and Oceanography", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Master of Accounting", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.AC.", area: "College of Business" },
  { name: "Master of Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "M.Ed.", area: "College of Education" },
  { name: "Master of Health Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.H.A.", area: "College of Business" },
  { name: "Master of Nonprofit Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.N.M.", area: "College of Arts and Letters" },
  { name: "Master of Public Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.P.A.", area: "College of Arts and Letters" },
  { name: "Master of Social Work", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "graduate", credential: "M.S.W.", area: "College of Social Work and Criminal Justice" },
  { name: "Master of Taxation", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.TX.", area: "College of Business" },
  { name: "Master of Urban and Regional Planning", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.U.R.P.", area: "College of Science" },
  { name: "Mathematics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Mathematics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.T.", area: "College of Science" },
  { name: "Mathematics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "Mechanical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Mechanical Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "Medical Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "P.S.M.", area: "College of Science" },
  { name: "Music", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.M.", area: "College of Arts and Letters" },
  { name: "Neuroscience", url: "https://www.fau.edu/registrar/university-catalog/catalog/interdis-programs/", level: "graduate", credential: "Ph.D.", area: "Interdisciplinary Programs" },
  { name: "Nursing", url: "https://www.fau.edu/registrar/university-catalog/catalog/nursing/", level: "graduate", credential: "M.S.N.", area: "College of Nursing" },
  { name: "Nursing", url: "https://www.fau.edu/registrar/university-catalog/catalog/nursing/", level: "graduate", credential: "Ph.D.", area: "College of Nursing" },
  { name: "Ocean Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "M.S.", area: "College of Engineering and Computer Science" },
  { name: "Ocean Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.", area: "College of Science" },
  { name: "Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.S.T.", area: "College of Science" },
  { name: "Physics", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "Ph.D.", area: "College of Science" },
  { name: "Political Science", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Psychology", url: "https://www.fau.edu/registrar/university-catalog/catalog/science/", level: "graduate", credential: "M.A.", area: "College of Science" },
  { name: "Public Administration", url: "https://www.fau.edu/registrar/university-catalog/catalog/sw-cj/", level: "graduate", credential: "Ph.D.", area: "College of Arts and Letters" },
  { name: "Sociology", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
  { name: "Special Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "Ph.D.", area: "College of Education" },
  { name: "Specialist in Education", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "Ed.S.", area: "College of Education" },
  { name: "Speech-Language Pathology/Audiology", url: "https://www.fau.edu/registrar/university-catalog/catalog/education/", level: "graduate", credential: "M.S.", area: "College of Education" },
  { name: "Studio/Fine Arts", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.F.A.", area: "College of Arts and Letters" },
  { name: "Supply Chain Management", url: "https://www.fau.edu/registrar/university-catalog/catalog/business/", level: "graduate", credential: "M.S.", area: "College of Business" },
  { name: "Theatre", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.F.A.", area: "College of Arts and Letters" },
  { name: "Transportation and Environmental Engineering", url: "https://www.fau.edu/registrar/university-catalog/catalog/engineering/", level: "graduate", credential: "Ph.D.", area: "College of Engineering and Computer Science" },
  { name: "Women, Gender and Sexuality Studies", url: "https://www.fau.edu/registrar/university-catalog/catalog/artsandletters/", level: "graduate", credential: "M.A.", area: "College of Arts and Letters" },
];

// FAU is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const fauCatalog = createProgramCatalog(FAU_PROGRAMS, { preferred: "bachelor" });
