// FGCU degree catalog: program name -> official program page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:fgcu
//
// Source:     https://catalog.fgcu.edu/programs/
// Scraped:    2026-07-26
// Programs:   102 (66 bachelor, 36 graduate)
//
// FGCU is a four-year university (like FIU/UCF/UF), so pathways start at the
// bachelor's rather than an associate degree. Every entry's own credential
// (e.g. "B.S.", "M.S.", "D.N.P.") comes straight from FGCU's single combined
// A-Z program sitemap — no area/college field, since that page doesn't
// expose one and guessing would be worse than leaving it out.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const FGCU_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting", url: "https://catalog.fgcu.edu/programs/accounting-bs/", level: "bachelor", credential: "B.S." },
  { name: "Accounting and Taxation", url: "https://catalog.fgcu.edu/programs/accounting-taxation-ms/", level: "graduate", credential: "M.S." },
  { name: "Analytics and Informatics", url: "https://catalog.fgcu.edu/programs/analytics-informatics-bs/", level: "bachelor", credential: "B.S." },
  { name: "Anthropology", url: "https://catalog.fgcu.edu/programs/anthropology-ba/", level: "bachelor", credential: "B.A." },
  { name: "Applied Mathematics", url: "https://catalog.fgcu.edu/programs/applied-mathematics-ms/", level: "graduate", credential: "M.S." },
  { name: "Art", url: "https://catalog.fgcu.edu/programs/art-ba/", level: "bachelor", credential: "B.A." },
  { name: "Biochemistry", url: "https://catalog.fgcu.edu/programs/biochemistry-bs/", level: "bachelor", credential: "B.S." },
  { name: "Bioengineering", url: "https://catalog.fgcu.edu/programs/bioengineering-bs/", level: "bachelor", credential: "B.S." },
  { name: "Biology", url: "https://catalog.fgcu.edu/programs/biology-ba/", level: "bachelor", credential: "B.A." },
  { name: "Biology", url: "https://catalog.fgcu.edu/programs/biology-bs/", level: "bachelor", credential: "B.S." },
  { name: "Biology", url: "https://catalog.fgcu.edu/programs/biology-ms/", level: "graduate", credential: "M.S." },
  { name: "Biology-Accelerated", url: "https://catalog.fgcu.edu/programs/biologyaccelerated-bs/", level: "bachelor", credential: "B.S." },
  { name: "Biotechnology", url: "https://catalog.fgcu.edu/programs/biotechnology-bs/", level: "bachelor", credential: "B.S." },
  { name: "BSN to DNP Nurse Anesthesiology", url: "https://catalog.fgcu.edu/programs/bsn-dnp-nrse-anesthesiology-dnp/", level: "graduate", credential: "D.N.P." },
  { name: "BSN to DNP Nurse Practitioner", url: "https://catalog.fgcu.edu/programs/bsn-dnp-nurse-practitioner-dnp/", level: "graduate", credential: "D.N.P." },
  { name: "Business Administration", url: "https://catalog.fgcu.edu/programs/business-administration-mba/", level: "graduate", credential: "M.B.A." },
  { name: "Business Analytics", url: "https://catalog.fgcu.edu/programs/busana-mba/", level: "graduate", credential: "M.B.A." },
  { name: "Chemistry", url: "https://catalog.fgcu.edu/programs/chemistry-ba/", level: "bachelor", credential: "B.A." },
  { name: "Chemistry", url: "https://catalog.fgcu.edu/programs/chemistry-bs/", level: "bachelor", credential: "B.S." },
  { name: "Child and Youth Studies", url: "https://catalog.fgcu.edu/programs/child-youth-studies-bs/", level: "bachelor", credential: "B.S." },
  { name: "Civil Engineering", url: "https://catalog.fgcu.edu/programs/civil-engineering-bsce/", level: "bachelor", credential: "B.S.C.E." },
  { name: "Civil Engineering", url: "https://catalog.fgcu.edu/programs/ms-civengr/", level: "graduate", credential: "M.S." },
  { name: "Clinical Laboratory Science", url: "https://catalog.fgcu.edu/programs/clinical-laboratory-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Clinical Mental Health Counseling", url: "https://catalog.fgcu.edu/programs/clinical-mental-health-cnslng-ma/", level: "graduate", credential: "M.A." },
  { name: "Communication", url: "https://catalog.fgcu.edu/programs/communication-ba/", level: "bachelor", credential: "B.A." },
  { name: "Computer Information Systems", url: "https://catalog.fgcu.edu/programs/computer-information-systems-bs/", level: "bachelor", credential: "B.S." },
  { name: "Computer Science", url: "https://catalog.fgcu.edu/programs/computer-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Computer Science", url: "https://catalog.fgcu.edu/programs/computer-science-ms/", level: "graduate", credential: "M.S." },
  { name: "Construction Management", url: "https://catalog.fgcu.edu/programs/construction-management-bscm/", level: "bachelor", credential: "B.S.C.M." },
  { name: "Criminal Justice", url: "https://catalog.fgcu.edu/programs/criminal-justice-bs/", level: "bachelor", credential: "B.S." },
  { name: "Criminal Justice", url: "https://catalog.fgcu.edu/programs/criminal-justice-ms/", level: "graduate", credential: "M.S." },
  { name: "Curriculum and Instruction", url: "https://catalog.fgcu.edu/programs/curriculum-instruction-med/", level: "graduate", credential: "M.Ed." },
  { name: "Data Analytics and AI", url: "https://catalog.fgcu.edu/programs/data-analytics-ai-ms/", level: "graduate", credential: "M.S." },
  { name: "Digital Media Design", url: "https://catalog.fgcu.edu/programs/digital-media-design-ba/", level: "bachelor", credential: "B.A." },
  { name: "Early Childhood Education", url: "https://catalog.fgcu.edu/programs/early-childhood-education-ba/", level: "bachelor", credential: "B.A." },
  { name: "Education", url: "https://catalog.fgcu.edu/programs/education-edd/", level: "graduate", credential: "Ed.D." },
  { name: "Educational Leadership", url: "https://catalog.fgcu.edu/programs/educational-leadership-ma/", level: "graduate", credential: "M.A." },
  { name: "Educational Leadership", url: "https://catalog.fgcu.edu/programs/educational-leadership-med/", level: "graduate", credential: "M.Ed." },
  { name: "Elementary Education", url: "https://catalog.fgcu.edu/programs/elementary-education-ba/", level: "bachelor", credential: "B.A." },
  { name: "English", url: "https://catalog.fgcu.edu/programs/english-ba/", level: "bachelor", credential: "B.A." },
  { name: "English", url: "https://catalog.fgcu.edu/programs/english-ma/", level: "graduate", credential: "M.A." },
  { name: "Entrepreneurship", url: "https://catalog.fgcu.edu/programs/entrepreneurship-bs/", level: "bachelor", credential: "B.S." },
  { name: "Entrepreneurship", url: "https://catalog.fgcu.edu/programs/entrepreneurship-ms/", level: "graduate", credential: "M.S." },
  { name: "Environmental Engineering", url: "https://catalog.fgcu.edu/programs/environmental-engineering-bsenve/", level: "bachelor", credential: "B.S.Env.E." },
  { name: "Environmental Geology", url: "https://catalog.fgcu.edu/programs/environmental-geology-bs/", level: "bachelor", credential: "B.S." },
  { name: "Environmental Science", url: "https://catalog.fgcu.edu/programs/environmental-science-ms/", level: "graduate", credential: "M.S." },
  { name: "Environmental Studies", url: "https://catalog.fgcu.edu/programs/environmental-studies-ba/", level: "bachelor", credential: "B.A." },
  { name: "Environmental Studies", url: "https://catalog.fgcu.edu/programs/environmental-studies-ma/", level: "graduate", credential: "M.A." },
  { name: "Exercise Science", url: "https://catalog.fgcu.edu/programs/exercise-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Finance", url: "https://catalog.fgcu.edu/programs/finance-bs/", level: "bachelor", credential: "B.S." },
  { name: "Forensic Science", url: "https://catalog.fgcu.edu/programs/forensic-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Forensic Studies", url: "https://catalog.fgcu.edu/programs/forensic-studies-bs/", level: "bachelor", credential: "B.S." },
  { name: "Forensic Studies", url: "https://catalog.fgcu.edu/programs/forensic-studies-ms/", level: "graduate", credential: "M.S." },
  { name: "Health Administration", url: "https://catalog.fgcu.edu/programs/health-administration-bs/", level: "bachelor", credential: "B.S." },
  { name: "Health Science", url: "https://catalog.fgcu.edu/programs/health-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Health Science", url: "https://catalog.fgcu.edu/programs/health-science-ms/", level: "graduate", credential: "M.S." },
  { name: "History", url: "https://catalog.fgcu.edu/programs/history-ba/", level: "bachelor", credential: "B.A." },
  { name: "History", url: "https://catalog.fgcu.edu/programs/history-ma/", level: "graduate", credential: "M.A." },
  { name: "Hospitality & Tourism Mgmt", url: "https://catalog.fgcu.edu/programs/htm-bs/", level: "bachelor", credential: "B.S." },
  { name: "Integrated Studies", url: "https://catalog.fgcu.edu/programs/integrated-studies-ba/", level: "bachelor", credential: "B.A." },
  { name: "Journalism", url: "https://catalog.fgcu.edu/programs/journalism-ba/", level: "bachelor", credential: "B.A." },
  { name: "Learning Design & Technology", url: "https://catalog.fgcu.edu/programs/learning-design-technology-ma/", level: "graduate", credential: "M.A." },
  { name: "Legal Studies", url: "https://catalog.fgcu.edu/programs/legal-studies-bs/", level: "bachelor", credential: "B.S." },
  { name: "Management", url: "https://catalog.fgcu.edu/programs/management-bs/", level: "bachelor", credential: "B.S." },
  { name: "Marine Science", url: "https://catalog.fgcu.edu/programs/marine-science-bs/", level: "bachelor", credential: "B.S." },
  { name: "Marketing", url: "https://catalog.fgcu.edu/programs/marketing-bs/", level: "bachelor", credential: "B.S." },
  { name: "Mathematics", url: "https://catalog.fgcu.edu/programs/mathematics-ba/", level: "bachelor", credential: "B.A." },
  { name: "Mathematics", url: "https://catalog.fgcu.edu/programs/mathematics-bs/", level: "bachelor", credential: "B.S." },
  { name: "MSN to DNP", url: "https://catalog.fgcu.edu/programs/msn-dnp-dnp/", level: "graduate", credential: "D.N.P." },
  { name: "MSN to DNP Nurse Anesthesiology", url: "https://catalog.fgcu.edu/programs/msn-dnp-nrse-anesthesiology-dnp/", level: "graduate", credential: "D.N.P." },
  { name: "Music", url: "https://catalog.fgcu.edu/programs/music-ba/", level: "bachelor", credential: "B.A." },
  { name: "Music Education", url: "https://catalog.fgcu.edu/programs/music-education-bme/", level: "bachelor", credential: "B.M.E." },
  { name: "Music Performance", url: "https://catalog.fgcu.edu/programs/music-performance-bm/", level: "bachelor", credential: "B.M." },
  { name: "Music Therapy", url: "https://catalog.fgcu.edu/programs/music-therapy-bmt/", level: "bachelor", credential: "B.M.T." },
  { name: "Nurse Educator", url: "https://catalog.fgcu.edu/programs/nurse-educator-msn/", level: "graduate", credential: "M.S.N." },
  { name: "Nursing", url: "https://catalog.fgcu.edu/programs/nursing-bsn/", level: "bachelor", credential: "B.S.N." },
  { name: "Nursing Leadership and Mgmt.", url: "https://catalog.fgcu.edu/programs/nursing-leadership-management-msn/", level: "graduate", credential: "M.S.N." },
  { name: "Occupational Therapy", url: "https://catalog.fgcu.edu/programs/occupational-therapy-ms/", level: "graduate", credential: "M.S." },
  { name: "PGA Golf Management", url: "https://catalog.fgcu.edu/programs/pga-golf-management-bs/", level: "bachelor", credential: "B.S." },
  { name: "Philosophy", url: "https://catalog.fgcu.edu/programs/philosophy-ba/", level: "bachelor", credential: "B.A." },
  { name: "Physical Therapy", url: "https://catalog.fgcu.edu/programs/physical-therapy-dpt/", level: "graduate", credential: "D.P.T." },
  { name: "Physical Therapy-Transitional", url: "https://catalog.fgcu.edu/programs/physical-therapytransitional-dpt/", level: "graduate", credential: "D.P.T." },
  { name: "Physician Assistant Studies", url: "https://catalog.fgcu.edu/programs/physician-assistant-studies-mpas/", level: "graduate", credential: "M.P.A.S." },
  { name: "Physics", url: "https://catalog.fgcu.edu/programs/physics-bs/", level: "bachelor", credential: "B.S." },
  { name: "Political Science", url: "https://catalog.fgcu.edu/programs/political-science-ba/", level: "bachelor", credential: "B.A." },
  { name: "Psychology", url: "https://catalog.fgcu.edu/programs/psychology-ba/", level: "bachelor", credential: "B.A." },
  { name: "Public Administration", url: "https://catalog.fgcu.edu/programs/public-administration-mpa/", level: "graduate", credential: "M.P.A." },
  { name: "Public Health", url: "https://catalog.fgcu.edu/programs/public-health-bsph/", level: "bachelor", credential: "B.S.P.H." },
  { name: "Quantitative Economics", url: "https://catalog.fgcu.edu/programs/quanteco-bs/", level: "bachelor", credential: "B.S." },
  { name: "Resort & Hospitality Admin", url: "https://catalog.fgcu.edu/programs/resort-hospitality-admin-bs/", level: "bachelor", credential: "B.S." },
  { name: "School Counseling", url: "https://catalog.fgcu.edu/programs/school-counseling-ma/", level: "graduate", credential: "M.A." },
  { name: "Secondary Biology Education", url: "https://catalog.fgcu.edu/programs/secondary-biology-education-ba/", level: "bachelor", credential: "B.A." },
  { name: "Secondary Mathematics Ed", url: "https://catalog.fgcu.edu/programs/secondary-mathematics-ed-ba/", level: "bachelor", credential: "B.A." },
  { name: "Secondary Social Science Ed", url: "https://catalog.fgcu.edu/programs/secondary-social-science-ed-ba/", level: "bachelor", credential: "B.A." },
  { name: "Social Work", url: "https://catalog.fgcu.edu/programs/social-work-bsw/", level: "bachelor", credential: "B.S.W." },
  { name: "Social Work", url: "https://catalog.fgcu.edu/programs/social-work-msw/", level: "graduate", credential: "M.S.W." },
  { name: "Sociology", url: "https://catalog.fgcu.edu/programs/sociology-ba/", level: "bachelor", credential: "B.A." },
  { name: "Software Engineering", url: "https://catalog.fgcu.edu/programs/software-engineering-bs/", level: "bachelor", credential: "B.S." },
  { name: "Special Education", url: "https://catalog.fgcu.edu/programs/special-education-ba/", level: "bachelor", credential: "B.A." },
  { name: "Special Education", url: "https://catalog.fgcu.edu/programs/special-education-med/", level: "graduate", credential: "M.Ed." },
  { name: "Supply Chain Management", url: "https://catalog.fgcu.edu/programs/supply-chain-management-bs/", level: "bachelor", credential: "B.S." },
  { name: "Theatre", url: "https://catalog.fgcu.edu/programs/theatre-ba/", level: "bachelor", credential: "B.A." },
];

// FGCU is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const fgcuCatalog = createProgramCatalog(FGCU_PROGRAMS, { preferred: "bachelor" });
