// FSCJ program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.fscj.edu/programs (Programs, 9 paginated pages)
// Scraped:  2026-07-25
// Programs: 162 (52 associate, 97 certificate, 13 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const FSCJ_PROGRAMS: SchoolProgram[] = [
  { name: "ASL/English Interpreting", url: "https://catalog.fscj.edu/programs/221A", level: "associate", credential: "A.S." },
  { name: "Accounting Technology", url: "https://catalog.fscj.edu/programs/2201", level: "associate", credential: "A.S." },
  { name: "Accounting Technology Management", url: "https://catalog.fscj.edu/programs/6224", level: "certificate", credential: "T.C." },
  { name: "Accounting Technology Operations", url: "https://catalog.fscj.edu/programs/6223", level: "certificate", credential: "T.C." },
  { name: "Accounting Technology Specialist", url: "https://catalog.fscj.edu/programs/6221", level: "certificate", credential: "T.C." },
  { name: "Adult Education - Academic Skills Building Mathematics", url: "https://catalog.fscj.edu/programs/8556", level: "certificate", credential: "N.C." },
  { name: "Adult Education - Academic Skills Building Reasoning Through Language Arts", url: "https://catalog.fscj.edu/programs/8561", level: "certificate", credential: "N.C." },
  { name: "Adult Education - Mathematics", url: "https://catalog.fscj.edu/programs/8555", level: "certificate", credential: "N.C." },
  { name: "Adult Education - Reasoning through Language Arts", url: "https://catalog.fscj.edu/programs/8560", level: "certificate", credential: "N.C." },
  { name: "Adult English for Speakers of Other Languages (ESOL)", url: "https://catalog.fscj.edu/programs/8500", level: "certificate", credential: "N.C." },
  { name: "Advanced Computer-Aided Technical Design", url: "https://catalog.fscj.edu/programs/6012", level: "certificate", credential: "T.C." },
  { name: "Advanced Driver Assistance Systems (ADAS) Technician", url: "https://catalog.fscj.edu/programs/6963", level: "certificate", credential: "T.C." },
  { name: "Advanced Manufacturing (Automation)", url: "https://catalog.fscj.edu/programs/6040", level: "certificate", credential: "T.C." },
  { name: "American Sign Language", url: "https://catalog.fscj.edu/programs/6521", level: "certificate", credential: "T.C." },
  { name: "Architectural Design and Construction Technology", url: "https://catalog.fscj.edu/programs/2202", level: "associate", credential: "A.S." },
  { name: "Artificial Intelligence (AI) Awareness", url: "https://catalog.fscj.edu/programs/6116", level: "certificate", credential: "T.C." },
  { name: "Artificial Intelligence (AI) Practitioner", url: "https://catalog.fscj.edu/programs/6118", level: "certificate", credential: "T.C." },
  { name: "Artificial Intelligence Systems Technology (Applied Artificial Intelligence)", url: "https://catalog.fscj.edu/programs/2159", level: "associate", credential: "A.S." },
  { name: "Associate in Arts (Baccalaureate Transfer)", url: "https://catalog.fscj.edu/programs/1108", level: "associate", credential: "A.A." },
  { name: "Automotive Collision Technology Technician", url: "https://catalog.fscj.edu/programs/5806", level: "certificate", credential: "C.C." },
  { name: "Automotive Service Management Technology", url: "https://catalog.fscj.edu/programs/A236", level: "associate", credential: "A.A.S." },
  { name: "Automotive Service Technician", url: "https://catalog.fscj.edu/programs/6236", level: "certificate", credential: "T.C." },
  { name: "Aviation Administration (Air Traffic Control)", url: "https://catalog.fscj.edu/programs/2360", level: "associate", credential: "A.S." },
  { name: "Aviation Airframe Mechanics", url: "https://catalog.fscj.edu/programs/6115", level: "certificate", credential: "T.C." },
  { name: "Aviation Maintenance Administration", url: "https://catalog.fscj.edu/programs/2365", level: "associate", credential: "A.S." },
  { name: "Aviation Maintenance Management", url: "https://catalog.fscj.edu/programs/2150", level: "associate", credential: "A.S." },
  { name: "Aviation Mechanic", url: "https://catalog.fscj.edu/programs/6119", level: "certificate", credential: "T.C." },
  { name: "Aviation Powerplant Mechanics", url: "https://catalog.fscj.edu/programs/6117", level: "certificate", credential: "T.C." },
  { name: "Banking Specialist - Financial Services (FinTech)", url: "https://catalog.fscj.edu/programs/6225", level: "certificate", credential: "T.C." },
  { name: "Barbering", url: "https://catalog.fscj.edu/programs/5622", level: "certificate", credential: "C.C." },
  { name: "Basic Recruit Training Program (BRTP) for Florida Correctional Officers (Correctional Officer)", url: "https://catalog.fscj.edu/programs/5761", level: "certificate", credential: "C.C." },
  { name: "Biomedical Equipment Technician", url: "https://catalog.fscj.edu/programs/2371", level: "associate", credential: "A.S." },
  { name: "Biomedical Sciences", url: "https://catalog.fscj.edu/programs/T300", level: "bachelor", credential: "B.S." },
  { name: "Biotechnology Laboratory Specialist (Health Science)", url: "https://catalog.fscj.edu/programs/6199", level: "certificate", credential: "T.C." },
  { name: "Biotechnology Laboratory Technology", url: "https://catalog.fscj.edu/programs/2199", level: "associate", credential: "A.S." },
  { name: "Biotechnology Specialist (Manufacturing)", url: "https://catalog.fscj.edu/programs/6198", level: "certificate", credential: "T.C." },
  { name: "Building Construction Specialist", url: "https://catalog.fscj.edu/programs/6138", level: "certificate", credential: "T.C." },
  { name: "Building Construction Technology (Construction Management)", url: "https://catalog.fscj.edu/programs/2234", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.fscj.edu/programs/2213", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.fscj.edu/programs/T200", level: "bachelor", credential: "B.S." },
  { name: "Business Analytics (Business Analysis Specialist)", url: "https://catalog.fscj.edu/programs/2325", level: "associate", credential: "A.S." },
  { name: "Business Entrepreneurship", url: "https://catalog.fscj.edu/programs/6257", level: "certificate", credential: "T.C." },
  { name: "Business Entrepreneurship Operations", url: "https://catalog.fscj.edu/programs/6139", level: "certificate", credential: "T.C." },
  { name: "Business Management", url: "https://catalog.fscj.edu/programs/6251", level: "certificate", credential: "T.C." },
  { name: "Business Operations", url: "https://catalog.fscj.edu/programs/6250", level: "certificate", credential: "T.C." },
  { name: "Business Specialist", url: "https://catalog.fscj.edu/programs/6253", level: "certificate", credential: "T.C." },
  { name: "CNC Machinist/Fabricator", url: "https://catalog.fscj.edu/programs/6041", level: "certificate", credential: "T.C." },
  { name: "Cardiovascular Technology", url: "https://catalog.fscj.edu/programs/2125", level: "associate", credential: "A.S." },
  { name: "Central Sterile Processing Technologist", url: "https://catalog.fscj.edu/programs/6367", level: "certificate", credential: "T.C." },
  { name: "Chemical Laboratory Specialist", url: "https://catalog.fscj.edu/programs/6501", level: "certificate", credential: "T.C." },
  { name: "Child Care Center Management Specialization", url: "https://catalog.fscj.edu/programs/6001", level: "certificate", credential: "T.C." },
  { name: "Clinical Research Coordinator", url: "https://catalog.fscj.edu/programs/6408", level: "certificate", credential: "T.C." },
  { name: "Clinical Research Professional", url: "https://catalog.fscj.edu/programs/2408", level: "associate", credential: "A.S." },
  { name: "Commercial Vehicle Driving", url: "https://catalog.fscj.edu/programs/5100", level: "certificate", credential: "C.C." },
  { name: "Communication and Media", url: "https://catalog.fscj.edu/programs/T400", level: "bachelor", credential: "B.S." },
  { name: "Computer Aided Technical Design", url: "https://catalog.fscj.edu/programs/6011", level: "certificate", credential: "T.C." },
  { name: "Computer Information Technology", url: "https://catalog.fscj.edu/programs/2153", level: "associate", credential: "A.S." },
  { name: "Computer Programming Specialist", url: "https://catalog.fscj.edu/programs/6956", level: "certificate", credential: "T.C." },
  { name: "Computer Systems Networking", url: "https://catalog.fscj.edu/programs/S300", level: "bachelor", credential: "B.A.S." },
  { name: "Cosmetology", url: "https://catalog.fscj.edu/programs/5743", level: "certificate", credential: "C.C." },
  { name: "Criminal Justice Technology", url: "https://catalog.fscj.edu/programs/2239", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology Specialist", url: "https://catalog.fscj.edu/programs/6420", level: "certificate", credential: "T.C." },
  { name: "Crossover From Correctional Officer to Law Enforcement Officer", url: "https://catalog.fscj.edu/programs/5798", level: "certificate", credential: "C.C." },
  { name: "Culinary Arts", url: "https://catalog.fscj.edu/programs/6051", level: "certificate", credential: "T.C." },
  { name: "Culinary Management", url: "https://catalog.fscj.edu/programs/2259", level: "associate", credential: "A.S." },
  { name: "Data Science Technician", url: "https://catalog.fscj.edu/programs/6287", level: "certificate", credential: "T.C." },
  { name: "Data Science Technology", url: "https://catalog.fscj.edu/programs/2157", level: "associate", credential: "A.S." },
  { name: "Database Development Specialist", url: "https://catalog.fscj.edu/programs/6955", level: "certificate", credential: "T.C." },
  { name: "Dental Assisting", url: "https://catalog.fscj.edu/programs/5649", level: "certificate", credential: "C.C." },
  { name: "Dental Hygiene", url: "https://catalog.fscj.edu/programs/2300", level: "associate", credential: "A.S." },
  { name: "Digital Forensics", url: "https://catalog.fscj.edu/programs/6112", level: "certificate", credential: "T.C." },
  { name: "Digital Media", url: "https://catalog.fscj.edu/programs/S500", level: "bachelor", credential: "B.A.S." },
  { name: "Digital Media/Multimedia Production", url: "https://catalog.fscj.edu/programs/6402", level: "certificate", credential: "T.C." },
  { name: "Digital Media/Multimedia Technology", url: "https://catalog.fscj.edu/programs/2152", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education", url: "https://catalog.fscj.edu/programs/2200", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education", url: "https://catalog.fscj.edu/programs/T100", level: "bachelor", credential: "B.S." },
  { name: "Electricity (Construction)", url: "https://catalog.fscj.edu/programs/5632", level: "certificate", credential: "C.C." },
  { name: "Emergency Administration and Management", url: "https://catalog.fscj.edu/programs/2404", level: "associate", credential: "A.S." },
  { name: "Emergency Administrator and Manager", url: "https://catalog.fscj.edu/programs/6405", level: "certificate", credential: "T.C." },
  { name: "Emergency Medical Services (E.M.S.)", url: "https://catalog.fscj.edu/programs/2251", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Technician", url: "https://catalog.fscj.edu/programs/6394", level: "certificate", credential: "T.C." },
  { name: "Engineering Technology (Advanced Manufacturing)", url: "https://catalog.fscj.edu/programs/2320", level: "associate", credential: "A.S." },
  { name: "Engineering Technology Support Specialist", url: "https://catalog.fscj.edu/programs/6042", level: "certificate", credential: "T.C." },
  { name: "Entrepreneurship in Interior Design", url: "https://catalog.fscj.edu/programs/4106", level: "certificate", credential: "A.T.C." },
  { name: "Environmental Science Technician", url: "https://catalog.fscj.edu/programs/6022", level: "certificate", credential: "T.C." },
  { name: "Environmental Science Technology", url: "https://catalog.fscj.edu/programs/2166", level: "associate", credential: "A.S." },
  { name: "Facials Specialty", url: "https://catalog.fscj.edu/programs/5101", level: "certificate", credential: "C.C." },
  { name: "FinTech Technician", url: "https://catalog.fscj.edu/programs/6289", level: "certificate", credential: "T.C." },
  { name: "Financial Services", url: "https://catalog.fscj.edu/programs/T210", level: "bachelor", credential: "B.S." },
  { name: "Financial Technology (FinTech)", url: "https://catalog.fscj.edu/programs/4301", level: "certificate", credential: "A.T.C." },
  { name: "Fire Officer Supervisor", url: "https://catalog.fscj.edu/programs/6455", level: "certificate", credential: "T.C." },
  { name: "Fire Science Technology", url: "https://catalog.fscj.edu/programs/2911", level: "associate", credential: "A.S." },
  { name: "Firefighter", url: "https://catalog.fscj.edu/programs/5820", level: "certificate", credential: "C.C." },
  { name: "Florida Funeral Director", url: "https://catalog.fscj.edu/programs/6154", level: "certificate", credential: "T.C." },
  { name: "Florida Law Enforcement Academy", url: "https://catalog.fscj.edu/programs/5797", level: "certificate", credential: "C.C." },
  { name: "Food and Beverage Management", url: "https://catalog.fscj.edu/programs/6050", level: "certificate", credential: "T.C." },
  { name: "Funeral Services", url: "https://catalog.fscj.edu/programs/2161", level: "associate", credential: "A.S." },
  { name: "GED® Preparation: High School Equivalency Program", url: "https://catalog.fscj.edu/programs/8515", level: "certificate", credential: "N.C." },
  { name: "GIS (Geographic Information System) Technician", url: "https://catalog.fscj.edu/programs/6203", level: "certificate", credential: "T.C." },
  { name: "Graphic Design Production", url: "https://catalog.fscj.edu/programs/6401", level: "certificate", credential: "T.C." },
  { name: "Guests Services Specialist", url: "https://catalog.fscj.edu/programs/6052", level: "certificate", credential: "T.C." },
  { name: "Hazardous Materials Specialist", url: "https://catalog.fscj.edu/programs/6021", level: "certificate", credential: "T.C." },
  { name: "Health Information Technology", url: "https://catalog.fscj.edu/programs/2277", level: "associate", credential: "A.S." },
  { name: "Health Navigator", url: "https://catalog.fscj.edu/programs/2370", level: "associate", credential: "A.S." },
  { name: "Health Navigator Specialist", url: "https://catalog.fscj.edu/programs/6370", level: "certificate", credential: "T.C." },
  { name: "Healthcare Informatics Specialist", url: "https://catalog.fscj.edu/programs/6165", level: "certificate", credential: "T.C." },
  { name: "Heating, Ventilation, Air-Conditioning/Refrigeration (HVAC/R)", url: "https://catalog.fscj.edu/programs/5604", level: "certificate", credential: "C.C." },
  { name: "Histologic Technology", url: "https://catalog.fscj.edu/programs/2262", level: "associate", credential: "A.S." },
  { name: "Home Staging Specialist", url: "https://catalog.fscj.edu/programs/6399", level: "certificate", credential: "T.C." },
  { name: "Homeland Security and Emergency Manager", url: "https://catalog.fscj.edu/programs/6404", level: "certificate", credential: "T.C." },
  { name: "Hospitality and Tourism Management", url: "https://catalog.fscj.edu/programs/2214", level: "associate", credential: "A.S." },
  { name: "Human Services", url: "https://catalog.fscj.edu/programs/T500", level: "bachelor", credential: "B.S." },
  { name: "I.T. Security", url: "https://catalog.fscj.edu/programs/2158", level: "associate", credential: "A.S." },
  { name: "IP Communications", url: "https://catalog.fscj.edu/programs/6114", level: "certificate", credential: "T.C." },
  { name: "Industry Operations Management (Industrial Management Technology)", url: "https://catalog.fscj.edu/programs/2378", level: "associate", credential: "A.S." },
  { name: "Information Systems Technology", url: "https://catalog.fscj.edu/programs/S301", level: "bachelor", credential: "B.A.S." },
  { name: "Information Technology Analysis", url: "https://catalog.fscj.edu/programs/6281", level: "certificate", credential: "T.C." },
  { name: "Information Technology Support Specialist", url: "https://catalog.fscj.edu/programs/6280", level: "certificate", credential: "T.C." },
  { name: "Interior Design Technology", url: "https://catalog.fscj.edu/programs/2389", level: "associate", credential: "A.S." },
  { name: "Legal Studies (Paralegal Studies)", url: "https://catalog.fscj.edu/programs/2299", level: "associate", credential: "A.S." },
  { name: "Logistics", url: "https://catalog.fscj.edu/programs/S110", level: "bachelor", credential: "B.A.S." },
  { name: "Logistics and Transportation Specialist", url: "https://catalog.fscj.edu/programs/6127", level: "certificate", credential: "T.C." },
  { name: "Mechatronics", url: "https://catalog.fscj.edu/programs/6044", level: "certificate", credential: "T.C." },
  { name: "Medical Assisting", url: "https://catalog.fscj.edu/programs/5648", level: "certificate", credential: "C.C." },
  { name: "Medical Information Coder/Biller", url: "https://catalog.fscj.edu/programs/6155", level: "certificate", credential: "T.C." },
  { name: "Medical Laboratory Technology", url: "https://catalog.fscj.edu/programs/2220", level: "associate", credential: "A.S." },
  { name: "Network Enterprise Administration", url: "https://catalog.fscj.edu/programs/6113", level: "certificate", credential: "T.C." },
  { name: "Network Infrastructure", url: "https://catalog.fscj.edu/programs/6110", level: "certificate", credential: "T.C." },
  { name: "Network Support Technician", url: "https://catalog.fscj.edu/programs/6109", level: "certificate", credential: "T.C." },
  { name: "Network Systems Technology", url: "https://catalog.fscj.edu/programs/2156", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://catalog.fscj.edu/programs/2330", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://catalog.fscj.edu/programs/N200", level: "bachelor", credential: "B.S.N." },
  { name: "Nursing (Bridge Option for Paramedics and Licensed Practical Nurses)", url: "https://catalog.fscj.edu/programs/2335", level: "associate", credential: "A.S." },
  { name: "Occupational Therapy Assistant", url: "https://catalog.fscj.edu/programs/2355", level: "associate", credential: "A.S." },
  { name: "Office Administration", url: "https://catalog.fscj.edu/programs/2265", level: "associate", credential: "A.S." },
  { name: "Office Management", url: "https://catalog.fscj.edu/programs/6359", level: "certificate", credential: "T.C." },
  { name: "Office Specialist", url: "https://catalog.fscj.edu/programs/6101", level: "certificate", credential: "T.C." },
  { name: "Office Support", url: "https://catalog.fscj.edu/programs/6100", level: "certificate", credential: "T.C." },
  { name: "Paralegal Studies", url: "https://catalog.fscj.edu/programs/4104", level: "certificate", credential: "A.T.C." },
  { name: "Paramedic", url: "https://catalog.fscj.edu/programs/B393", level: "certificate", credential: "A.T.D." },
  { name: "Paramedic", url: "https://catalog.fscj.edu/programs/6393", level: "certificate", credential: "T.C." },
  { name: "Pharmacy Technician", url: "https://catalog.fscj.edu/programs/5771", level: "certificate", credential: "C.C." },
  { name: "Physical Therapist Assistant", url: "https://catalog.fscj.edu/programs/222A", level: "associate", credential: "A.S." },
  { name: "Pneumatics, Hydraulics and Motors for Manufacturing", url: "https://catalog.fscj.edu/programs/6043", level: "certificate", credential: "T.C." },
  { name: "Practical Nursing", url: "https://catalog.fscj.edu/programs/5657", level: "certificate", credential: "C.C." },
  { name: "Professional Pilot Technology", url: "https://catalog.fscj.edu/programs/2258", level: "associate", credential: "A.S." },
  { name: "Public Safety Management", url: "https://catalog.fscj.edu/programs/S400", level: "bachelor", credential: "B.A.S." },
  { name: "Radiation Therapy", url: "https://catalog.fscj.edu/programs/2163", level: "associate", credential: "A.S." },
  { name: "Radiation Therapy Specialist", url: "https://catalog.fscj.edu/programs/4105", level: "certificate", credential: "A.T.C." },
  { name: "Radiography (Degree Completion)", url: "https://catalog.fscj.edu/programs/2254", level: "associate", credential: "A.S." },
  { name: "Radiography (Florida State College at Jacksonville Option)", url: "https://catalog.fscj.edu/programs/2154", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.fscj.edu/programs/2244", level: "associate", credential: "A.S." },
  { name: "Scientific Workplace Preparation", url: "https://catalog.fscj.edu/programs/6502", level: "certificate", credential: "T.C." },
  { name: "Stage Technology", url: "https://catalog.fscj.edu/programs/6210", level: "certificate", credential: "T.C." },
  { name: "Supervision and Management", url: "https://catalog.fscj.edu/programs/S100", level: "bachelor", credential: "B.A.S." },
  { name: "Supply Chain Management", url: "https://catalog.fscj.edu/programs/2127", level: "associate", credential: "A.S." },
  { name: "Surgical Services", url: "https://catalog.fscj.edu/programs/2167", level: "associate", credential: "A.S." },
  { name: "Theatre and Entertainment Technology (Entertainment Technology)", url: "https://catalog.fscj.edu/programs/221B", level: "associate", credential: "A.S." },
  { name: "VERTICAL Career Readiness I (Specialized Career Education Basic)", url: "https://catalog.fscj.edu/programs/5290", level: "certificate", credential: "C.C." },
  { name: "VERTICAL Career Readiness II (Specialized Career Education – Comprehensive)", url: "https://catalog.fscj.edu/programs/5291", level: "certificate", credential: "C.C." },
  { name: "Web Development Specialist", url: "https://catalog.fscj.edu/programs/6954", level: "certificate", credential: "T.C." },
  { name: "Welding Technology", url: "https://catalog.fscj.edu/programs/5789", level: "certificate", credential: "C.C." },
];
