// FSU degree catalog: program name -> the one page that actually lists it.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:fsu
//
// Source (undergraduate): https://academic-guide.fsu.edu/all-programs
// Source (graduate):      https://gradschool.fsu.edu/academics-research/degree-programs/masters-degree-programs
//                          https://gradschool.fsu.edu/Academics-Research/Degree-Programs/Doctoral-Degree-Programs
//                          https://gradschool.fsu.edu/Academics-Research/Degree-Programs/Specialist-Degree-Programs
// Scraped:    2026-07-27
// Programs:   304 (167 bachelor, 137 graduate)
//
// Every entry links to https://admissions.fsu.edu/majors rather than a
// per-program page. FSU's real per-program (and per-college) links live in a
// Power BI dashboard on that page that this scraper cannot extract — see the
// header comment above and HANDOFF.md §13 for why. One shared, always-correct
// link beats a guessed or fabricated per-program URL.
//
// Credentials are spelled out ("Bachelor's"/"Master's"/"Doctoral"/
// "Specialist") rather than abbreviated, since the source pages don't state
// a clean per-program abbreviation for most entries — same call NCF's
// scraper made for its two unlabeled graduate programs.
//
// FSU is a four-year university (like FIU/UCF/UF/FGCU/UWF/NCF/UNF/FlPoly/
// USF/FAU/FAMU), so pathways start at the bachelor's rather than an
// associate degree.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const FSU_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Actuarial Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Advertising (Communication)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "African American Studies", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Ancient History", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Anthropology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Applied Mathematics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Art History", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Art, Studio BA", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Art, Studio BFA", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Athletic Training", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Biochemistry", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Biological Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Biomathematics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Blindness and Low Vision", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Business Administration", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Chemical Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Chemistry", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Civics and Liberty Studies (Conscience Liberty)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Civics and Liberty Studies (Constitutional Liberty)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Civics and Liberty Studies (Economic Liberty)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Civics and Liberty Studies (Educational Liberty)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Classical Archaeology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Classical Civilization", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Classics and Religion", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Communication (Digital Media Production)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Communication (Media and Communication Studies)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Communication (Professional Communication)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Communication Science & Disorders (Audiology & Speech Pathology)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computational Biology (Biology)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computational Biology (Computer Science)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computational Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computer Programming and Applications BA", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computer Science, BA", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Computer Science, BS", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Crime Scene Investigation : Public Safety and Security", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Criminology - Criminal Justice", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Cyber Criminology (Computer Science)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Cyber Criminology (Criminology)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Dance", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Design and Visual Communication", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Dietetics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Economics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Elementary Education", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Elementary Education PC", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Emergency Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Biomedical)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Chemical)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Civil)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Computer)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Electrical)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Industrial)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Engineering (Mechanical)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "English (Creative Writing)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "English (Editing, Writing, & Media)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "English (Literature, Media, and Culture)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "English Education", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Entrepreneurship (Commercial)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Entrepreneurship (STEM)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Environment and Society", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Environmental Chemistry", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Environmental Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Environmental Science & Policy", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Event Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Exercise Physiology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Exploratory", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Fashion, Merchandising, and Product Development", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Finance", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Financial Planning", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Geography", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Geology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Global Club Management and Leadership", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Greek", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Greek and Latin", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "History", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Hospitality and Tourism Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Human Development and Family Sciences", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Human Resource Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Human Rights and Social Justice", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Humanities", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Information Technology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Information, Communication & Technology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Intelligence Studies", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Interdisciplinary Medical Sciences: Clinical Professions", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Interdisciplinary Medical Sciences: Community Patient Care", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Interdisciplinary Medical Sciences: Health Management, Policy and Information", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Interdisciplinary Social Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Interior Design", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Asian Studies with Emphasis in Business)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Asian Studies)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Broad Curriculum)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Latin American and Caribbean Studies with Emphasis in Business)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Latin American and Caribbean Studies)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "International Affairs (Russian and East European Studies)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Latin", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Law Enforcement Intelligence : Public Safety and Security", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Law Enforcement Operations : Public Safety and Security", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Linguistics (General Linguistics, Linguistics & Languages)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Management (General)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Management Information Systems", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Marketing", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Materials Chemistry", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Mathematics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Meteorology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Middle Eastern Studies", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Chinese)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Dual Languages)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (French)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (German)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Italian)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Japanese)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Russian)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (Spanish)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Modern Languages, Literatures, and Cultures (World Literature & Cultural Studies)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Motion Picture Arts (Animation & Digital Arts)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Motion Picture Arts (Production)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (Business)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (Commercial)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (Community)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (General)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (Jazz)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music (Sacred)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Composition", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Education (Choral)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Education (General)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Education (Instrumental)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Guitar)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Harp)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Jazz)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Organ)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Piano)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (String)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Voice)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Performance (Woodwind, Brass, Percussion)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Theatre (College of Music)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Theatre (School of Theatre)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Theory", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Music Therapy", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Neuroscience: Behavioral Neuroscience", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Neuroscience: Cell and Molecular Neuroscience", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Nursing", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Nutrition and Food Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Philosophy", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Physical Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Physics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Physics & Astrophysics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Political Science", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Professional Communication", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Professional Sales", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Psychology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Public Health", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Public Relations (Communication)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Real Estate", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Recreation and Tourism Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Religion", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Religion & Classics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Risk Management and Insurance", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Social Science Education", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Social Work", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Sociology", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Special Education Teaching", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Sport Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Stage Management", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Statistics", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Theatre, BA", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Theatre, BFA (Acting)", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Women’s  Studies", url: "https://admissions.fsu.edu/majors", level: "bachelor", credential: "Bachelor's" },
  { name: "Accounting (MAcc)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Anthropology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Anthropology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Art Education", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Art Education", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Art Education", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Specialist" },
  { name: "Art History", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Art History", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Asian Studies", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Athletic Coaching", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Biological Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Biological Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Biomedical Sciences", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Business", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Business Administration (MBA- Full-Time)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Business Administration (MBA- Online- Part Time)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Business Administration (MBA-Part-Time)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Business Analytics (MS-BA)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Chemical and Biomedical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Chemical and Biomedical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Chemistry", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Chemistry", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Civil Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Civil Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Classics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Classics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Communication", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Communication", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Communication Science and Disorders", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Communication Science and Disorders", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Computational Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Computational Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Computer Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Computer Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Corporate and Public Communication", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Counseling and Human Systems", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Specialist" },
  { name: "Counseling Psychology and School Psychology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Criminology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Criminology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Curriculum and Instruction", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Curriculum and Instruction", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Curriculum and Instruction", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Specialist" },
  { name: "Curriculum and Instruction (Online)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Dance", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Data Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Demography", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Earth, Ocean, and Atmospheric Sciences", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Earth, Ocean, and Atmospheric Sciences", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Economics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Economics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Educational Leadership and Policy Studies", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Educational Leadership and Policy Studies", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Educational Leadership and Policy Studies", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Specialist" },
  { name: "Educational Leadership and Policy Studies (Online)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Educational Leadership and Policy Studies (Online)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Educational Psychology and Learning Systems", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Educational Psychology and Learning Systems", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Electrical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Electrical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "English", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "English", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Entrepreneurship", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Exercise Physiology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Exercise Physiology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Finance (MSF)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Genetic Counseling", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Geography", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Geography", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Geophysical Fluid Dynamics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "History", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "History", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Human Development and Family Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Human Development and Family Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Industrial Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Industrial Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Information", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Information", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Information", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Specialist" },
  { name: "Interior Architecture and Design", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "International Affairs", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Juris Doctor", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Juris Master", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Law Enforcement Intelligence", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "LL.M.", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Management Information Systems (MS-MIS)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Materials Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Materials Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Mathematics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Mathematics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Mechanical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Mechanical Engineering", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Medicine", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Medicine (M.D.)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Modern Languages and Linguistics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Modern Languages and Linguistics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Molecular Biophysics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Motion Picture Arts", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Music", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Music", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Neuroscience", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Nurse Anesthesia", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Nursing", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Nursing", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Nutrition and Food Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Nutrition and Food Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Organizational Management & Communication", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Philosophy", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Philosophy", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Physician Assistant", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Physics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Physics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Political Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Political Science", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Psychology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Psychology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Public Administration", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Public Administration", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Public Health", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Religion", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Religion", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Risk Management and Insurance (MS-RMI)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Russian and Eastern European Studies", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Social Work", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Social Work (MSW)", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Sociology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Sociology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Sport Management", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Sport Management", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Sport Psychology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Sport Psychology", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Statistics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Statistics", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Studio Art", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Theatre", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Theatre", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
  { name: "Urban and Regional Planning", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Master's" },
  { name: "Urban and Regional Planning", url: "https://admissions.fsu.edu/majors", level: "graduate", credential: "Doctoral" },
];

// FSU is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const fsuCatalog = createProgramCatalog(FSU_PROGRAMS, { preferred: "bachelor" });
