// HCC program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://www.hcfl.edu/browse-all-degrees-certificates
// Scraped:  2026-07-26
// Programs: 205 (107 associate, 97 certificate, 1 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.
// Credential extracted from trailing marker in each program's anchor text (AA Pathway/AS/ATC/ATD/CCC/PSAV); 2 entries required visiting the program page directly to confirm credential.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const HCC_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Accounting Technology Financial Option", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-technology-financial-option", level: "associate", credential: "A.S." },
  { name: "Accounting Technology Management", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-technology-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Operations", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-technology-operations-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Specialist", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-technology-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Tax Option", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/accounting-technology-tax-option", level: "associate", credential: "A.S." },
  { name: "Advanced Network Infrastructure", url: "https://www.hcfl.edu/academics/subjects/information-technology/advanced-network-infrastructure-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Agriculture", url: "https://www.hcfl.edu/academics/subjects/environment/agriculture-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Anthropology", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/anthropology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Aquaculture", url: "https://www.hcfl.edu/academics/subjects/environment/aquaculture", level: "associate", credential: "A.S." },
  { name: "Aquaculture Technology", url: "https://www.hcfl.edu/academics/subjects/environment/aquaculture-technology-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Architectural Design and Construction Technology", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/architectural-design-and-construction-technology", level: "associate", credential: "A.S." },
  { name: "Architecture", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/architecture-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Art", url: "https://www.hcfl.edu/academics/subjects/visual-arts-and-design/art-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Artificial Intelligence", url: "https://www.hcfl.edu/academics/subjects/information-technology/artificial-intelligence", level: "associate", credential: "A.S." },
  { name: "AutoCAD Foundations", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/autocad-foundations-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Automation", url: "https://www.hcfl.edu/academics/subjects/engineering/automation-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Automotive Collision Technology Technician", url: "https://www.hcfl.edu/academics/subjects/transportation/automotive-collision-technology-technician-psav", level: "certificate", credential: "PSAV" },
  { name: "Automotive Service Technology", url: "https://www.hcfl.edu/academics/subjects/transportation/automotive-service-technology-psav", level: "certificate", credential: "PSAV" },
  { name: "Auxiliary Law Enforcement Officer", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/auxiliary-law-enforcement-officer-psav", level: "certificate", credential: "PSAV" },
  { name: "Bail Bonding/Surety Agent", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/bail-bondingsurety-agent-psav", level: "certificate", credential: "PSAV" },
  { name: "Biological Sciences", url: "https://www.hcfl.edu/academics/subjects/math-and-science/biological-sciences-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Biotechnology Laboratory Specialist", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/biotechnology-laboratory-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Biotechnology Laboratory Technology", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/biotechnology-laboratory-technology", level: "associate", credential: "A.S." },
  { name: "Broadcast Production", url: "https://www.hcfl.edu/academics/subjects/communications/broadcast-production-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Building Construction", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/building-construction-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Business Administration", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-administration-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Business Administration and Management", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-administration-and-management", level: "associate", credential: "A.S." },
  { name: "Business Administration International Business", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-administration-international-business", level: "associate", credential: "A.S." },
  { name: "Business Intelligence Professional", url: "https://www.hcfl.edu/academics/subjects/information-technology/business-intelligence-professional-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Business Intelligence Specialist", url: "https://www.hcfl.edu/academics/subjects/information-technology/business-intelligence-specialist", level: "associate", credential: "A.S." },
  { name: "Business Management", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Business Operations", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-operations-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Business Specialist", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/business-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Cardiac Catheterization", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/cardiac-catheterization", level: "associate", credential: "A.S." },
  { name: "Chef's Apprentice", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/chefs-apprentice-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Clinical Research Coordinator", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/clinical-research-coordinator-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Clinical Research Professional", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/clinical-research-professional", level: "associate", credential: "A.S." },
  { name: "CNC Machinist", url: "https://www.hcfl.edu/academics/subjects/engineering/cnc-machinist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Communication", url: "https://www.hcfl.edu/academics/subjects/communications/communication-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Computed Tomography (CT)", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/computed-tomography-ct-atc", level: "certificate", credential: "A.T.C." },
  { name: "Computer Engineering Technology", url: "https://www.hcfl.edu/academics/subjects/engineering/computer-engineering-technology", level: "associate", credential: "A.S." },
  { name: "Computer Information Systems", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-information-systems-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Computer Information Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-information-technology", level: "associate", credential: "A.S." },
  { name: "Computer Programmer", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-programmer-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming and Analysis", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-programming-and-analysis", level: "associate", credential: "A.S." },
  { name: "Computer Programming Specialist", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-programming-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Computer Science Engineering", url: "https://www.hcfl.edu/academics/subjects/information-technology/computer-science-engineering-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Correctional Officer", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/correctional-officer-psav", level: "certificate", credential: "PSAV" },
  { name: "Counseling and Human Services", url: "https://www.hcfl.edu/academics/subjects/counseling-and-human-services/counseling-and-human-services", level: "associate", credential: "A.S." },
  { name: "Crime Scene", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/crime-scene-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Criminal Justice Technology Specialist", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/criminal-justice-technology-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Criminology", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/criminology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Criminology and Criminal Justice Studies", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/criminology-and-criminal-justice-studies", level: "associate", credential: "A.S." },
  { name: "Cross-Over Correctional Officer to Law Enforcement Officer", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/cross-over-correctional-officer-law-enforcement-officer-psav", level: "certificate", credential: "PSAV" },
  { name: "Culinary and Dietetic Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/culinary-and-dietetic-management", level: "associate", credential: "A.S." },
  { name: "Culinary Arts", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/culinary-arts-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Culinary Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/culinary-management", level: "associate", credential: "A.S." },
  { name: "Cybersecurity", url: "https://www.hcfl.edu/academics/subjects/information-technology/cybersecurity-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Cybersecurity", url: "https://www.hcfl.edu/academics/subjects/information-technology/cybersecurity", level: "associate", credential: "A.S." },
  { name: "Cybersecurity Operations", url: "https://www.hcfl.edu/academics/subjects/information-technology/cybersecurity-operations", level: "associate", credential: "A.S." },
  { name: "Dance", url: "https://www.hcfl.edu/academics/subjects/performing-arts/dance-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Database Administrator", url: "https://www.hcfl.edu/academics/subjects/information-technology/database-administrator-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Database Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/database-technology", level: "associate", credential: "A.S." },
  { name: "Dental", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/dental-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Dental Assisting", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/dental-assisting-atd", level: "certificate", credential: "A.T.D." },
  { name: "Dental Hygiene", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/dental-hygiene", level: "associate", credential: "A.S." },
  { name: "Diagnostic Medical Sonography", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/diagnostic-medical-sonography", level: "associate", credential: "A.S." },
  { name: "Diesel Systems Technician", url: "https://www.hcfl.edu/academics/subjects/diesel-systems-technician-psav", level: "certificate", credential: "PSAV" },
  { name: "Digital Forensics", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-forensics-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Multimedia Developer", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-media-multimedia-developer", level: "associate", credential: "A.S." },
  { name: "Digital Media Multimedia Game Design", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-media-multimedia-game-design", level: "associate", credential: "A.S." },
  { name: "Digital Media Multimedia Instructional Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-media-multimedia-instructional-technology-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Multimedia Production", url: "https://www.hcfl.edu/academics/subjects/communications/digital-media-multimedia-production-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media/Multimedia Video Production", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-mediamultimedia-video-production-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media/Multimedia Web Production", url: "https://www.hcfl.edu/academics/subjects/information-technology/digital-mediamultimedia-web-production-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Drafting", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/drafting-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Education Administrator", url: "https://www.hcfl.edu/academics/subjects/education/early-childhood-education-administrator-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Education - Administrator Option", url: "https://www.hcfl.edu/academics/subjects/education/early-childhood-education-administrator-option", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education - Preschool Option", url: "https://www.hcfl.edu/academics/subjects/education/early-childhood-education-preschool-option", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education Preschool", url: "https://www.hcfl.edu/academics/subjects/education/early-childhood-education-preschool-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Echocardiography", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/echocardiography", level: "associate", credential: "A.S." },
  { name: "Education Teacher Preparation", url: "https://www.hcfl.edu/academics/subjects/education/education-teacher-preparation-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Electronics Engineering Technology", url: "https://www.hcfl.edu/academics/subjects/engineering/electronics-engineering-technology", level: "associate", credential: "A.S." },
  { name: "Electronics Technician", url: "https://www.hcfl.edu/academics/subjects/engineering/electronics-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Emergency Medical Services", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/emergency-medical-services", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Technician", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/emergency-medical-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Engineering", url: "https://www.hcfl.edu/academics/subjects/engineering/engineering-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Engineering Technology", url: "https://www.hcfl.edu/academics/subjects/engineering/engineering-technology", level: "associate", credential: "A.S." },
  { name: "Engineering Technology Support Specialist", url: "https://www.hcfl.edu/academics/subjects/engineering/engineering-technology-support-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Enterprise Cloud Computing", url: "https://www.hcfl.edu/academics/subjects/information-technology/enterprise-cloud-computing", level: "associate", credential: "A.S." },
  { name: "Entrepreneurship", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/entrepreneurship-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Entrepreneurship and Innovation", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/entrepreneurship-and-innovation-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Entrepreneurship Strategies", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/entrepreneurship-strategies-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Entrepreneurship Ventures", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/entrepreneurship-ventures-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Environmental Science Technology", url: "https://www.hcfl.edu/academics/subjects/environment/environmental-science-technology", level: "associate", credential: "A.S." },
  { name: "Event Planning Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/event-planning-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Exercise Science", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/exercise-science-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Finance", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/finance-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Financial Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/financial-technology", level: "associate", credential: "A.S." },
  { name: "Financial Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/financial-technology-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Fire Officer Supervisor", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/fire-officer-supervisor-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Fire Science Technology", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/fire-science-technology", level: "associate", credential: "A.S." },
  { name: "Food and Beverage Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/food-and-beverage-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Food and Beverage Operations", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/food-and-beverage-operations-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Foreign Language", url: "https://www.hcfl.edu/academics/subjects/humanities/foreign-language-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Game Design and Development", url: "https://www.hcfl.edu/academics/subjects/information-technology/game-design-and-development-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Geology", url: "https://www.hcfl.edu/academics/subjects/environment/geology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Graphic Design", url: "https://www.hcfl.edu/academics/subjects/visual-arts-and-design/graphic-design-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Graphic Design Production", url: "https://www.hcfl.edu/academics/subjects/visual-arts-and-design/graphic-design-production-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Health Navigator", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/health-navigator", level: "associate", credential: "A.S." },
  { name: "Health Navigator Specialist", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/health-navigator-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Healthcare Support Specialist", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/healthcare-support-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Heavy Equipment Service Technician", url: "https://www.hcfl.edu/academics/subjects/transportation/heavy-equipment-service-technician-psav", level: "certificate", credential: "PSAV" },
  { name: "Help Desk Support Technician", url: "https://www.hcfl.edu/academics/subjects/information-technology/help-desk-support-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "History", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/history-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Home Staging Specialist", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/home-staging-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Homeland Security Specialist", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/homeland-security-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality Administration Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/hospitality-administration-management-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Hospitality and Tourism Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/hospitality-and-tourism-management", level: "associate", credential: "A.S." },
  { name: "Human Resource Assistant", url: "https://www.hcfl.edu/academics/subjects/office-administration/human-resource-assistant-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Humanities", url: "https://www.hcfl.edu/academics/subjects/humanities/humanities-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Industrial Management Technology", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/industrial-management-technology", level: "associate", credential: "A.S." },
  { name: "Information Technology", url: "https://www.hcfl.edu/academics/subjects/information-technology/information-technology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Interdisciplinary Entrepreneurship", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/interdisciplinary-entrepreneurship", level: "associate", credential: "A.S." },
  { name: "Internet Services Technology Web Designer", url: "https://www.hcfl.edu/academics/subjects/information-technology/internet-services-technology-web-designer", level: "associate", credential: "A.S." },
  { name: "Internet Services Technology Web Developer", url: "https://www.hcfl.edu/academics/subjects/information-technology/internet-services-technology-web-developer", level: "associate", credential: "A.S." },
  { name: "Internet Services Technology: Web Designer", url: "https://www.hcfl.edu/academics/subjects/information-technology/internet-services-technology-web-designer-ccc", level: "certificate", credential: "C.C.C." },
  { name: "IT Project Management", url: "https://www.hcfl.edu/academics/subjects/information-technology/it-project-management", level: "associate", credential: "A.S." },
  { name: "Laser and Photonics", url: "https://www.hcfl.edu/academics/subjects/engineering/laser-and-photonics-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Law Enforcement Officer", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/law-enforcement-officer-psav", level: "certificate", credential: "PSAV" },
  { name: "Lean Manufacturing", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/lean-manufacturing-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Liberal Arts and Sciences", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/liberal-arts-and-sciences-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Logistics and Transportation Specialist", url: "https://www.hcfl.edu/academics/subjects/transportation/logistics-and-transportation-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Magnetic Resonance Imaging (MRI)", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/magnetic-resonance-imaging-mri-atc", level: "certificate", credential: "A.T.C." },
  { name: "Marketing", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/marketing-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Mass Communications", url: "https://www.hcfl.edu/academics/subjects/communications/mass-communications-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Math Education Teacher Preparation", url: "https://www.hcfl.edu/academics/subjects/education/math-education-teacher-preparation-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Mathematics", url: "https://www.hcfl.edu/academics/subjects/math-and-science/mathematics-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Mechatronics", url: "https://www.hcfl.edu/academics/subjects/engineering/mechatronics-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Medical Information: Medical Coder", url: "https://www.hcfl.edu/academics/subjects/office-administration/medical-information-medical-coder-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Medical Laboratory Science", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/medical-laboratory-science", level: "associate", credential: "A.S." },
  { name: "Medical Laboratory Science", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/medical-laboratory-science-atc", level: "certificate", credential: "A.T.C." },
  { name: "Medical Office Administration - Billing Option", url: "https://www.hcfl.edu/academics/subjects/office-administration/medical-office-administration-billing-option", level: "associate", credential: "A.S." },
  { name: "Medical Office Administration - Management Option", url: "https://www.hcfl.edu/academics/subjects/office-administration/medical-office-administration-management-option", level: "associate", credential: "A.S." },
  { name: "Medical Office Management - Billing", url: "https://www.hcfl.edu/academics/subjects/office-administration/medical-office-management-billing-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Medical Office Management - Management", url: "https://www.hcfl.edu/academics/subjects/office-administration/medical-office-management-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Medical Sciences - Dental, Medical and Veterinary", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/medical-sciences-dental-medical-and-veterinary-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Microcomputer Repairer/Installer", url: "https://www.hcfl.edu/academics/subjects/engineering/microcomputer-repairerinstaller-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Motion Picture Production Management", url: "https://www.hcfl.edu/academics/subjects/communications/motion-picture-production-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Music", url: "https://www.hcfl.edu/academics/subjects/performing-arts/music-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Network Enterprise Administration", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-enterprise-administration-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Infrastructure", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-infrastructure", level: "associate", credential: "A.S." },
  { name: "Network Infrastructure", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-infrastructure-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Security", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-security", level: "associate", credential: "A.S." },
  { name: "Network Security Cyber-Security Cisco", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-security-cyber-security-cisco-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Security Cyber-Security Linux", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-security-cyber-security-linux-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Security Cyber-Security Windows", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-security-cyber-security-windows-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Server Administration", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-server-administration-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Support Technician", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-support-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Network Systems Technology: Digital Forensics", url: "https://www.hcfl.edu/academics/subjects/information-technology/network-systems-technology-digital-forensics", level: "associate", credential: "A.S." },
  { name: "Nuclear Medicine Technology", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/nuclear-medicine-technology", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/nursing-bachelor-science", level: "bachelor", credential: "B.S." },
  { name: "Nursing", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/nursing", level: "associate", credential: "A.S." },
  { name: "Nursing - LPN Transition Option", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/nursing-lpn-transition-option", level: "associate", credential: "A.S." },
  { name: "Office Management", url: "https://www.hcfl.edu/academics/subjects/office-administration/office-management", level: "associate", credential: "A.S." },
  { name: "Office Management", url: "https://www.hcfl.edu/academics/subjects/office-administration/office-management-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Office Specialist", url: "https://www.hcfl.edu/academics/subjects/office-administration/office-specialist-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Office Support", url: "https://www.hcfl.edu/academics/subjects/office-administration/office-support-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Ophthalmic Laboratory Technician", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/ophthalmic-laboratory-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Opticianry", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/opticianry", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/paralegal-studies", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/paralegal-studies-atc", level: "certificate", credential: "A.T.C." },
  { name: "Paramedic", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/paramedic-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Pharmacy", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/pharmacy-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Philosophy", url: "https://www.hcfl.edu/academics/subjects/humanities/philosophy-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Pneumatics, Hydraulics and Motors for Manufacturing", url: "https://www.hcfl.edu/academics/subjects/engineering/pneumatics-hydraulics-and-motors-manufacturing-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Political Science", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/political-science-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Private Investigator Intern", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/private-investigator-intern-psav", level: "certificate", credential: "PSAV" },
  { name: "Project Manager Associate", url: "https://www.hcfl.edu/academics/subjects/information-technology/project-manager-associate-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Psychology", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/psychology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Public Health", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/public-health-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Radiation Therapy", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/radiation-therapy", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/radiography", level: "associate", credential: "A.S." },
  { name: "Real Estate Paralegal", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/real-estate-paralegal-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Religious Studies", url: "https://www.hcfl.edu/academics/subjects/humanities/religious-studies-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Respiratory Care", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/respiratory-care", level: "associate", credential: "A.S." },
  { name: "Respiratory Care Transition Option", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/respiratory-care-transition-option", level: "associate", credential: "A.S." },
  { name: "Restaurant Management", url: "https://www.hcfl.edu/academics/subjects/hospitality-and-culinary/restaurant-management", level: "associate", credential: "A.S." },
  { name: "Robotics and Simulation", url: "https://www.hcfl.edu/academics/subjects/engineering/robotics-and-simulation-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Sociology", url: "https://www.hcfl.edu/academics/subjects/social-and-behavioral-sciences/sociology-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Statistics", url: "https://www.hcfl.edu/academics/subjects/math-and-science/statistics-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Supply Chain Management", url: "https://www.hcfl.edu/academics/subjects/transportation/supply-chain-management-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Supply Chain Management", url: "https://www.hcfl.edu/academics/subjects/accounting-and-business/supply-chain-management", level: "associate", credential: "A.S." },
  { name: "Surgical Technology", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/surgical-technology", level: "associate", credential: "A.S." },
  { name: "Sustainable Design", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/sustainable-design-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Technology Project Manager", url: "https://www.hcfl.edu/academics/subjects/information-technology/technology-project-manager-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Theatre", url: "https://www.hcfl.edu/academics/subjects/performing-arts/theatre-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Veterinary", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/veterinary-aa-pathway", level: "associate", credential: "A.A." },
  { name: "Veterinary Technology", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/veterinary-technology", level: "associate", credential: "A.S." },
  { name: "Visual Assessment", url: "https://www.hcfl.edu/academics/subjects/health-and-medical/visual-assessment-atc", level: "certificate", credential: "A.T.C." },
  { name: "Water Quality Technician", url: "https://www.hcfl.edu/academics/subjects/environment/water-quality-technician-ccc", level: "certificate", credential: "C.C.C." },
  { name: "Welding Technology", url: "https://www.hcfl.edu/academics/subjects/architecture-and-building-trades/welding-technology-psav", level: "certificate", credential: "PSAV" },
  { name: "Cross-Over Correctional Probation Officer to Law Enforcement Officer", url: "https://www.hcfl.edu/academics/subjects/law-criminal-justice-security/cross-over-correctional-probation-officer-law-enforcement-officer", level: "certificate", credential: "C.T.C." },
  { name: "Internet Services Technology Web Development Specialist - Developer", url: "https://www.hcfl.edu/academics/subjects/information-technology/internet-services-technology-web-development-specialist-developer", level: "certificate", credential: "C.C.C." },
];
