// PHSC program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/programs-of-study
// Scraped:  2026-07-26
// Programs: 82 (25 associate, 55 certificate, 2 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.
// PHSC uses SmartCatalogIQ. 'Career Cert.' = the catalog's own PSVC (postsecondary vocational) certificate track; 'Cert.' = the catalog's TC (technical certificate) track; EPI = Educator Preparation Institute, a post-baccalaureate teaching credential.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const PHSC_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-acc", level: "associate", credential: "A.S." },
  { name: "Business Administration AS to BS Transfer Program", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-ba", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-cjj", level: "associate", credential: "A.S." },
  { name: "Computer Programming and Analysis", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-cpa", level: "associate", credential: "A.S." },
  { name: "Crime Scene/Forensic Science Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-cst", level: "associate", credential: "A.S." },
  { name: "Computer Aided Drafting and Design Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-ddt", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-dh", level: "associate", credential: "A.S." },
  { name: "Digital Media / Multimedia Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-dmt", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-ems", level: "associate", credential: "A.S." },
  { name: "Engineering Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-engt", level: "associate", credential: "A.S." },
  { name: "Financial Services", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-fins", level: "associate", credential: "A.S." },
  { name: "Industrial Management Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-imt", level: "associate", credential: "A.S." },
  { name: "Internet Services Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-isti", level: "associate", credential: "A.S." },
  { name: "Cyber and IT Security", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-its", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies (Legal Assisting)", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-la", level: "associate", credential: "A.S." },
  { name: "Marketing Management", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-mm", level: "associate", credential: "A.S." },
  { name: "Nursing (RN) Generic Program", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-ngt", level: "associate", credential: "A.S." },
  { name: "Nursing (RN) ADN Transition Program", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-nlt", level: "associate", credential: "A.S." },
  { name: "Office Administration", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-oa", level: "associate", credential: "A.S." },
  { name: "Professional Pilot Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-ppt", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-rad", level: "associate", credential: "A.S." },
  { name: "Social and Human Services", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-shs", level: "associate", credential: "A.S." },
  { name: "Surgical Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/as-sts", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Technician", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/atd/atd-emt", level: "certificate", credential: "A.T.D." },
  { name: "Aviation Maintenance Administration", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/aviation-maintenance-administration", level: "associate", credential: "A.S." },
  { name: "Basic Recruit Training Program for Florida Correctional Officers", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/basic-recruit-training-program-for-florida-correctional-officers", level: "certificate", credential: "Career Cert." },
  { name: "Supervision and Management", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/bas/bas-sm", level: "bachelor", credential: "B.A.S." },
  { name: "Nursing", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/bachelor-of-science/bs-nur", level: "bachelor", credential: "B.S.N." },
  { name: "Addiction Services", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-adsc", level: "certificate", credential: "Cert." },
  { name: "Computer-Aided Design Technical", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-af", level: "certificate", credential: "Cert." },
  { name: "Artificial Intelligence Awareness", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-aiaw", level: "certificate", credential: "Cert." },
  { name: "Automation", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-am", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology Management", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-atm", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology Operations", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-ato", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-ats", level: "certificate", credential: "Cert." },
  { name: "Business Development and Entrepreneurship", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-bde", level: "certificate", credential: "Cert." },
  { name: "Computer Programmer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-bdp", level: "certificate", credential: "Cert." },
  { name: "Business Operations", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-bo", level: "certificate", credential: "Cert." },
  { name: "Business Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-bs", level: "certificate", credential: "Cert." },
  { name: "Computer Programming Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-cps", level: "certificate", credential: "Cert." },
  { name: "Network Security", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-cs", level: "certificate", credential: "Cert." },
  { name: "Crime Scene Technician", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-cst", level: "certificate", credential: "Cert." },
  { name: "Database and E-Commerce Security", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-decs", level: "certificate", credential: "Cert." },
  { name: "Digital Media / Multimedia Authoring", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-dma", level: "certificate", credential: "Cert." },
  { name: "Digital Media / Multimedia Production", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-dmp", level: "certificate", credential: "Cert." },
  { name: "Digital Media / Multimedia Video Production", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-dmvp", level: "certificate", credential: "Cert." },
  { name: "Digital Media / Multimedia Web Production / Graphic Designer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-dmwp", level: "certificate", credential: "Cert." },
  { name: "Entrepreneurship", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-entr", level: "certificate", credential: "Cert." },
  { name: "Engineering Technology Support Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-ets", level: "certificate", credential: "Cert." },
  { name: "Internet of Things Applications", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-iot", level: "certificate", credential: "Cert." },
  { name: "Information Technology Administration", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-itad", level: "certificate", credential: "Cert." },
  { name: "Marketing Operations", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-mo", level: "certificate", credential: "Cert." },
  { name: "Network Infrastructure", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-nic", level: "certificate", credential: "Cert." },
  { name: "Network Support Technician", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-nstc", level: "certificate", credential: "Cert." },
  { name: "Office Management", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-om", level: "certificate", credential: "Cert." },
  { name: "Office Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-os", level: "certificate", credential: "Cert." },
  { name: "Office Support", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-oss", level: "certificate", credential: "Cert." },
  { name: "Paramedic", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-para", level: "certificate", credential: "Cert." },
  { name: "Pneumatics, Hydraulics and Motors for Manufacturing", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-phmm", level: "certificate", credential: "Cert." },
  { name: "Real Estate Paralegal", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-rep", level: "certificate", credential: "Cert." },
  { name: "Business Management", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-sbm", level: "certificate", credential: "Cert." },
  { name: "Crossover from Correctional Officer to Law Enforcement Officer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-ctl", level: "certificate", credential: "Career Cert." },
  { name: "Web Development Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/ccc-wds", level: "certificate", credential: "Cert." },
  { name: "Dental Assisting", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-da", level: "certificate", credential: "Career Cert." },
  { name: "Emergency Medical Technician / Firefighter-Combined", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-femt", level: "certificate", credential: "Career Cert." },
  { name: "Fire Academy", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-ff", level: "certificate", credential: "Career Cert." },
  { name: "Auxiliary Law Enforcement Officer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-lea", level: "certificate", credential: "Career Cert." },
  { name: "Florida Law Enforcement Academy", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-leb", level: "certificate", credential: "Career Cert." },
  { name: "Law Enforcement Basic Training for Special Operations Forces Recruits", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-lso", level: "certificate", credential: "Career Cert." },
  { name: "Medical Assistant", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-ma", level: "certificate", credential: "Career Cert." },
  { name: "Phlebotomy", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-phlb", level: "certificate", credential: "Career Cert." },
  { name: "Practical Nursing", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-pn", level: "certificate", credential: "Career Cert." },
  { name: "Welding Technology", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-wdt", level: "certificate", credential: "Career Cert." },
  { name: "Welding Technology-Advanced", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/cc-wta", level: "certificate", credential: "Career Cert." },
  { name: "Correctional Officer Basic Training Program for Special Operations Forces", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/correctional-officer-basic-training-program-for-special-operations-forces", level: "certificate", credential: "Career Cert." },
  { name: "Crossover Training Program for Florida Correctional Probation Officer to Correctional Officer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/crossover-training-program-for-florida-correctional-probation-officer-to-correctional-officer", level: "certificate", credential: "Career Cert." },
  { name: "Crossover Training Program for Florida Correctional Probation Officer to Law Enforcement Officer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/crossover-training-program-for-florida-correctional-probation-officer-to-law-enforcement-officer", level: "certificate", credential: "Career Cert." },
  { name: "Crossover Training Program for Florida Law Enforcement Officer to Correctional Officer", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/psvc/crossover-training-program-for-florida-law-enforcement-officer-to-correctional-officer", level: "certificate", credential: "Career Cert." },
  { name: "Educator Preparation Institute", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/institutional-credit-certificate/educator-preparation-institute-epi-certificate", level: "certificate", credential: "EPI" },
  { name: "Mechatronics", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/mechatronics-certificate", level: "certificate", credential: "Cert." },
  { name: "Healthcare Informatics Specialist", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/tc/tc-hcis", level: "certificate", credential: "Cert." },
  { name: "Unmanned Vehicles Systems Operation", url: "https://phsc.smartcatalogiq.com/en/2025-2026/catalog-and-student-handbook/prog-desc/as/unmanned-vehicle-systems-operations", level: "associate", credential: "A.S." },
];
