// POLK program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.polk.edu/content.php?catoid=55&navoid=4002 (Programs of Study)
// Scraped:  2026-07-25
// Programs: 90 (13 bachelor, 28 associate, 49 certificate)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const POLK_PROGRAMS: SchoolProgram[] = [
  { name: "Supervision and Management (Business Administration)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3757", level: "bachelor", credential: "B.A.S." },
  { name: "Supervision and Management (Business Information Technology)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3770", level: "bachelor", credential: "B.A.S." },
  { name: "Supervision and Management (Healthcare Administration)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3758", level: "bachelor", credential: "B.A.S." },
  { name: "Supervision and Management (Human Resource Management)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3812", level: "bachelor", credential: "B.A.S." },
  { name: "Supervision and Management (Public Administration)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3759", level: "bachelor", credential: "B.A.S." },
  { name: "Supervision and Management (Supply Chain Management)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3819", level: "bachelor", credential: "B.A.S." },
  { name: "Aerospace Sciences (Aerospace Administration)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3780", level: "bachelor", credential: "B.S." },
  { name: "Aerospace Sciences (Professional Pilot)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3781", level: "bachelor", credential: "B.S." },
  { name: "Criminal Justice (Crime Scene Investigations)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3814", level: "bachelor", credential: "B.S." },
  { name: "Criminal Justice", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3764", level: "bachelor", credential: "B.S." },
  { name: "Early Childhood Education", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3798", level: "bachelor", credential: "B.S." },
  { name: "Elementary Education", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3799", level: "bachelor", credential: "B.S." },
  { name: "Nursing (RN-to", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3737", level: "bachelor", credential: "B.S." },
  { name: "Liberal Arts", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3733", level: "associate", credential: "A.A." },
  { name: "Accounting Technology", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3688", level: "associate", credential: "A.S." },
  { name: "Aerospace Administration", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3779", level: "associate", credential: "A.S." },
  { name: "Aviation Maintenance Administration", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3800", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3692", level: "associate", credential: "A.S." },
  { name: "Business Operational Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3693", level: "associate", credential: "A.S." },
  { name: "Cardiovascular Technology", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3694", level: "associate", credential: "A.S." },
  { name: "Computer Systems and Business Analysis", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3705", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3711", level: "associate", credential: "A.S." },
  { name: "Diagnostic Medical Sonography", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3713", level: "associate", credential: "A.S." },
  { name: "Digital Media Technology (Graphic Design Specialization)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3776", level: "associate", credential: "A.S." },
  { name: "Digital Media Technology (Video Production Specialization)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3775", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education and Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3716", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3721", level: "associate", credential: "A.S." },
  { name: "Engineering Technology (Advanced Manufacturing Specialization)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3723", level: "associate", credential: "A.S." },
  { name: "Engineering Technology (Mechanical Design and Fabrication)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3790", level: "associate", credential: "A.S." },
  { name: "Fire Science Technology", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3727", level: "associate", credential: "A.S." },
  { name: "Hospitality and Tourism Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3827", level: "associate", credential: "A.S." },
  { name: "Network Systems Engineering Technology (Infrastructure Specialization)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3806", level: "associate", credential: "A.S." },
  { name: "Network Systems Engineering Technology (Security Specialization)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3807", level: "associate", credential: "A.S." },
  { name: "Nursing (Generic Track)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3736", level: "associate", credential: "A.S." },
  { name: "Nursing (Transition Track)", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3738", level: "associate", credential: "A.S." },
  { name: "Occupational Therapy Assistant", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3740", level: "associate", credential: "A.S." },
  { name: "Physical Therapist Assistant", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3752", level: "associate", credential: "A.S." },
  { name: "Professional Pilot Science", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3772", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3754", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3756", level: "associate", credential: "A.S." },
  { name: "Supply Chain Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3761", level: "associate", credential: "A.S." },
  { name: "Accounting Technology Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3821", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Technology Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3815", level: "certificate", credential: "C.C.C." },
  { name: "Airline Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3809", level: "certificate", credential: "C.C.C." },
  { name: "Airport Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3810", level: "certificate", credential: "C.C.C." },
  { name: "Automation Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3803", level: "certificate", credential: "C.C.C." },
  { name: "Bookkeeping Operations Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3690", level: "certificate", credential: "C.C.C." },
  { name: "Business Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3816", level: "certificate", credential: "C.C.C." },
  { name: "Business Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3817", level: "certificate", credential: "C.C.C." },
  { name: "Child Care Center Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3695", level: "certificate", credential: "C.C.C." },
  { name: "Child Development Early Intervention Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3801", level: "certificate", credential: "C.C.C." },
  { name: "Commercial Pilot Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3811", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming Specialist Database Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3831", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3820", level: "certificate", credential: "C.C.C." },
  { name: "Emergency Medical Technology Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3791", level: "certificate", credential: "C.C.C." },
  { name: "Engineering Technology Support Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3789", level: "certificate", credential: "C.C.C." },
  { name: "Entrepreneurship Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3765", level: "certificate", credential: "C.C.C." },
  { name: "Event-Planning Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3822", level: "certificate", credential: "C.C.C." },
  { name: "Food and Beverage Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3823", level: "certificate", credential: "C.C.C." },
  { name: "Food and Beverage Operations Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3824", level: "certificate", credential: "C.C.C." },
  { name: "Food and Beverage Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3825", level: "certificate", credential: "C.C.C." },
  { name: "General Business Operations Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3818", level: "certificate", credential: "C.C.C." },
  { name: "Graphic Design Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3769", level: "certificate", credential: "C.C.C." },
  { name: "Guest-Services Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3826", level: "certificate", credential: "C.C.C." },
  { name: "Logistics and Transportation Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3778", level: "certificate", credential: "C.C.C." },
  { name: "Mechatronics Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3804", level: "certificate", credential: "C.C.C." },
  { name: "Medical Coding Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3734", level: "certificate", credential: "C.C.C." },
  { name: "Network Infrastructure Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3795", level: "certificate", credential: "C.C.C." },
  { name: "Network Security Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3808", level: "certificate", credential: "C.C.C." },
  { name: "Paramedic Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3750", level: "certificate", credential: "C.C.C." },
  { name: "Pneumatics, Hydraulics, and Motors for Manufacturing Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3805", level: "certificate", credential: "C.C.C." },
  { name: "Preschool Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3753", level: "certificate", credential: "C.C.C." },
  { name: "Rooms-Division Management Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3828", level: "certificate", credential: "C.C.C." },
  { name: "Rooms-Division Operations Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3829", level: "certificate", credential: "C.C.C." },
  { name: "Rooms-Division Specialist Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3830", level: "certificate", credential: "C.C.C." },
  { name: "Software Developer Applications Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3832", level: "certificate", credential: "C.C.C." },
  { name: "Video Production Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3767", level: "certificate", credential: "C.C.C." },
  { name: "Business Information Technology", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3802", level: "certificate", credential: "A.T.C." },
  { name: "Healthcare Administration", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3792", level: "certificate", credential: "A.T.C." },
  { name: "Human Resource Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3813", level: "certificate", credential: "A.T.C." },
  { name: "Public Safety Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3793", level: "certificate", credential: "A.T.C." },
  { name: "Supply Chain Management", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3833", level: "certificate", credential: "A.T.C." },
  { name: "Correctional Officer Crossover to Florida Law Enforcement Basic Recruit Training Certificate Program", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3712", level: "certificate", credential: "V.C." },
  { name: "Correctional Probation Officer Crossover to Florida Law Enforcement Academy Training Certificate Program", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3707", level: "certificate", credential: "V.C." },
  { name: "Florida Correctional Basic Recruit Training Certificate Program", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3709", level: "certificate", credential: "V.C." },
  { name: "Florida Law Enforcement Academy Training Certificate Program", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3730", level: "certificate", credential: "V.C." },
  { name: "Florida Law Enforcement Auxiliary Academy Program Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3729", level: "certificate", credential: "V.C." },
  { name: "Law Enforcement Officer Crossover to Florida Correctional Basic Recruit Training Certificate Program", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3732", level: "certificate", credential: "V.C." },
  { name: "Corrections Equivalency of Training (EOT) Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3708", level: "certificate", credential: "C.C.C." },
  { name: "Law Enforcement Equivalency of Training Certificate", url: "https://catalog.polk.edu/preview_program.php?catoid=55&poid=3731", level: "certificate", credential: "C.C.C." },
];
