// PSC program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.pensacolastate.edu/content.php?catoid=2&navoid=54 (Programs of Study, Alphabetical Listing)
// Scraped:  2026-07-25
// Programs: 121 (84 certificate, 34 associate, 3 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const PSC_PROGRAMS: SchoolProgram[] = [
  { name: "Baking and Pastry", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=177", level: "certificate", credential: "A.T.C." },
  { name: "Critical Care Nursing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=931", level: "certificate", credential: "A.T.C." },
  { name: "Human Resources Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=175", level: "certificate", credential: "A.T.C." },
  { name: "Perioperative Nursing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=932", level: "certificate", credential: "A.T.C." },
  { name: "Project Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=176", level: "certificate", credential: "A.T.C." },
  { name: "Dental Assisting Technology and Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=1702", level: "certificate", credential: "A.T.D." },
  { name: "Emergency Medical Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=274", level: "certificate", credential: "A.T.D." },
  { name: "Pharmacy Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=275", level: "certificate", credential: "A.T.D." },
  { name: "Associate in Arts", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=187", level: "associate", credential: "A.A." },
  { name: "Accounting Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=189", level: "associate", credential: "A.S." },
  { name: "Applied Artificial Intelligence", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=675", level: "associate", credential: "A.S." },
  { name: "Architectural Design and Construction Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=193", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=195", level: "associate", credential: "A.S." },
  { name: "Computer Information Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=201", level: "associate", credential: "A.S." },
  { name: "Computer Programming and Analysis-Programming Support", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=202", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=204", level: "associate", credential: "A.S." },
  { name: "Culinary Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=207", level: "associate", credential: "A.S." },
  { name: "Cyber Forensics", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=211", level: "associate", credential: "A.S." },
  { name: "Cybersecurity", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=212", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=214", level: "associate", credential: "A.S." },
  { name: "Early Childhood Education", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=215", level: "associate", credential: "A.S." },
  { name: "Electronics Engineering Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=222", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=227", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Advanced Manufacturing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=229", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Mechanical Design and Fabrication", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=235", level: "associate", credential: "A.S." },
  { name: "Graphics Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=240", level: "associate", credential: "A.S." },
  { name: "Health Information Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=245", level: "associate", credential: "A.S." },
  { name: "Health Services Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=248", level: "associate", credential: "A.S." },
  { name: "Hospitality and Tourism Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=250", level: "associate", credential: "A.S." },
  { name: "LPN to RN Career Mobility Option", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=260", level: "associate", credential: "A.S." },
  { name: "Nursing Registered Nurse", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=259", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=261", level: "associate", credential: "A.S." },
  { name: "Pharmacy Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=263", level: "associate", credential: "A.S." },
  { name: "Photographic Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=264", level: "associate", credential: "A.S." },
  { name: "Physical Therapist Assistant", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=266", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=267", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=672", level: "associate", credential: "A.S." },
  { name: "Sonography (Diagnostic Medical Sonography)", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=268", level: "associate", credential: "A.S." },
  { name: "Sport, Fitness, and Recreation Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=269", level: "associate", credential: "A.S." },
  { name: "Surgical Services", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=270", level: "associate", credential: "A.S." },
  { name: "Veterinary Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=273", level: "associate", credential: "A.S." },
  { name: "Cybersecurity", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=171", level: "bachelor", credential: "B.A.S." },
  { name: "Nursing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=174", level: "bachelor", credential: "B.S.N." },
  { name: "Advanced Esthetics", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=276", level: "certificate", credential: "C.C." },
  { name: "Advanced Welding Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=277", level: "certificate", credential: "C.C." },
  { name: "Aviation Airframe Mechanics", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=278", level: "certificate", credential: "C.C." },
  { name: "Aviation Powerplant Mechanics", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=279", level: "certificate", credential: "C.C." },
  { name: "Barbering", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=280", level: "certificate", credential: "C.C." },
  { name: "Carpentry", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=281", level: "certificate", credential: "C.C." },
  { name: "Commercial Vehicle Driving", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=282", level: "certificate", credential: "C.C." },
  { name: "Cosmetology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=283", level: "certificate", credential: "C.C." },
  { name: "Diesel Maintenance Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=284", level: "certificate", credential: "C.C." },
  { name: "Electricity", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=286", level: "certificate", credential: "C.C." },
  { name: "Electrocardiography Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=285", level: "certificate", credential: "C.C." },
  { name: "Facials Specialty", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=287", level: "certificate", credential: "C.C." },
  { name: "Heating, Ventilation and Air Conditioning", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=288", level: "certificate", credential: "C.C." },
  { name: "Massage Therapy", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=289", level: "certificate", credential: "C.C." },
  { name: "Medical Assisting", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=290", level: "certificate", credential: "C.C." },
  { name: "Nails Specialty", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=291", level: "certificate", credential: "C.C." },
  { name: "Phlebotomy", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=292", level: "certificate", credential: "C.C." },
  { name: "Plumbing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=293", level: "certificate", credential: "C.C." },
  { name: "Practical Nursing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=294", level: "certificate", credential: "C.C." },
  { name: "Welding Technology", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=295", level: "certificate", credential: "C.C." },
  { name: "Business and Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=163", level: "bachelor", credential: "B.A.S." },
  { name: "Accounting Technology Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=190", level: "certificate", credential: "T.C." },
  { name: "Accounting Technology Operations", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=191", level: "certificate", credential: "T.C." },
  { name: "Accounting Technology Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=192", level: "certificate", credential: "T.C." },
  { name: "Artificial Intelligence Practitioner", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=933", level: "certificate", credential: "T.C." },
  { name: "Automation", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=230", level: "certificate", credential: "T.C." },
  { name: "Basic Electronics Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=223", level: "certificate", credential: "T.C." },
  { name: "Business Entrepreneurship", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=199", level: "certificate", credential: "T.C." },
  { name: "Business Entrepreneurship Operations", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=200", level: "certificate", credential: "T.C." },
  { name: "Business Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=196", level: "certificate", credential: "T.C." },
  { name: "Central Sterile Processing Technologist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=271", level: "certificate", credential: "T.C." },
  { name: "Chef's Apprentice", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=208", level: "certificate", credential: "T.C." },
  { name: "Child Care Center Management Specialization", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=216", level: "certificate", credential: "T.C." },
  { name: "CNC Composite Fabricator/Programmer", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=236", level: "certificate", credential: "T.C." },
  { name: "CNC Machinist Operator/Programmer", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=238", level: "certificate", credential: "T.C." },
  { name: "CNC Machinist/Fabricator", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=237", level: "certificate", credential: "T.C." },
  { name: "Computer Programmer", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=203", level: "certificate", credential: "T.C." },
  { name: "Crime Scene Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=671", level: "certificate", credential: "T.C." },
  { name: "Criminal Justice Technology Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=205", level: "certificate", credential: "T.C." },
  { name: "Culinary Arts", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=209", level: "certificate", credential: "T.C." },
  { name: "Culinary Arts Management Operations", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=210", level: "certificate", credential: "T.C." },
  { name: "Cybersecurity Analyst", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=213", level: "certificate", credential: "T.C." },
  { name: "Early Childhood Development Specialization", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=217", level: "certificate", credential: "T.C." },
  { name: "Early Childhood Inclusion Specialization", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=218", level: "certificate", credential: "T.C." },
  { name: "Electronics Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=224", level: "certificate", credential: "T.C." },
  { name: "Endoscopic Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=669", level: "certificate", credential: "T.C." },
  { name: "Engineering Technology Support Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=231", level: "certificate", credential: "T.C." },
  { name: "Event Planning Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=251", level: "certificate", credential: "T.C." },
  { name: "Food and Beverage Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=252", level: "certificate", credential: "T.C." },
  { name: "Food and Beverage Operations", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=253", level: "certificate", credential: "T.C." },
  { name: "Food and Beverage Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=254", level: "certificate", credential: "T.C." },
  { name: "Graphic Design Production", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=241", level: "certificate", credential: "T.C." },
  { name: "Graphic Design Support", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=242", level: "certificate", credential: "T.C." },
  { name: "Guest Services Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=255", level: "certificate", credential: "T.C." },
  { name: "Health Care Services Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=249", level: "certificate", credential: "T.C." },
  { name: "Healthcare Informatics Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=246", level: "certificate", credential: "T.C." },
  { name: "Homeland Security Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=206", level: "certificate", credential: "T.C." },
  { name: "Human Resources Administrator", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=197", level: "certificate", credential: "T.C." },
  { name: "Infant/Toddler Specialization", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=220", level: "certificate", credential: "T.C." },
  { name: "Interactive Media Production", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=243", level: "certificate", credential: "T.C." },
  { name: "Interactive Media Support", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=244", level: "certificate", credential: "T.C." },
  { name: "Laser and Photonics Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=225", level: "certificate", credential: "T.C." },
  { name: "Lean Manufacturing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=232", level: "certificate", credential: "T.C." },
  { name: "Mechanical Designer/Programmer", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=239", level: "certificate", credential: "T.C." },
  { name: "Mechatronics", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=233", level: "certificate", credential: "T.C." },
  { name: "Medical Information Coder/Biller", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=247", level: "certificate", credential: "T.C." },
  { name: "Paramedic", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=228", level: "certificate", credential: "T.C." },
  { name: "Photography", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=265", level: "certificate", credential: "T.C." },
  { name: "Pneumatics, Hydraulics, and Motors for Manufacturing", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=234", level: "certificate", credential: "T.C." },
  { name: "Preschool Specialization", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=219", level: "certificate", credential: "T.C." },
  { name: "Real Estate Paralegal", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=262", level: "certificate", credential: "T.C." },
  { name: "Robotics and Simulation Technician", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=226", level: "certificate", credential: "T.C." },
  { name: "Rooms Division Management", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=256", level: "certificate", credential: "T.C." },
  { name: "Rooms Division Operations", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=257", level: "certificate", credential: "T.C." },
  { name: "Rooms Division Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=258", level: "certificate", credential: "T.C." },
  { name: "Surgical Technology Specialist", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=272", level: "certificate", credential: "T.C." },
  { name: "Sustainable Design", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=194", level: "certificate", credential: "T.C." },
  { name: "Business Entrepreneurship", url: "https://catalog.pensacolastate.edu/preview_program.php?catoid=2&poid=198", level: "associate", credential: "A.S." },
];
