// SF program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.sfcollege.edu/content.php?catoid=28&navoid=856 (Programs of Study)
// Scraped:  2026-07-25
// Programs: 85 (39 associate, 38 certificate, 8 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const SF_PROGRAMS: SchoolProgram[] = [
  { name: "Associate in Arts", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1939", level: "associate", credential: "A.A." },
  { name: "Biomedical Equipment Technician", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1931", level: "associate", credential: "A.S." },
  { name: "Biotechnology Laboratory Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1930", level: "associate", credential: "A.S." },
  { name: "Chemical Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1932", level: "associate", credential: "A.S." },
  { name: "Phlebotomy, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1940", level: "certificate", credential: "C.C." },
  { name: "Accounting", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1993", level: "associate", credential: "A.S." },
  { name: "Applied Business Analytic", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2004", level: "associate", credential: "A.S." },
  { name: "Business Administration - Insurance and Risk Management", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1942", level: "associate", credential: "A.S." },
  { name: "Business Administration - Management", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1941", level: "associate", credential: "A.S." },
  { name: "Health Information Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1946", level: "associate", credential: "A.S." },
  { name: "Health Services Management", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1945", level: "associate", credential: "A.S." },
  { name: "Leadership for Industry", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2007", level: "associate", credential: "A.S." },
  { name: "Office Administration", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1943", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1949", level: "associate", credential: "A.S." },
  { name: "Allied Healthcare Business Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2000", level: "certificate", credential: "C.C.C." },
  { name: "Healthcare Analytics and Informatics Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1947", level: "certificate", credential: "C.C.C." },
  { name: "Medical Coding and Revenue Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2049", level: "certificate", credential: "C.C.C." },
  { name: "Mobile Gaming Entrepreneurship", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1998", level: "certificate", credential: "C.C.C." },
  { name: "Office Administration, Office Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1944", level: "certificate", credential: "C.C.C." },
  { name: "Risk Management and Insurance Operations", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2001", level: "certificate", credential: "C.C.C." },
  { name: "Automotive Service Management Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1950", level: "associate", credential: "A.A.S." },
  { name: "Construction Management Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1951", level: "associate", credential: "A.S." },
  { name: "Engineering Technology - Advanced Manufacturing (ETAM)", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2006", level: "associate", credential: "A.S." },
  { name: "Automotive Service Technology, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1953", level: "certificate", credential: "C.C." },
  { name: "Building Maintenance and Management, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1999", level: "certificate", credential: "C.C." },
  { name: "Building Maintenance Repairer Apprenticeship, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2002", level: "certificate", credential: "C.C." },
  { name: "Carpentry Apprenticeship, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1958", level: "certificate", credential: "C.C." },
  { name: "Diesel Systems Technician, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2005", level: "certificate", credential: "C.C." },
  { name: "Electrical Construction Apprenticeship, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1956", level: "certificate", credential: "C.C." },
  { name: "Heating and Air Conditioning Apprenticeship, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1955", level: "certificate", credential: "C.C." },
  { name: "Heating, Ventilation, Air-Conditioning/Refrigeration Technology, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1952", level: "certificate", credential: "C.C." },
  { name: "Plumbing Apprenticeship, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1957", level: "certificate", credential: "C.C." },
  { name: "Welding Technology Advanced, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1989", level: "certificate", credential: "C.C." },
  { name: "Welding Technology, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1954", level: "certificate", credential: "C.C." },
  { name: "Early Childhood Education", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1938", level: "associate", credential: "A.S." },
  { name: "Digital Media Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1974", level: "associate", credential: "A.S." },
  { name: "Graphic Design Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1975", level: "associate", credential: "A.S." },
  { name: "Theatre and Entertainment Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1988", level: "associate", credential: "A.S." },
  { name: "Cardiovascular Sonography", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1997", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene Bridge", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1960", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1959", level: "associate", credential: "A.S." },
  { name: "Diagnostic Medical Sonography", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1972", level: "associate", credential: "A.S." },
  { name: "Invasive Cardiovascular Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1996", level: "associate", credential: "A.S." },
  { name: "Nuclear Medicine Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1967", level: "associate", credential: "A.S." },
  { name: "Nursing Bridge", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1963", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1962", level: "associate", credential: "A.S." },
  { name: "Physical Therapist Assistant", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1966", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1968", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1970", level: "associate", credential: "A.S." },
  { name: "Surgical Services", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2003", level: "associate", credential: "A.S." },
  { name: "Computed Tomography", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1969", level: "certificate", credential: "A.T.C." },
  { name: "Polysomnography", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1971", level: "certificate", credential: "A.T.C." },
  { name: "Radiation Therapy Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=2051", level: "certificate", credential: "A.T.C." },
  { name: "Sterile Processing Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1992", level: "certificate", credential: "C.C.C." },
  { name: "Dental Assisting, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1961", level: "certificate", credential: "C.C." },
  { name: "Nursing Assistant, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1965", level: "certificate", credential: "C.C." },
  { name: "Practical Nursing, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1964", level: "certificate", credential: "C.C." },
  { name: "Computer Information Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1973", level: "associate", credential: "A.S." },
  { name: "IT Security", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1991", level: "associate", credential: "A.S." },
  { name: "Network Systems Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1976", level: "associate", credential: "A.S." },
  { name: "Programming and Analysis", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1977", level: "associate", credential: "A.S." },
  { name: "Computer Programmer", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1981", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1982", level: "certificate", credential: "C.C.C." },
  { name: "Help Desk Support Technician", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1994", level: "certificate", credential: "C.C.C." },
  { name: "Information Technology Support Specialist", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1995", level: "certificate", credential: "C.C.C." },
  { name: "Network Infrastructure", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1979", level: "certificate", credential: "C.C.C." },
  { name: "Network Security", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1980", level: "certificate", credential: "C.C.C." },
  { name: "Network Server Administration", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1978", level: "certificate", credential: "C.C.C." },
  { name: "Criminal Justice Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1987", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1926", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Technician", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1927", level: "certificate", credential: "C.C.C." },
  { name: "Paramedic", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1928", level: "certificate", credential: "C.C.C." },
  { name: "Correctional Officer, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1923", level: "certificate", credential: "C.C." },
  { name: "Crossover from Correctional Officer to Law Enforcement Officer, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1925", level: "certificate", credential: "C.C." },
  { name: "Crossover from Law Enforcement Officer to Correctional Officer, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1924", level: "certificate", credential: "C.C." },
  { name: "Law Enforcement Officer, Career Certificate", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1922", level: "certificate", credential: "C.C." },
  { name: "Zoo Animal Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1929", level: "associate", credential: "A.S." },
  { name: "Health Services Administration", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1933", level: "bachelor", credential: "B.A.S." },
  { name: "Information Systems Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1983", level: "bachelor", credential: "B.A.S." },
  { name: "Medical Laboratory Science", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1986", level: "bachelor", credential: "B.A.S." },
  { name: "Multimedia and Video Production Technology", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1935", level: "bachelor", credential: "B.A.S." },
  { name: "Organizational Management", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1984", level: "bachelor", credential: "B.A.S." },
  { name: "Accounting", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1990", level: "bachelor", credential: "B.S." },
  { name: "Early Childhood Education", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1936", level: "bachelor", credential: "B.S." },
  { name: "Nursing", url: "https://catalog.sfcollege.edu/preview_program.php?catoid=28&poid=1937", level: "bachelor", credential: "B.S." },
];
