// SSC program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://www.seminolestate.edu/catalog/programs
// Scraped:  2026-07-26
// Programs: 128 (6 bachelor, 47 certificate, 75 associate)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.
// SAAT = Specialized Associate in Arts Transfer; CPP = Certificate of Professional Preparation (post-baccalaureate); Career Cert. = the catalog's own Career Certificate credential, distinct from College Credit Certificate (C.C.C.).

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const SSC_PROGRAMS: SchoolProgram[] = [
  { name: "Engineering Technology", url: "https://www.seminolestate.edu/catalog/programs/aet-bs", level: "bachelor", credential: "B.S." },
  { name: "Construction", url: "https://www.seminolestate.edu/catalog/programs/const-bs", level: "bachelor", credential: "B.S." },
  { name: "Exceptional Student Education K-12", url: "https://www.seminolestate.edu/catalog/programs/exceped-bs", level: "bachelor", credential: "B.S." },
  { name: "Interior Design", url: "https://www.seminolestate.edu/catalog/programs/intd-bas", level: "bachelor", credential: "B.A.S." },
  { name: "Management and Organizational Leadership", url: "https://www.seminolestate.edu/catalog/programs/mgmt-bas", level: "bachelor", credential: "B.A.S." },
  { name: "Public Safety Administration", url: "https://www.seminolestate.edu/catalog/programs/psa-bs", level: "bachelor", credential: "B.S." },
  { name: "Data and Visual Analytics", url: "https://www.seminolestate.edu/catalog/programs/datavis-bc", level: "certificate", credential: "C.P.P." },
  { name: "Fire Science", url: "https://www.seminolestate.edu/catalog/programs/fire-bc", level: "certificate", credential: "C.P.P." },
  { name: "Project Management", url: "https://www.seminolestate.edu/catalog/programs/pmt-bc", level: "certificate", credential: "C.P.P." },
  { name: "Biology", url: "https://www.seminolestate.edu/catalog/programs/bio-saat", level: "associate", credential: "SAAT" },
  { name: "Electrical Engineering", url: "https://www.seminolestate.edu/catalog/programs/elec-saat", level: "associate", credential: "SAAT" },
  { name: "Accounting Technology", url: "https://www.seminolestate.edu/catalog/programs/acct-as", level: "associate", credential: "A.S." },
  { name: "Automotive Engineering Technology", url: "https://www.seminolestate.edu/catalog/programs/auto-aas", level: "associate", credential: "A.A.S." },
  { name: "STEM", url: "https://www.seminolestate.edu/catalog/programs/chemt-as", level: "associate", credential: "A.S." },
  { name: "Software Development", url: "https://www.seminolestate.edu/catalog/programs/cmppa-as", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://www.seminolestate.edu/catalog/programs/crim-as", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services (EMS)", url: "https://www.seminolestate.edu/catalog/programs/ems-as", level: "associate", credential: "A.S." },
  { name: "Engineering Technology", url: "https://www.seminolestate.edu/catalog/programs/et-as", level: "associate", credential: "A.S." },
  { name: "Digital Media", url: "https://www.seminolestate.edu/catalog/programs/grdig-as", level: "associate", credential: "A.S." },
  { name: "Health Information Technology", url: "https://www.seminolestate.edu/catalog/programs/hinfo-as", level: "associate", credential: "A.S." },
  { name: "Industrial Technology Management", url: "https://www.seminolestate.edu/catalog/programs/indmgt-as", level: "associate", credential: "A.S." },
  { name: "Information Systems Technology", url: "https://www.seminolestate.edu/catalog/programs/ist-as", level: "associate", credential: "A.S." },
  { name: "Social Media and Marketing", url: "https://www.seminolestate.edu/catalog/programs/marsoc-as", level: "associate", credential: "A.S." },
  { name: "Digital Cinema and Television Production", url: "https://www.seminolestate.edu/catalog/programs/mmtfp-as", level: "associate", credential: "A.S." },
  { name: "Physical Therapist Assistant (PTA)", url: "https://www.seminolestate.edu/catalog/programs/pta-as", level: "associate", credential: "A.S." },
  { name: "Nursing", url: "https://www.seminolestate.edu/catalog/programs/rn-as", level: "associate", credential: "A.S." },
  { name: "Agricultural Operations", url: "https://www.seminolestate.edu/catalog/programs/agr-plan", level: "associate", credential: "A.A." },
  { name: "Architecture", url: "https://www.seminolestate.edu/catalog/programs/arch-aa", level: "associate", credential: "A.A." },
  { name: "Art - BFA Emerging Media", url: "https://www.seminolestate.edu/catalog/programs/art-art", level: "associate", credential: "A.A." },
  { name: "Digital Arts & Science", url: "https://www.seminolestate.edu/catalog/programs/art-digart", level: "associate", credential: "A.A." },
  { name: "Interior Design", url: "https://www.seminolestate.edu/catalog/programs/art-intd", level: "associate", credential: "A.A." },
  { name: "Art Studio", url: "https://www.seminolestate.edu/catalog/programs/art-stud", level: "associate", credential: "A.A." },
  { name: "Visual Arts Management", url: "https://www.seminolestate.edu/catalog/programs/art-va", level: "associate", credential: "A.A." },
  { name: "Accounting", url: "https://www.seminolestate.edu/catalog/programs/bus-acc", level: "associate", credential: "A.A." },
  { name: "Event Management", url: "https://www.seminolestate.edu/catalog/programs/bus-evtm", level: "associate", credential: "A.A." },
  { name: "General Business", url: "https://www.seminolestate.edu/catalog/programs/bus-gen", level: "associate", credential: "A.A." },
  { name: "Real Estate", url: "https://www.seminolestate.edu/catalog/programs/bus-rlest", level: "associate", credential: "A.A." },
  { name: "Tourism: Event & Recr Mgmt", url: "https://www.seminolestate.edu/catalog/programs/bus-tour", level: "associate", credential: "A.A." },
  { name: "Computer Science", url: "https://www.seminolestate.edu/catalog/programs/cas-comp", level: "associate", credential: "A.A." },
  { name: "Human Communication", url: "https://www.seminolestate.edu/catalog/programs/com-humn", level: "associate", credential: "A.A." },
  { name: "Media Production & Management", url: "https://www.seminolestate.edu/catalog/programs/com-ratv", level: "associate", credential: "A.A." },
  { name: "Construction", url: "https://www.seminolestate.edu/catalog/programs/const-aa", level: "associate", credential: "A.A." },
  { name: "Economics-Liberal Arts Track", url: "https://www.seminolestate.edu/catalog/programs/eco-lib", level: "associate", credential: "A.A." },
  { name: "Chemistry Education", url: "https://www.seminolestate.edu/catalog/programs/edu-chm", level: "associate", credential: "A.A." },
  { name: "English Language Arts Educ", url: "https://www.seminolestate.edu/catalog/programs/edu-engl", level: "associate", credential: "A.A." },
  { name: "Mathematics Education", url: "https://www.seminolestate.edu/catalog/programs/edu-math", level: "associate", credential: "A.A." },
  { name: "Physical Education", url: "https://www.seminolestate.edu/catalog/programs/edu-phse", level: "associate", credential: "A.A." },
  { name: "Educational Sciences", url: "https://www.seminolestate.edu/catalog/programs/edu-scie", level: "associate", credential: "A.A." },
  { name: "Spanish Education", url: "https://www.seminolestate.edu/catalog/programs/edu-span", level: "associate", credential: "A.A." },
  { name: "Career and Technical Education", url: "https://www.seminolestate.edu/catalog/programs/edu-trdi", level: "associate", credential: "A.A." },
  { name: "Engineering Technology", url: "https://www.seminolestate.edu/catalog/programs/eng-aetbs", level: "associate", credential: "A.A." },
  { name: "Computer Engineering", url: "https://www.seminolestate.edu/catalog/programs/eng-comp", level: "associate", credential: "A.A." },
  { name: "Electrical Engineering", url: "https://www.seminolestate.edu/catalog/programs/eng-elec", level: "associate", credential: "A.A." },
  { name: "Industrial Engineering", url: "https://www.seminolestate.edu/catalog/programs/eng-ind", level: "associate", credential: "A.A." },
  { name: "Mechanical Engineering", url: "https://www.seminolestate.edu/catalog/programs/eng-mech", level: "associate", credential: "A.A." },
  { name: "English Creative Writing", url: "https://www.seminolestate.edu/catalog/programs/engcr-aa", level: "associate", credential: "A.A." },
  { name: "English Tech Communication", url: "https://www.seminolestate.edu/catalog/programs/engtc-aa", level: "associate", credential: "A.A." },
  { name: "General Studies Liberal Arts", url: "https://www.seminolestate.edu/catalog/programs/gen-librl", level: "associate", credential: "A.A." },
  { name: "History", url: "https://www.seminolestate.edu/catalog/programs/his-hist", level: "associate", credential: "A.A." },
  { name: "Health Coaching", url: "https://www.seminolestate.edu/catalog/programs/hlt-coach", level: "associate", credential: "A.A." },
  { name: "Health Education & Behavior", url: "https://www.seminolestate.edu/catalog/programs/hlt-educ", level: "associate", credential: "A.A." },
  { name: "Health Services Administration", url: "https://www.seminolestate.edu/catalog/programs/hlt-hsa", level: "associate", credential: "A.A." },
  { name: "Medical Laboratory Sciences", url: "https://www.seminolestate.edu/catalog/programs/hlt-mdtc", level: "associate", credential: "A.A." },
  { name: "Pharmacy", url: "https://www.seminolestate.edu/catalog/programs/hlt-phar", level: "associate", credential: "A.A." },
  { name: "PTA AA Pre-Major", url: "https://www.seminolestate.edu/catalog/programs/hlt-pta", level: "associate", credential: "A.A." },
  { name: "Humanities", url: "https://www.seminolestate.edu/catalog/programs/hum-hum", level: "associate", credential: "A.A." },
  { name: "Information Systems Technology", url: "https://www.seminolestate.edu/catalog/programs/ist-aa", level: "associate", credential: "A.A." },
  { name: "Legal Studies", url: "https://www.seminolestate.edu/catalog/programs/legal-aa", level: "associate", credential: "A.A." },
  { name: "Mathematics", url: "https://www.seminolestate.edu/catalog/programs/mat-math", level: "associate", credential: "A.A." },
  { name: "Management", url: "https://www.seminolestate.edu/catalog/programs/mgt-aa", level: "associate", credential: "A.A." },
  { name: "Music", url: "https://www.seminolestate.edu/catalog/programs/mus-musc", level: "associate", credential: "A.A." },
  { name: "Political Science - Pre Law", url: "https://www.seminolestate.edu/catalog/programs/pol-law", level: "associate", credential: "A.A." },
  { name: "Fire & Emergency Services", url: "https://www.seminolestate.edu/catalog/programs/pub-fire", level: "associate", credential: "A.A." },
  { name: "Biology Pre-Professional", url: "https://www.seminolestate.edu/catalog/programs/sci-bio", level: "associate", credential: "A.A." },
  { name: "Data Sciences", url: "https://www.seminolestate.edu/catalog/programs/sci-datsci", level: "associate", credential: "A.A." },
  { name: "Geology", url: "https://www.seminolestate.edu/catalog/programs/sci-geol", level: "associate", credential: "A.A." },
  { name: "Meteorology", url: "https://www.seminolestate.edu/catalog/programs/sci-met", level: "associate", credential: "A.A." },
  { name: "Physics", url: "https://www.seminolestate.edu/catalog/programs/sci-phys", level: "associate", credential: "A.A." },
  { name: "Environmental Management", url: "https://www.seminolestate.edu/catalog/programs/soc-envr", level: "associate", credential: "A.A." },
  { name: "Non-Profit Management", url: "https://www.seminolestate.edu/catalog/programs/soc-nonpm", level: "associate", credential: "A.A." },
  { name: "Public Relations", url: "https://www.seminolestate.edu/catalog/programs/soc-pr", level: "associate", credential: "A.A." },
  { name: "Social Sciences", url: "https://www.seminolestate.edu/catalog/programs/soc-ss", level: "associate", credential: "A.A." },
  { name: "Kinesiology", url: "https://www.seminolestate.edu/catalog/programs/sprt-fit", level: "associate", credential: "A.A." },
  { name: "Sustainability", url: "https://www.seminolestate.edu/catalog/programs/sustain-aa", level: "associate", credential: "A.A." },
  { name: "Accounting Operations", url: "https://www.seminolestate.edu/catalog/programs/accop-cc", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Applications", url: "https://www.seminolestate.edu/catalog/programs/actap-cc", level: "certificate", credential: "C.C.C." },
  { name: "Associate Project Management", url: "https://www.seminolestate.edu/catalog/programs/ascpm-cc", level: "certificate", credential: "C.C.C." },
  { name: "Automation", url: "https://www.seminolestate.edu/catalog/programs/automat-cc", level: "certificate", credential: "C.C.C." },
  { name: "Building Construction Technology", url: "https://www.seminolestate.edu/catalog/programs/bldcn-cc", level: "certificate", credential: "C.C.C." },
  { name: "Management", url: "https://www.seminolestate.edu/catalog/programs/bmgt-cc", level: "certificate", credential: "C.C.C." },
  { name: "Business Operations", url: "https://www.seminolestate.edu/catalog/programs/busop-cc", level: "certificate", credential: "C.C.C." },
  { name: "Computer-Aided Design Technician", url: "https://www.seminolestate.edu/catalog/programs/cadd-cc", level: "certificate", credential: "C.C.C." },
  { name: "Chef's Apprentice", url: "https://www.seminolestate.edu/catalog/programs/chefapp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Education, Preschool Specialization", url: "https://www.seminolestate.edu/catalog/programs/chldp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Software Developer", url: "https://www.seminolestate.edu/catalog/programs/compr-cc", level: "certificate", credential: "C.C.C." },
  { name: "Software Development Specialist", url: "https://www.seminolestate.edu/catalog/programs/cprsp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Graphic Design Production Artist", url: "https://www.seminolestate.edu/catalog/programs/digpr-cc", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Inclusion & Behavior Management Specialization", url: "https://www.seminolestate.edu/catalog/programs/eceinc-cc", level: "certificate", credential: "C.C.C." },
  { name: "Early Childhood Education Early Intervention Specialist", url: "https://www.seminolestate.edu/catalog/programs/einsp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Sustainability", url: "https://www.seminolestate.edu/catalog/programs/enrg-cc", level: "certificate", credential: "C.C.C." },
  { name: "Entrepreneurship", url: "https://www.seminolestate.edu/catalog/programs/entre-cc", level: "certificate", credential: "C.C.C." },
  { name: "Event Planning Management", url: "https://www.seminolestate.edu/catalog/programs/evtplmt-cc", level: "certificate", credential: "C.C.C." },
  { name: "Food and Beverage Operations", url: "https://www.seminolestate.edu/catalog/programs/fdbevop-cc", level: "certificate", credential: "C.C.C." },
  { name: "Financial Operations", url: "https://www.seminolestate.edu/catalog/programs/finop-cc", level: "certificate", credential: "C.C.C." },
  { name: "Fire Officer Supervisor", url: "https://www.seminolestate.edu/catalog/programs/frofsp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Guest Services Specialist", url: "https://www.seminolestate.edu/catalog/programs/guestsv-cc", level: "certificate", credential: "C.C.C." },
  { name: "Homeland Security Professional Certificate", url: "https://www.seminolestate.edu/catalog/programs/hlspr-cc", level: "certificate", credential: "C.C.C." },
  { name: "Instructional Design", url: "https://www.seminolestate.edu/catalog/programs/insdsgn-cc", level: "certificate", credential: "C.C.C." },
  { name: "Web Development", url: "https://www.seminolestate.edu/catalog/programs/itssp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Mechatronics", url: "https://www.seminolestate.edu/catalog/programs/mechat-cc", level: "certificate", credential: "C.C.C." },
  { name: "Social Media Development", url: "https://www.seminolestate.edu/catalog/programs/mmweb-cc", level: "certificate", credential: "C.C.C." },
  { name: "Cybersecurity", url: "https://www.seminolestate.edu/catalog/programs/ntwksec-cc", level: "certificate", credential: "C.C.C." },
  { name: "Virtualization and Cloud Computing", url: "https://www.seminolestate.edu/catalog/programs/nwkvir-cc", level: "certificate", credential: "C.C.C." },
  { name: "Office Support", url: "https://www.seminolestate.edu/catalog/programs/osp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Office Management", url: "https://www.seminolestate.edu/catalog/programs/oss-cc", level: "certificate", credential: "C.C.C." },
  { name: "Pharmacy Technician", url: "https://www.seminolestate.edu/catalog/programs/pharm-atd", level: "certificate", credential: "C.C.C." },
  { name: "Rooms Division Management", url: "https://www.seminolestate.edu/catalog/programs/rmdivmt-cc", level: "certificate", credential: "C.C.C." },
  { name: "Rooms Division Specialist", url: "https://www.seminolestate.edu/catalog/programs/rmdivsp-cc", level: "certificate", credential: "C.C.C." },
  { name: "Video Editing and Post Production", url: "https://www.seminolestate.edu/catalog/programs/tvedt-cc", level: "certificate", credential: "C.C.C." },
  { name: "IT Client Specialist", url: "https://www.seminolestate.edu/catalog/programs/wladv-cc", level: "certificate", credential: "C.C.C." },
  { name: "Heating, Ventilation, Air Conditioning/Refrigeration Technology II (HVAC/R)", url: "https://www.seminolestate.edu/catalog/programs/acrfhtt-vc", level: "certificate", credential: "Career Cert." },
  { name: "Correctional Officer Training to Florida Law Enforcement Academy", url: "https://www.seminolestate.edu/catalog/programs/cotle-vc", level: "certificate", credential: "Career Cert." },
  { name: "Traditional Correctional Basic Recruit Training Program", url: "https://www.seminolestate.edu/catalog/programs/crect-vc", level: "certificate", credential: "Career Cert." },
  { name: "Electrician Helper", url: "https://www.seminolestate.edu/catalog/programs/electri-vc", level: "certificate", credential: "Career Cert." },
  { name: "Fire Academy/EMT Combined", url: "https://www.seminolestate.edu/catalog/programs/firemt-vc", level: "certificate", credential: "Career Cert." },
  { name: "Building Trade Technologies", url: "https://www.seminolestate.edu/catalog/programs/genbld-vc", level: "certificate", credential: "Career Cert." },
  { name: "Cross-over: Law Enforcement Officer to Corrections", url: "https://www.seminolestate.edu/catalog/programs/letco-vc", level: "certificate", credential: "Career Cert." },
  { name: "Welding Technologies", url: "https://www.seminolestate.edu/catalog/programs/weldtec-vc", level: "certificate", credential: "Career Cert." },
];
