// TSC program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.tsc.fl.edu/content.php?catoid=24&navoid=3657 (Programs of Study)
// Scraped:  2026-07-25
// Programs: 95 (38 associate, 51 certificate, 6 bachelor)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const TSC_PROGRAMS: SchoolProgram[] = [
  { name: "College and University Transfer", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2662", level: "associate", credential: "A.A." },
  { name: "Veterinary Assisting", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2768", level: "certificate", credential: "C.C." },
  { name: "Landscape and Turf Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2780", level: "certificate", credential: "C.C." },
  { name: "Building Construction Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2692", level: "associate", credential: "A.S." },
  { name: "Building Construction Specialist", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2693", level: "certificate", credential: "Cert." },
  { name: "CAD Foundations", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2690", level: "certificate", credential: "Cert." },
  { name: "Construction Management Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2777", level: "associate", credential: "A.S." },
  { name: "Drafting and Design Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2688", level: "associate", credential: "A.S." },
  { name: "Electrical Apprenticeship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2754", level: "certificate", credential: "C.C." },
  { name: "Heating, Ventilation, Air-Conditioning/Refrigeration (HVAC/R) 1", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2727", level: "certificate", credential: "C.C." },
  { name: "Heating, Ventilation, Air-Conditioning/Refrigeration (HVAC/R) 2", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2760", level: "certificate", credential: "C.C." },
  { name: "Heating, Ventilation, Air Conditioning, Refrigeration (HVAC/R) Apprenticeship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2755", level: "certificate", credential: "C.C." },
  { name: "Pipefitter Apprenticeship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2756", level: "certificate", credential: "C.C." },
  { name: "Plumbing Apprenticeship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2753", level: "certificate", credential: "C.C." },
  { name: "Animation and Game Art", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2775", level: "associate", credential: "A.S." },
  { name: "Graphic and Web Design Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2691", level: "associate", credential: "A.S." },
  { name: "Graphic Design Support", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2689", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2761", level: "associate", credential: "A.S." },
  { name: "Accounting Technology Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2674", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology Operations", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2672", level: "certificate", credential: "Cert." },
  { name: "Accounting Technology Specialist", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2670", level: "certificate", credential: "Cert." },
  { name: "Auditing and Compliance Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2788", level: "bachelor", credential: "B.A.S." },
  { name: "Business Administration", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2759", level: "bachelor", credential: "B.A.S." },
  { name: "Business Administration", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2676", level: "associate", credential: "A.S." },
  { name: "Business Development and Entrepreneurship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2682", level: "certificate", credential: "Cert." },
  { name: "Management Analytics", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2789", level: "bachelor", credential: "B.A.S." },
  { name: "Medical Office Administration", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2765", level: "associate", credential: "A.S." },
  { name: "Medical Administrative Specialist", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2733", level: "certificate", credential: "C.C." },
  { name: "Entrepreneurship", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2739", level: "certificate", credential: "Cert." },
  { name: "Risk Management and Insurance Operations", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2784", level: "certificate", credential: "Cert." },
  { name: "Computer Related Crime Investigations", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2773", level: "associate", credential: "A.S." },
  { name: "Crime Scene Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2772", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2704", level: "associate", credential: "A.S." },
  { name: "Correctional Officer Basic Recruit", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2706", level: "certificate", credential: "C.C." },
  { name: "Correctional Probation Officer Basic Recruit", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2705", level: "certificate", credential: "C.C." },
  { name: "Crossover from Correctional Officer to Correctional Probation Officer", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2712", level: "certificate", credential: "C.C." },
  { name: "Crossover from Correctional Officer to Law Enforcement Officer", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2709", level: "certificate", credential: "C.C." },
  { name: "Crossover from Correctional Probation Officer to Correctional Officer", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2711", level: "certificate", credential: "C.C." },
  { name: "Crossover from Correctional Probation Officer to Law Enforcement Officer", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2708", level: "certificate", credential: "C.C." },
  { name: "Crossover from Law Enforcement Officer to Correctional Officer Career and Technical", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2710", level: "certificate", credential: "Cert." },
  { name: "Firefighter", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2661", level: "certificate", credential: "C.C." },
  { name: "Firefighter/Emergency Medical Technician -Combined", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2699", level: "certificate", credential: "C.C." },
  { name: "Law Enforcement Basic Recruit", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2707", level: "certificate", credential: "C.C." },
  { name: "Paralegal/Legal Studies", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2698", level: "associate", credential: "A.S." },
  { name: "Elementary Education", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2757", level: "bachelor", credential: "B.S." },
  { name: "Exceptional Student Education", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2758", level: "bachelor", credential: "B.S." },
  { name: "Early Childhood Development, Education and Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2697", level: "associate", credential: "A.S." },
  { name: "Child Development Early Intervention", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2748", level: "certificate", credential: "Cert." },
  { name: "Infant and Toddler", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2749", level: "certificate", credential: "Cert." },
  { name: "Preschool Specialization", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2750", level: "certificate", credential: "Cert." },
  { name: "Sports, Fitness and Recreation Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2696", level: "associate", credential: "A.S." },
  { name: "Emergency Administration and Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2786", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2671", level: "associate", credential: "A.S." },
  { name: "Dental Assisting Technology and Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2745", level: "certificate", credential: "A.T.D." },
  { name: "Diagnostic Medical Sonography", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2785", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services (EMS) Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2669", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Technician", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2668", level: "certificate", credential: "A.T.D." },
  { name: "Medical Assisting Advanced", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2790", level: "associate", credential: "A.S." },
  { name: "Medical Assisting", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2781", level: "certificate", credential: "C.C." },
  { name: "Nursing", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2744", level: "bachelor", credential: "B.S." },
  { name: "Nursing", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2667", level: "associate", credential: "A.S." },
  { name: "Nursing (Bridge for Healthcare Professionals to Nursing)", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2722", level: "associate", credential: "A.S." },
  { name: "Nurse Assistant, Long Term Care", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2718", level: "certificate", credential: "C.C." },
  { name: "Paramedic", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2666", level: "certificate", credential: "Cert." },
  { name: "Patient Care Technician", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2770", level: "certificate", credential: "C.C." },
  { name: "Phlebotomy", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2766", level: "certificate", credential: "C.C." },
  { name: "Radiologic Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2664", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2663", level: "associate", credential: "A.S." },
  { name: "Surgical Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2734", level: "associate", credential: "A.S." },
  { name: "Social and Human Services", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2787", level: "associate", credential: "A.S." },
  { name: "Applied Artificial Intelligence", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2769", level: "associate", credential: "A.S." },
  { name: "Artificial Intelligence Practitioner", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2783", level: "certificate", credential: "C.C." },
  { name: "Applied Cybersecurity", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2731", level: "certificate", credential: "C.C." },
  { name: "Computer Information Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2771", level: "associate", credential: "A.S." },
  { name: "Computer Programming and Web Development", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2687", level: "associate", credential: "A.S." },
  { name: "Computer Programming and Analysis", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2685", level: "certificate", credential: "Cert." },
  { name: "Computer Programming Specialist", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2684", level: "certificate", credential: "Cert." },
  { name: "Cybersecurity", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2686", level: "associate", credential: "A.S." },
  { name: "Cybersecurity Operations", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2763", level: "associate", credential: "A.S." },
  { name: "Data Science Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2778", level: "associate", credential: "A.S." },
  { name: "Game Development Design", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2774", level: "associate", credential: "A.S." },
  { name: "Network Systems Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2723", level: "associate", credential: "A.S." },
  { name: "Network Infrastructure", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2725", level: "certificate", credential: "Cert." },
  { name: "Network Security: Cyber Forensics", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2751", level: "certificate", credential: "Cert." },
  { name: "Network Support Technician", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2726", level: "certificate", credential: "Cert." },
  { name: "Electronics Engineering Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2776", level: "associate", credential: "A.S." },
  { name: "Engineering Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2721", level: "associate", credential: "A.S." },
  { name: "Engineering Technologies Support Specialist", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2713", level: "certificate", credential: "Cert." },
  { name: "Pneumatics, Hydraulics and Motors for Manufacturing", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2665", level: "certificate", credential: "Cert." },
  { name: "Welding Technology", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2715", level: "certificate", credential: "C.C." },
  { name: "Welding Technology Advanced", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2740", level: "certificate", credential: "C.C." },
  { name: "Commercial Vehicle Driving", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2743", level: "certificate", credential: "C.C." },
  { name: "Marine Services Technologies", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2779", level: "certificate", credential: "C.C." },
  { name: "Supply Chain Management", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2762", level: "associate", credential: "A.S." },
  { name: "Unmanned Vehicle Systems", url: "https://catalog.tsc.fl.edu/preview_program.php?catoid=24&poid=2764", level: "associate", credential: "A.S." },
];
