// UCF degree catalog: program name -> official program page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:ucf
//
// Source:     https://ucf.kuali.co/api/v1/catalog/programs/66bcc88cf93938001c548373
//             https://ucf.kuali.co/api/v1/catalog/programs/680f83ed108fd8c229965c69
// Scraped:    2026-07-26
// Programs:   334 (190 bachelor, 144 graduate)
//
// UCF is a four-year university (like FIU), so pathways start at the
// bachelor's rather than an associate degree — see universitySystemPrompt in
// app/lib/pathwayPrompts.ts. Only "Major" (undergrad) and
// "Master"/"Doctoral"/"Master of Fine Arts"/"Specialist" (grad) program types
// are included; minors, certificates, and the associate-level "Articulated
// A.S." track are excluded because they aren't a degree pathway on their own.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const UCF_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rySv41-uiu", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Accounting MSA", url: "https://www.ucf.edu/catalog/graduate/#/programs/By5QRxdid", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Actuarial Science (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hyd4J-dod", level: "bachelor", area: "College of Sciences" },
  { name: "Advertising/Public Relations (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Syg8VyZOo_", level: "bachelor", area: "College of Sciences" },
  { name: "Aerospace Engineering (B.S.A.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJlLFjn3u", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Aerospace Engineering MSAE", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1flnRguiu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Aerospace Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkBVkWOoO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Anthropology (B.A.), Anthropological Methods and Practice Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hkgc4kWOj_", level: "bachelor", area: "College of Sciences" },
  { name: "Anthropology (B.A.), General Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1v2uXwHA", level: "bachelor", area: "College of Sciences" },
  { name: "Anthropology MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1knAeuo_", level: "graduate", area: "College of Sciences" },
  { name: "Applied Learning and Instruction MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1H9mAeuod", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Architecture (B.Des.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ByvEk-dj_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Art, History Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1-Xc8Rid", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Art, Immersive Experience Design Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJE_Ed94a", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Art, Studio Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJgxmcL0i_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Art, Visual Arts Management Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJNQ98CiO", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Athletic Training MAT", url: "https://www.ucf.edu/catalog/graduate/#/programs/BkRmJb_sO", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Big Data Analytics PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJYoRe_sO", level: "graduate", area: "College of Sciences" },
  { name: "Biology (B.S.), Ecology, Evolutionary and Conservation Biology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S15dhsAeC", level: "bachelor", area: "College of Sciences" },
  { name: "Biology (B.S.), General Biology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkYf7sCgA", level: "bachelor", area: "College of Sciences" },
  { name: "Biology (B.S.), Marine and Aquatic Biology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJUoAiAxR", level: "bachelor", area: "College of Sciences" },
  { name: "Biology (B.S.), Plant Sciences Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ByCEx2Ax0", level: "bachelor", area: "College of Sciences" },
  { name: "Biology (B.S.), Pre-Health Professional Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B10Ej9RlA", level: "bachelor", area: "College of Sciences" },
  { name: "Biology (B.S.), Zoology and Pre-Veterinarian Science Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hkev41buid", level: "bachelor", area: "College of Sciences" },
  { name: "Biology MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1lTjCxOsd", level: "graduate", area: "College of Sciences" },
  { name: "Biomedical Engineering MSBME", url: "https://www.ucf.edu/catalog/graduate/#/programs/Syxh0lOsd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Biomedical Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1jr6bG4t", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Biomedical Sciences (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJGDE1b_s_", level: "bachelor", area: "College of Medicine" },
  { name: "Biomedical Sciences (B.S.), Integrated Biomedical Sciences Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkH33vPjkl", level: "bachelor", area: "College of Medicine" },
  { name: "Biomedical Sciences (B.S.), Neuroscience Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJW-Q5UAsu", level: "bachelor", area: "College of Medicine" },
  { name: "Biomedical Sciences (B.S.), Pre-Medical Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkKB11kpi", level: "bachelor", area: "College of Medicine" },
  { name: "Biomedical Sciences MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkMuiCl_su", level: "graduate", area: "College of Medicine" },
  { name: "Biomedical Sciences PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hke_jAe_od", level: "graduate", area: "College of Medicine" },
  { name: "Biotechnology (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rk_VJ-_iO", level: "bachelor", area: "College of Medicine" },
  { name: "Biotechnology MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyYsAedo_", level: "graduate", area: "College of Medicine" },
  { name: "Business Administration MBA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkG9mCeusO", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Business Administration PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkx6s0xusO", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Business Analytics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1EInJQPF", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Business Economics (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJAN1bOoO", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Business Economics (B.S.B.A.), Business Analytics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SygtEkWuiu", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Career and Technical Education (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S16VyZ_jO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Career and Technical Education (B.S.), Workforce Training and Development Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJwwWI-pd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Career and Workforce Education MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkpXRx_o_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Chemistry (B.A.), Education Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkKdQek-A", level: "bachelor", area: "College of Sciences" },
  { name: "Chemistry (B.A.), Industry Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1MFolJZ0", level: "bachelor", area: "College of Sciences" },
  { name: "Chemistry (B.A.), Preprofessional Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJlsQYruF", level: "bachelor", area: "College of Sciences" },
  { name: "Chemistry (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rylD4y-dod", level: "bachelor", area: "College of Sciences" },
  { name: "Chemistry (B.S.), Biochemistry Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rygU7q8RjO", level: "bachelor", area: "College of Sciences" },
  { name: "Chemistry MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1eAiCxOs_", level: "graduate", area: "College of Sciences" },
  { name: "Chemistry PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1lYsCl_oO", level: "graduate", area: "College of Sciences" },
  { name: "Civil Engineering (B.S.C.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkPEybOiO", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Civil Engineering MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkel3CeOjO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Civil Engineering MSCE", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1ZQsRx_sd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Civil Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/HygzP0ldiu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Clinical Psychology MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1ajReOid", level: "graduate", area: "College of Sciences" },
  { name: "Clinical Psychology MS, Master Along the Way Track", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1XrEo5bkl", level: "graduate", area: "College of Sciences" },
  { name: "Clinical Psychology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1lKjAgdju", level: "graduate", area: "College of Sciences" },
  { name: "Communication (B.A.), Business & Professional Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkcASVwB0", level: "bachelor", area: "College of Sciences" },
  { name: "Communication (B.A.), General Communication Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1AqtEDSA", level: "bachelor", area: "College of Sciences" },
  { name: "Communication (B.A.), Visual Communication Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJEJSkW_oO", level: "bachelor", area: "College of Sciences" },
  { name: "Communication and Conflict (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJxvVyZOiO", level: "bachelor", area: "College of Sciences" },
  { name: "Communication MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyZg3Rx_sd", level: "graduate", area: "College of Sciences" },
  { name: "Communication Sciences and Disorders (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkMNfA30i", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Communication Sciences and Disorders MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/By7uoAldiu", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Communication Sciences and Disorders PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkTTfqGWJx", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Computer Engineering MSCpE", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1LoRxOsO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Computer Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryzvAe_id", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Computer Engineering, Comprehensive Track (B.S.Cp.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ByV-QqL0sd", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Computer Engineering, Digital Circuits Track (B.S.Cp.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJgmm9LRo_", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Computer Science (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkbvEJ-_iO", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Computer Science MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkZmjRgdjd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Computer Science PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bk4tAeOou", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Computer Vision MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkWxNJ-OoO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Construction Engineering (B.S.Con.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1WDN1Wus_", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Counselor Education MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyasCedo_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Counselor Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJZ0jAeOjd", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Creative Writing MFA", url: "https://www.ucf.edu/catalog/graduate/#/programs/H12QAedod", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Criminal Justice (B.A. or B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1qEJWujd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Criminal Justice MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJZFs0x_jO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Criminal Justice PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryeuoRedj_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Criminal Justice, Professional Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJA4mOJRT", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Criminal Justice, Professional Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJME6ySHT", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Criminal Justice, Scholars' Track (B.A. or B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkxQcLRsO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Curriculum and Instruction EdD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryiXRl_o_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Curriculum and Instruction MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1b6sAx_jO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Cyber Security and Privacy MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hk7CQJZdju", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Data Analytics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJXjRg_su", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Data Science (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkpNJ-_sd", level: "bachelor", area: "College of Sciences" },
  { name: "Digital Forensics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/BklmsAgOsd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Digital Media (B.A.), Game Design Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Sk9aXDY5p", level: "bachelor", area: "College of Sciences" },
  { name: "Digital Media (B.A.), Web and Interactive Media Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJUySyZOs_", level: "bachelor", area: "College of Sciences" },
  { name: "Digital Media MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SyeToAeuju", level: "graduate", area: "College of Sciences" },
  { name: "Doctor of Medicine MD", url: "https://www.ucf.edu/catalog/graduate/#/programs/SyX_jAe_ju", level: "graduate", area: "College of Medicine" },
  { name: "Early Childhood Development and Education (B.S.), Track 1: Education, Pre-Kindergarten - Primary (PK-3)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1x-X5LRju", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Early Childhood Development and Education MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rk_vAldjO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Early Childhood Development and Education, Track 2: Early Childhood Development (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Bk-7qICsu", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Economics (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Sk-yByZOo_", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Economics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkFQ0l_sd", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Education EdS", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryZlnAgdsu", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Education PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1xyhReOiO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Educational Leadership EdD", url: "https://www.ucf.edu/catalog/graduate/#/programs/SJ-TsCgOid", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Educational Leadership EdS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rylzvRxuj_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Educational Leadership MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJxRXJ-did", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Educational Leadership MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/ByOPAx_o_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Electrical Engineering MSEE", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyQiRedsu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkhvRl_oO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering, Communications and Signal Processing Track (B.S.E.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJGE7cLRi_", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering, Comprehensive Track (B.S.E.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1eXcIAod", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering, Power and Renewable Energy Track (B.S.E.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ryxQ5ICid", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Electrical Engineering, RF and Microwaves Track (B.S.E.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJfXQcIRid", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Elementary Education MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkuvCxusu", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Elementary Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJXwAeuoO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Elementary Education, K-6 Certification Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJlWm9UAou", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Elementary Education, Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1-m9U0su", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Elementary Education, Professional Studies Track (Non-certification) (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJVQc80ou", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Emergency and Crisis Management MECM", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1zaXJWus_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Emergency Management (B.A. / B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJyr1ZuoO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Emerging Media MFA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJCo0l_j_", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Emerging Media, Character Animation Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1QZXqI0od", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Emerging Media, Graphic Design Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJxgXcUCsO", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Engineering Management MSEM", url: "https://www.ucf.edu/catalog/graduate/#/programs/ByfXs0gOiu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "English MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/S1As0edju", level: "graduate", area: "College of Arts and Humanities" },
  { name: "English, Creative Writing Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hyyrk-diu", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "English, Literature (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1OUlAwnu", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "English, Rhetoric and Composition MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bkm9m0gOsO", level: "graduate", area: "College of Arts and Humanities" },
  { name: "English, Technical Communication Track (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1w1HkWuiO", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Entertainment Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJ1HkWusO", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Environmental Engineering (B.S.Env.E)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJ-yHybdj_", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Environmental Engineering MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/Syxl20g_jd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Environmental Engineering MSEnvE", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJxQjRgOiu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Environmental Engineering MSEnvE, Accelerated BS to MSEnvE", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkVAQ1-Oj_", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Environmental Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkbGvAxOj_", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Environmental Science (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Bk8JyY2gT", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Environmental Studies (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SyHkHyZ_jd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Event Leadership MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyJ9XLkNt", level: "graduate", area: "Rosen College of Hospitality Management" },
  { name: "Event Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BklkBJ-dod", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Exceptional Student Education (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1JSJZus_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Exceptional Student Education K-12 MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJ4Y0e_oO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Exceptional Student Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/SyfvRgusO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Exceptional Student Education, Learning and Development Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1QmqUAsd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Exercise Physiology, Education PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJ7q7Ce_j_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Feature Film Production MFA", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1NA7kWOoO", level: "graduate", area: "College of Sciences" },
  { name: "Film (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJWfryb_ou", level: "bachelor", area: "College of Sciences" },
  { name: "Film (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkxHJbuou", level: "bachelor", area: "College of Sciences" },
  { name: "Finance (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJlkByZusd", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "FinTech MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1MicHqQF", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Forensic Science (B.S.), Biochemistry Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BybmmcUAi_", level: "bachelor", area: "College of Sciences" },
  { name: "Forensic Science (B.S.), Chemistry Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BybWQqURoO", level: "bachelor", area: "College of Sciences" },
  { name: "Forensic Science MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkn7JW_ou", level: "graduate", area: "College of Sciences" },
  { name: "French and Francophone Studies (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1LkBJZdod", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "General Health Studies (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJPllD6g1l", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Health Administration MHA", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJgxhAxuj_", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Health Care Informatics MS, Professional Science Master's", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bkuj0lOi_", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Health Informatics (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Sym4cfWNT", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Health Information Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hkls2cURJl", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Health Promotion and Behavioral Sciences MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJa1ntIs3", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Health Sciences, Health Promotion Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1W75UCs_", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Health Sciences, Pre-Clinical Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJW7cI0oO", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Health Services Administration (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJJHyZ_jO", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "History (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1G1SyZOi_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "History MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bke9Q0eOou", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Hospitality and Tourism Management MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1khCx_s_", level: "graduate", area: "Rosen College of Hospitality Management" },
  { name: "Hospitality Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJxBkZdju", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Hospitality Management, PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkxCiRgOs_", level: "graduate", area: "Rosen College of Hospitality Management" },
  { name: "Human Factors and Cognitive Psychology MA, Master Along the Way Track", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkMm0a6ikg", level: "graduate", area: "College of Sciences" },
  { name: "Human Factors and Cognitive Psychology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1l5jAlOod", level: "graduate", area: "College of Sciences" },
  { name: "Humanities and Cultural Studies (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJxJByZOo_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Industrial and Organizational Psychology MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkXpjCxuoO", level: "graduate", area: "College of Sciences" },
  { name: "Industrial and Organizational Psychology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bkjs0x_jO", level: "graduate", area: "College of Sciences" },
  { name: "Industrial Engineering (B.S.I.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1JHJWujO", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Industrial Engineering MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/BkenClOjO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Industrial Engineering MSIE", url: "https://www.ucf.edu/catalog/graduate/#/programs/rywj0e_sO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Industrial Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ByIDCg_j_", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Information Technology (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1MkH1WOiu", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Instructional Design and Technology MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rk0j0x_sd", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Integrated Business (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJleH1ZOsu", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Integrated Sciences and Technology (B.S.), Integrated Sciences Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkQofaxIa", level: "bachelor", area: "College of Sciences" },
  { name: "Integrated Sciences and Technology (B.S.), Integrated Sciences: Education Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1Cf3BGXR", level: "bachelor", area: "College of Sciences" },
  { name: "Integrative and Conservation Biology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkQxnRe_j_", level: "graduate", area: "College of Sciences" },
  { name: "Integrative Anthropological Sciences PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1egnRgdo_", level: "graduate", area: "College of Sciences" },
  { name: "Integrative General Studies (B.G.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Sk_KaosNh", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Interactive Entertainment MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkqmAgOjd", level: "graduate", area: "College of Sciences" },
  { name: "Interdisciplinary Studies (B.A./B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1gfBJZ_od", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Interdisciplinary Studies MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hke30guod", level: "graduate", area: "College of Graduate Studies" },
  { name: "Interdisciplinary Studies MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/Byl2Alds_", level: "graduate", area: "College of Graduate Studies" },
  { name: "International and Global Studies (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ByeS1-uod", level: "bachelor", area: "College of Sciences" },
  { name: "Journalism (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rycEybdiO", level: "bachelor", area: "College of Sciences" },
  { name: "K-8 Mathematics and Science Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkwDRgdjd", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Kinesiology (B.S.), Exercise and Sport Physiology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HyfmcU0sd", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Kinesiology (B.S.), Strength and Conditioning Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJBLhUoM9", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Kinesiology MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkuPClOo_", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Kinesiology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJNjYr0YY", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Latin American, Caribbean and Latinx Studies (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hyl-Bybuo_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Leadership B.A., Commerce Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkMm4j_p6", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.A., Communication Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkj6bsOaT", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.A., Education Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hyqt4idTp", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.A., Environmental Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJa6VsOa6", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.A., Multidisciplinary Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkkHHq4Tp", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.S., Commerce Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkA_Cc_6T", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.S., Communication Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ry24hqu6p", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.S., Education Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJFQys_p6", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.S., Environmental Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkFKJju66", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Leadership B.S., Multidisciplinary Leadership Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkFSkVOZa", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Legal Studies (B.A. or B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJGB1Wdo_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Lifestyle Community Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJgQr1Wuod", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Lodging and Restaurant Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BklGr1Zdsd", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Lodging and Restaurant Management, A.S. to B.S. Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1bCmxPY6", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Management (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJWSkW_oO", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Management MSM", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hkg3mRgOiO", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Marketing (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ByxMHk-Ojd", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Marriage, Couple, and Family Therapy MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SJXPReuod", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Materials Science and Engineering (B.S.M.S.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1zSJ-_jO", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Materials Science and Engineering MSMSE", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkemsRlOjd", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Materials Science and Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BylYReOsu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Mathematical Science MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HyWTj0xdod", level: "graduate", area: "College of Sciences" },
  { name: "Mathematics (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Sk7VZzF-eg", level: "bachelor", area: "College of Sciences" },
  { name: "Mathematics PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJGaoAlOou", level: "graduate", area: "College of Sciences" },
  { name: "Mechanical Engineering (B.S.M.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1GGSJbds_", level: "bachelor", area: "College of Engineering and Computer Science" },
  { name: "Mechanical Engineering MSME", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1blhRguju", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Mechanical Engineering PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/Skl4KAe_i_", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Media Production and Management (B.A.), Media Management and Operations Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1PVy-dou", level: "bachelor", area: "College of Sciences" },
  { name: "Media Production and Management (B.A.), Production Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BylMq6T1A", level: "bachelor", area: "College of Sciences" },
  { name: "Media Production and Management (B.A.), Sports Production Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJdY1T61R", level: "bachelor", area: "College of Sciences" },
  { name: "Medical Laboratory Sciences (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkxzHJZOjO", level: "bachelor", area: "College of Medicine" },
  { name: "Modeling and Simulation MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1IiCx_oO", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Modeling and Simulation PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BkNjCe_j_", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Molecular and Cellular Biology (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ryGGSJZdsO", level: "bachelor", area: "College of Medicine" },
  { name: "Molecular Microbiology (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJxXSkbOo_", level: "bachelor", area: "College of Medicine" },
  { name: "Music (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkubEAvnu", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Music Education (B.M.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJDNkZOod", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Music MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkiQRxOsd", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Music, Composition Track (B.M.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ryem9L0ju", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Music, Jazz Studies Track (B.M.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HyWQc8Ri_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Music, Performance Track (B.M.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkmQ9I0jd", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Nanotechnology MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkQiAluju", level: "graduate", area: "College of Graduate Studies" },
  { name: "Nonprofit Management (B.A. or B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1GSkbuj_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Nonprofit Management MNM", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJ-Yi0luou", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Nursing (B.S.N.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1lGryZuid", level: "bachelor", area: "College of Nursing" },
  { name: "Nursing (B.S.N.), R.N. to B.S.N. Program", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ry2bJQ5hO", level: "bachelor", area: "College of Nursing" },
  { name: "Nursing MSN", url: "https://www.ucf.edu/catalog/graduate/#/programs/Byel2AlusO", level: "graduate", area: "College of Nursing" },
  { name: "Nursing PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJeFo0gdsd", level: "graduate", area: "College of Nursing" },
  { name: "Nursing Practice DNP", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hy-xn0gdjd", level: "graduate", area: "College of Nursing" },
  { name: "Nursing, Accelerated Second Degree B.S.N. Option (B.S.N.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkYjRedju", level: "bachelor", area: "College of Nursing" },
  { name: "Optics and Photonics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkbFo0lOs_", level: "graduate", area: "College of Optics and Photonics" },
  { name: "Optics and Photonics PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/BygFj0xujd", level: "graduate", area: "College of Optics and Photonics" },
  { name: "Philosophy (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJxfBJW_su", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Photography (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJw4kb_o_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Photonic Science and Engineering (B.S.P.S.E.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HyzrJbds_", level: "bachelor", area: "College of Optics and Photonics" },
  { name: "Physical Therapy DPT", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJr_sRxusO", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Physics (B.A.), Biophysics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B123dBPS0", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.A.), Education Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJNbHHPHR", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.A.), Information Technology/ Data Science Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkVhuSPr0", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.A.), Technical Writing Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1QHy-did", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.S.), Astronomy Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1uxuJCrC", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.S.), Computational Physics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJ4KvJArA", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.S.), General Physics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1d4JZOod", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.S.), Materials Physics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1037JRBC", level: "bachelor", area: "College of Sciences" },
  { name: "Physics (B.S.), Optics and Lasers Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1J4uy0HC", level: "bachelor", area: "College of Sciences" },
  { name: "Physics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkbujAxus_", level: "graduate", area: "College of Sciences" },
  { name: "Physics PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryeTo0e_j_", level: "graduate", area: "College of Sciences" },
  { name: "Planetary and Space Sciences PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryKOSeRhR", level: "graduate", area: "College of Sciences" },
  { name: "Political Science (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Hy5Nk-usu", level: "bachelor", area: "College of Sciences" },
  { name: "Political Science (B.A.), Intelligence and National Security Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S18X9U0od", level: "bachelor", area: "College of Sciences" },
  { name: "Political Science (B.A.), Pre-Law Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HyelX9ICs_", level: "bachelor", area: "College of Sciences" },
  { name: "Political Science MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJCiCg_id", level: "graduate", area: "College of Sciences" },
  { name: "Psychology (B.S.), Clinical Psychology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkcNkZ_s_", level: "bachelor", area: "College of Sciences" },
  { name: "Psychology (B.S.), Experimental Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJi_610r0", level: "bachelor", area: "College of Sciences" },
  { name: "Psychology (B.S.), General Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H19RegASR", level: "bachelor", area: "College of Sciences" },
  { name: "Psychology (B.S.), Human Factors Psychology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkxqflCB0", level: "bachelor", area: "College of Sciences" },
  { name: "Psychology (B.S.), Industrial/Organizational Psychology Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ryw4zeCS0", level: "bachelor", area: "College of Sciences" },
  { name: "Psychology (B.S.), Neuroscience Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJwtfl0SC", level: "bachelor", area: "College of Sciences" },
  { name: "Public Administration (B.A. / B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJMrkWuj_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Public Administration MPA", url: "https://www.ucf.edu/catalog/graduate/#/programs/Sk5sAlujO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Public Affairs PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rkZehCldi_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Public Policy MPP", url: "https://www.ucf.edu/catalog/graduate/#/programs/B1lAQJWuod", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Reading Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/rymD0ldsu", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Real Estate (B.S.B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S17Hy-uj_", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Real Estate (B.S.B.A.), Appraisal Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkh9GepG1e", level: "bachelor", area: "Barry S. Miller College of Business" },
  { name: "Real Estate MSRE", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJxqXAedju", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Religion and Cultural Studies (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1zHkWOs_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Research Administration MRA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJbOiAx_su", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Robotics and Autonomous Systems MSRAS", url: "https://www.ucf.edu/catalog/graduate/#/programs/HkN61gn2h", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "School Psychology EdS", url: "https://www.ucf.edu/catalog/graduate/#/programs/B17fv0g_o_", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Secondary Education (B.S.), English Language Arts Education Track with ESOL and Reading Endorsement", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkfQqL0su", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education (B.S.), Science Education Chemistry Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1cmqLCsO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education (B.S.), Science Education Physics Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1FX9L0jd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education MEd", url: "https://www.ucf.edu/catalog/graduate/#/programs/H1pjAldju", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, English Language Arts Education - Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJK7q8RiO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Mathematics Education - Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkbL75LAsu", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Mathematics Education Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BygVX9URod", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Science Education Biology – Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkzQcUAo_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Science Education Biology Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BygYmqIAoO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Science Education Chemistry – Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BJw798Cod", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Science Education Physics – Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1fZX58Rou", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Social Science Education - Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1qXcIRsu", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Secondary Education, Social Science Education Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/S1tm5LRi_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Security Studies PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJMaoAgOju", level: "graduate", area: "College of Sciences" },
  { name: "Social Sciences (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/H1zBJWOsd", level: "bachelor", area: "College of Sciences" },
  { name: "Social Work (B.S.W.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HkWQS1Z_od", level: "bachelor", area: "College of Health Professions and Sciences" },
  { name: "Social Work MSW", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1xl20e_j_", level: "graduate", area: "College of Health Professions and Sciences" },
  { name: "Sociology (B.A./ B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HyZfrJbuj_", level: "bachelor", area: "College of Sciences" },
  { name: "Sociology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/HygTsCldsO", level: "graduate", area: "College of Sciences" },
  { name: "Sociology, Applied MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJToAgOsd", level: "graduate", area: "College of Sciences" },
  { name: "Spanish (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/BkaIfRv2_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Spanish MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/BkcQAldid", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Sport Business Management MSBM", url: "https://www.ucf.edu/catalog/graduate/#/programs/HJcQCeus_", level: "graduate", area: "Barry S. Miller College of Business" },
  { name: "Statistics (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Bk4H1bujO", level: "bachelor", area: "College of Sciences" },
  { name: "Statistics and Data Science MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/ryZ0mkbdsO", level: "graduate", area: "College of Sciences" },
  { name: "Strategic Communication PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/r1071WOsu", level: "graduate", area: "College of Sciences" },
  { name: "Studio Art (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1bXSkZdi_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Sustainability (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkjN8vlb6", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Sustainability (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkzNBUA2p", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Systems Engineering, MSSE", url: "https://www.ucf.edu/catalog/graduate/#/programs/Bk0XkZOsu", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Teacher Education (B.S.), Art Education Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/Byhm9URj_", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teacher Education (B.S.), Physical Education Track", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/ryF79ICsu", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teacher Education MAT", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJl3CgOjO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Teacher Education, Art Education – Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJb-79U0oO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teacher Education, Physical Education - Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SkZ-Qc8AjO", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teacher Education, World Languages Education - Lifelong Learning Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/r1gt75L0sd", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teacher Education, World Languages Education Track (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/B1tmq8Asu", level: "bachelor", area: "College of Community Innovation and Education" },
  { name: "Teaching English to Speakers of Other Languages (TESOL) MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SyZqXRlusO", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Texts and Technology PhD", url: "https://www.ucf.edu/catalog/graduate/#/programs/rygsXAgusd", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Theatre (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJfmBkWOiO", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Theatre MA", url: "https://www.ucf.edu/catalog/graduate/#/programs/SkcmRgdou", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Theatre MFA", url: "https://www.ucf.edu/catalog/graduate/#/programs/rJ6iAldi_", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Theatre, Acting Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkz7cUAju", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Theatre, Design and Technology Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/SJlXXqI0o_", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Theatre, Musical Theatre Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rkl75UAsd", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Theatre, Stage Management Track (B.F.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/rJmX9LRsO", level: "bachelor", area: "College of Arts and Humanities" },
  { name: "Theme Park and Attraction Management (B.S.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/By5uKqYvt", level: "bachelor", area: "Rosen College of Hospitality Management" },
  { name: "Themed Experience MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/BJ-A7yZOo_", level: "graduate", area: "College of Arts and Humanities" },
  { name: "Travel Technology and Analytics MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/Hyb6Qybuid", level: "graduate", area: "College of Engineering and Computer Science" },
  { name: "Urban and Regional Planning MS", url: "https://www.ucf.edu/catalog/graduate/#/programs/SJfOjRguoO", level: "graduate", area: "College of Community Innovation and Education" },
  { name: "Writing and Rhetoric (B.A.)", url: "https://www.ucf.edu/catalog/undergraduate/#/programs/HJ4BJbuo_", level: "bachelor", area: "College of Arts and Humanities" },
];

// UCF is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the master's of the same name.
export const ucfCatalog = createProgramCatalog(UCF_PROGRAMS, { preferred: "bachelor" });
