// UF degree catalog: program name -> official program page.
//
// GENERATED FILE — do not edit by hand. Regenerate with:
//   npm run scrape:uf
//
// Source:     https://catalog.ufl.edu/UGRD/programs/
//             https://gradcatalog.ufl.edu/graduate/programs-college/
// Scraped:    2026-07-26
// Programs:   316 (159 bachelor, 157 graduate)
//
// UF is a four-year university (like FIU/UCF), so pathways start at the
// bachelor's rather than an associate degree. Undergraduate entries are
// "major"-type cards only (minors/certificates excluded). Graduate entries
// come from the majors-by-college sitemap; a major's own page can list more
// than one graduate credential (e.g. both an M.S. and a Ph.D.), which is fine
// since this app's ProgramLevel doesn't distinguish between them.
//
// Many UF majors share an IDENTICAL name between the bachelor's and graduate
// catalogs (e.g. "Accounting" is both), unlike FIU/UCF where the credential is
// embedded in the name itself. Graduate entries get a credential field joined
// from the Graduate Degree Table ("Master", "Doctor", "Specialist") so
// programCatalog.ts's matcher can tell them apart — see programCatalogs.test.ts.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const UF_PROGRAMS: SchoolProgram[] = [
  { name: "Accounting", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGACT/ACT_BSAC/", level: "bachelor", area: "Accounting, Fischer School of" },
  { name: "Accounting", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/accounting/accounting/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Advertising", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/ADV_BSAD/", level: "bachelor", area: "Advertising" },
  { name: "Advertising | Persuasive Messaging", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/ADV_BSAD02_UFO/", level: "bachelor", area: "Advertising" },
  { name: "Aerospace Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/ARO_BSAE/", level: "bachelor", area: "Mechanical & Aerospace Engineering" },
  { name: "African American Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/AFA_BA/", level: "bachelor", area: "African American Studies" },
  { name: "African Languages", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FAF_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Agricultural and Biological Engineering (CALS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/agricultural-biological-engineering/agricultural-biological/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Agricultural Education and Communication", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/AEC_BS/", level: "bachelor", area: "Agricultural Education and Communication" },
  { name: "Agricultural Education and Communication", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/AEC_BS_UFO/", level: "bachelor", area: "Agricultural Education and Communication" },
  { name: "Agricultural Education and Communication", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/agricultural-education-communication/agricultural-education-communication/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Agricultural Operations Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/AOM_BS/", level: "bachelor", area: "Agricultural and Biological Engineering" },
  { name: "Agronomy", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/agronomy/agronomy/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "American Government, History, Literature, and Law", url: "https://catalog.ufl.edu/UGRD/colleges-schools/hamilton/AGH_BA/", level: "bachelor", area: "Hamilton School" },
  { name: "Anatomical Sciences Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/anatomical-sciences-education/", level: "graduate", area: "College of Education", credential: "Doctor, Master" },
  { name: "Anatomical Sciences Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/interdisciplinary-departments/anatomical-sciences-education/", level: "graduate", area: "College of Medicine", credential: "Doctor, Master" },
  { name: "Animal Molecular and Cellular Biology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/animal-molecular-cellular-biology/animal-molecular-cellular-biology/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Animal Molecular and Cellular Biology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/veterinary-medicine/animal-molecular-cellular-biology/animal-molecular-cellular-biology/", level: "graduate", area: "College of Veterinary Medicine", credential: "Doctor" },
  { name: "Animal Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/ANS_BS/", level: "bachelor", area: "Animal Sciences" },
  { name: "Animal Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/animal/animal/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Anthropology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/APY_BA_BS/", level: "bachelor", area: "Anthropology" },
  { name: "Anthropology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/APY_BA_UFO/", level: "bachelor", area: "Anthropology" },
  { name: "Anthropology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/anthropology/anthropology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Applied Physiology and Kinesiology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/APK_BSAP/", level: "bachelor", area: "Applied Physiology and Kinesiology" },
  { name: "Applied Physiology and Kinesiology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/health-human-performance/applied-physiology-kinesiology/applied-physiology-kinesiology/", level: "graduate", area: "College of Health and Human Performance", credential: "Master" },
  { name: "Arabic", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FAR_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Architecture", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGDCP/ARC_BDES/", level: "bachelor", area: "Architecture" },
  { name: "Architecture", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/architecture/architecture/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Art", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/art-history/art/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Art | BA", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/VAS_BA/", level: "bachelor", area: "Art + Art History" },
  { name: "Art | BFA", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/ART_BFA/", level: "bachelor", area: "Art + Art History" },
  { name: "Art Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/art-history/art-education/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Art History", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/ARH_BAHA/", level: "bachelor", area: "Art + Art History" },
  { name: "Art History", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/art-history/art-history/", level: "graduate", area: "College of the Arts", credential: "Doctor, Master" },
  { name: "Arts in Medicine", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/interdisciplinary-department/medicine/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Astronomy", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/astronomy/astronomy/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Astronomy and Astrophysics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/ATY_BA_ASP_BS/", level: "bachelor", area: "Astronomy" },
  { name: "Audiology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/speech-language-hearing-sciences/audiology/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor" },
  { name: "Biochemistry and Molecular Biology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/biochemistry-molecular/biochemistry-molecular-biology/", level: "graduate", area: "College of Medicine", credential: "Master" },
  { name: "Biological Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/BE_BSBE/", level: "bachelor", area: "Agricultural and Biological Engineering" },
  { name: "Biology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/BIO_BA_UFO/", level: "bachelor", area: "Biology" },
  { name: "Biology | CALS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/BLY_BS/", level: "bachelor", area: "Biology" },
  { name: "Biology | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/BIO_BA_BS/", level: "bachelor", area: "Biology" },
  { name: "Biomedical Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/BME_BSBM/", level: "bachelor", area: "Biomedical Engineering" },
  { name: "Biostatistics (Medicine)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/biostatistics/biostatistics/", level: "graduate", area: "College of Medicine", credential: "Doctor, Master" },
  { name: "Biostatistics (PHHP)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/biostatistics/biostatistics/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Botany", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/biology/botany/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Botany | CALS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/BTY_BS/", level: "bachelor", area: "Biology" },
  { name: "Botany | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/BOT_BS/", level: "bachelor", area: "Biology" },
  { name: "Business Administration (Accounting)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/accounting/business-administration/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Finance, Insurance, and Real Estate)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/finance-insurance-real-estate/business-administration/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Information Systems and Operations Management)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/information-systems-operations-management/business-administration/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (M.A.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/interdisciplinary-departments/business-administration-ma/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (M.B.A.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/interdisciplinary-departments/business-administration-mba/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (M.S.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/interdisciplinary-departments/business-administration-ms/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Management)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/management/business-administration/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Marketing - Master's)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/marketing/business-administration-masters/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Marketing - Ph.D.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/marketing/business-administration-phd/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration (Ph.D.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/interdisciplinary-departments/business-administration-phd/", level: "graduate", area: "Warrington College of Business", credential: "Doctor, Master" },
  { name: "Business Administration | General Business | BSBA", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/BAG_BSBA_UFO/", level: "bachelor", area: "Business, Heavener School of" },
  { name: "Business Administration | General Studies | BABA", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/BAG_BABA/", level: "bachelor", area: "Business, Heavener School of" },
  { name: "Business Administration | General Studies | BABA", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/BAG_BABA_UFO/", level: "bachelor", area: "Business, Heavener School of" },
  { name: "Chemical Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/CHE_BSCH/", level: "bachelor", area: "Chemical Engineering" },
  { name: "Chemistry", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/chemistry/chemistry/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Chemistry | Biochemistry", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CHY_BS/", level: "bachelor", area: "Chemistry" },
  { name: "Chinese", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FCH_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Civil Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/CVE_BSCE/", level: "bachelor", area: "Civil and Coastal Engineering" },
  { name: "Classical Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CLC_BA/", level: "bachelor", area: "Classics" },
  { name: "Classical Studies", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/classics/classical-studies/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor" },
  { name: "Communication Sciences and Disorders", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGPBH/CSD_BHS/", level: "bachelor", area: "Speech, Language, and Hearing Sciences" },
  { name: "Communication Sciences and Disorders", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGPBH/CSD_BHS_UFO/", level: "bachelor", area: "Speech, Language, and Hearing Sciences" },
  { name: "Communication Sciences and Disorders", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/speech-language-hearing-sciences/communication-sciences-disorders/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Master" },
  { name: "Computer Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/CPE_BSCO/", level: "bachelor", area: "Electrical and Computer Engineering" },
  { name: "Computer Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CSC_BS_UFO/", level: "bachelor", area: "Computer & Information Science & Engineering" },
  { name: "Computer Science (CLAS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/computer-information-science-engineering/computer/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Computer Science | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CSC_BS/", level: "bachelor", area: "Computer & Information Science & Engineering" },
  { name: "Computer Science | Herbert Wertheim College of Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/CPS_BSCS/", level: "bachelor", area: "Computer & Information Science & Engineering" },
  { name: "Construction Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGCMN/CM_BSCM/", level: "bachelor", area: "Construction Management" },
  { name: "Construction Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/construction-management/construction/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Counseling and Counselor Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/counseling-counselor/", level: "graduate", area: "College of Education", credential: "Doctor" },
  { name: "Counseling Psychology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/psychology/counseling/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor" },
  { name: "Creative Writing", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/english/creative-writing/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Criminology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CRI_BA/", level: "bachelor", area: "Sociology and Criminology & Law" },
  { name: "Criminology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/CRI_BA_UFO/", level: "bachelor", area: "Sociology and Criminology & Law" },
  { name: "Criminology, Law and Society", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/sociology-criminology-law/criminology-law-society/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Curriculum and Instruction (Ed.D.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/curriculum-instruction-ccd/", level: "graduate", area: "College of Education", credential: "Doctor, Master, Specialist" },
  { name: "Curriculum and Instruction (ISC)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/curriculum-instruction-isc/", level: "graduate", area: "College of Education", credential: "Doctor, Master, Specialist" },
  { name: "Dance | Bachelor of Arts", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/DAN_BA/", level: "bachelor", area: "Theatre + Dance, School of" },
  { name: "Dance | Bachelor of Fine Arts", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/DAN_BFA/", level: "bachelor", area: "Theatre + Dance, School of" },
  { name: "Data Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/DAT_BS/", level: "bachelor", area: "Statistics" },
  { name: "Dental Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/dentistry/dental/dental/", level: "graduate", area: "College of Dentistry", credential: "Master" },
  { name: "Design and Visual Communications", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/art-history/design-visual-communications/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Design, Construction, and Planning (Ph.D.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/interdisciplinary-departments/design-construction-planning-phd/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Doctor" },
  { name: "Dietetics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/DTS_BS/", level: "bachelor", area: "Food Science and Human Nutrition" },
  { name: "Digital Arts and Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/DAR_BADA_UFO/", level: "bachelor", area: "Digital Worlds Institute" },
  { name: "Digital Arts and Sciences (Arts)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/digital-worlds/digital-arts-sciences/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Digital Arts and Sciences | Bachelor of Arts", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/DAR_BADA/", level: "bachelor", area: "Digital Worlds Institute" },
  { name: "Digital Arts and Sciences | Bachelor of Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/DAS_BSDA/", level: "bachelor", area: "Computer & Information Science & Engineering" },
  { name: "Digital Worlds Institute", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/digital-worlds/", level: "graduate", area: "College of the Arts" },
  { name: "Dual Languages", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FLL_BA/FDU_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Early Childhood Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/special-education-psychology-early-childhood-studies/early-childhood/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Early Childhood Education | Age 3 - Grade 3", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EYC_BAE/", level: "bachelor", area: "" },
  { name: "Early Childhood Education | Age 3 - Grade 3", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EYC_BAE_UFO/", level: "bachelor", area: "Special Education" },
  { name: "Economics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/ECO_BA/", level: "bachelor", area: "Economics" },
  { name: "Economics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/economics/economics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Education Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EDS_BA/", level: "bachelor", area: "" },
  { name: "Education Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EDS_BA_UFO/", level: "bachelor", area: "" },
  { name: "Educational Leadership", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/educational-leadership/", level: "graduate", area: "College of Education", credential: "Doctor, Master, Specialist" },
  { name: "Electrical Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/ELE_BSEE/", level: "bachelor", area: "Electrical and Computer Engineering" },
  { name: "Elementary Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/elementary/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Elementary Education | Grades K-6", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EED_BAE/", level: "bachelor", area: "Special Education" },
  { name: "Elementary Education | Grades K-6", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGEDU/EED_BAE_UFO/", level: "bachelor", area: "Special Education" },
  { name: "Emergency Services", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGCMN/FES_BSFE_UFO/", level: "bachelor", area: "" },
  { name: "Engineering | Exploring Engineering Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/UES_NOD/", level: "bachelor", area: "" },
  { name: "English", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/EH_BA/", level: "bachelor", area: "English" },
  { name: "English", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/english/english/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "English Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/english/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Entomology and Nematology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/ENY_BS/", level: "bachelor", area: "Entomology and Nematology" },
  { name: "Entomology and Nematology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/ENY_BS_UFO/", level: "bachelor", area: "Entomology and Nematology" },
  { name: "Entomology and Nematology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/entomology-nematology/entomology-nematology/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Entrepreneurship", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/finance-insurance-real-estate/entrepreneurship/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Environmental and Global Health (M.H.S. - One Health)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/environmental-global/environmental-global-health-mhs/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Master" },
  { name: "Environmental Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/EVE_BSEN/", level: "bachelor", area: "Environmental Engineering Sciences" },
  { name: "Environmental Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGNTR/EVS_BA_BS/", level: "bachelor", area: "Natural Resources and Environment, School of" },
  { name: "Epidemiology (Medicine)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/epidemiology/epidemiology/", level: "graduate", area: "College of Medicine", credential: "Doctor, Master" },
  { name: "Epidemiology (PHHP)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/epidemiology/epidemiology/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Family, Youth and Community Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/FYC_BS/", level: "bachelor", area: "Family, Youth and Community Sciences" },
  { name: "Family, Youth, and Community Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/family-youth-community/family-youth-community/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Master" },
  { name: "Finance", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/FIN_BSBA/", level: "bachelor", area: "Finance, Insurance and Real Estate" },
  { name: "Finance", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/finance-insurance-real-estate/finance/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Fire and Emergency Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/construction-management/fire-emergency-sciences/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Fisheries and Aquatic Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/forest-resources-conservation/fisheries-aquatic/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Food and Resource Economics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/FRE_BS/", level: "bachelor", area: "Food and Resource Economics" },
  { name: "Food and Resource Economics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/food-resource-economics/food-resource-economics/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Food Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/FOS_BS/", level: "bachelor", area: "Food Science and Human Nutrition" },
  { name: "Food Science", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/food-science-human-nutrition/food-science/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Food Science and Human Nutrition", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/food-science-human-nutrition/food-science-human-nutrition/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Master" },
  { name: "Foreign Languages and Literatures", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FLL_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Forest Resources and Conservation", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/FRC_BSF/", level: "bachelor", area: "Forest, Fisheries, and Geomatics Sciences, School of" },
  { name: "Forest Resources and Conservation", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/forest-resources-conservation/forest-resources-conservation/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "French and Francophone Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FFR_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "French and Francophone Studies", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/languages-literatures-cultures/french-francophone-studies/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Genetics and Genomics (CALS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/interdisciplinary-department/genetics-genomics/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Genetics and Genomics (CLAS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/interdisciplinary-department/genetics-genomics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Genetics and Genomics (Medicine)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/interdisciplinary-departments/genetics-genomics/", level: "graduate", area: "College of Medicine", credential: "Doctor, Master" },
  { name: "Geography", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/GPY_BA_BS/", level: "bachelor", area: "Geography" },
  { name: "Geography", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/GPY_UFO/", level: "bachelor", area: "Geography" },
  { name: "Geography", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/geography/geography/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Geology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/GLY_BA_BS/", level: "bachelor", area: "Geological Sciences" },
  { name: "Geology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/GLY_BA_UFO/", level: "bachelor", area: "Geological Sciences" },
  { name: "Geology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/geological/geology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Geomatics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/GEM_BSGE/", level: "bachelor", area: "Forest, Fisheries, and Geomatics Sciences, School of" },
  { name: "German", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FGR_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "German", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/languages-literatures-cultures/german/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Graphic Design", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/GRD_BFAG/", level: "bachelor", area: "Art + Art History" },
  { name: "Great Books and Ideas", url: "https://catalog.ufl.edu/UGRD/colleges-schools/hamilton/GBI_BA/", level: "bachelor", area: "Hamilton School" },
  { name: "Health Administration", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/services-research-management-policy/health-administration/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Master" },
  { name: "Health and Human Performance", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/health-human-performance/interdisciplinary-department/health-human-performance/", level: "graduate", area: "College of Health and Human Performance", credential: "Doctor" },
  { name: "Health Education and Behavior", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/HEB_BSHE/", level: "bachelor", area: "Health Education and Behavior" },
  { name: "Health Education and Behavior", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/health-human-performance/health-education-behavior/health-education-behavior/", level: "graduate", area: "College of Health and Human Performance", credential: "Master" },
  { name: "Health Education and Behavior | Community Health Promotion", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/HEB_BSHE_UFO/", level: "bachelor", area: "Health Education and Behavior" },
  { name: "Health Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGPBH/HES_BHS/", level: "bachelor", area: "Health Science" },
  { name: "Hebrew", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HBR_BA/", level: "bachelor", area: "Jewish Studies, Center for" },
  { name: "Higher Education Administration", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/higher-education-administration/", level: "graduate", area: "College of Education", credential: "Doctor" },
  { name: "Hispanic and Latin American Languages, Literatures and Linguistics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HLL_BA/", level: "bachelor", area: "Spanish and Portuguese Studies" },
  { name: "Historic Preservation", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/interdisciplinary-departments/historic-preservation/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "History", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HY_BA/", level: "bachelor", area: "History" },
  { name: "History", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/history/history/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Horticultural Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/horticultural/horticultural/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Industrial and Systems Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/ISE_BSIS/", level: "bachelor", area: "Industrial and Systems Engineering" },
  { name: "Industrialized Construction Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/ICE_BSICE/", level: "bachelor", area: "Civil and Coastal Engineering" },
  { name: "Information Systems", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/IST_BSBA/", level: "bachelor", area: "Information Systems and Operations Management" },
  { name: "Information Systems and Operations Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/information-systems-operations-management/information-systems-operations-management/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Integrated Sustainable Development", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/interdisciplinary-departments/integrated-sustainable-development/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Interdisciplinary Ecology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/natural-resources-environment/interdisciplinary-ecology/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Interdisciplinary Studies | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/IDS_BA_BS/", level: "bachelor", area: "" },
  { name: "Interdisciplinary Studies | Environmental Management in Agriculture and Natural Resources", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/IS_BS01/", level: "bachelor", area: "Soil, Water, and Ecosystem Sciences" },
  { name: "Interdisciplinary Studies | Environmental Management in Agriculture and Natural Resources", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/IS_BS01_UFO/", level: "bachelor", area: "Soil, Water, and Ecosystem Sciences" },
  { name: "Interior Design", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGDCP/IND_BDES/", level: "bachelor", area: "Interior Design" },
  { name: "Interior Design", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/interior-design/interior-design/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "International Business", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/management/international/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "International Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/INS_BA/", level: "bachelor", area: "" },
  { name: "Italian", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FIT_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Japanese", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FJA_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "Jewish Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/JST_BA/", level: "bachelor", area: "Jewish Studies, Center for" },
  { name: "Journalism", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/JM_BSJ/", level: "bachelor", area: "Journalism" },
  { name: "Journalism | Sports and Media", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/JM_BSJ01_UFO/", level: "bachelor", area: "Journalism" },
  { name: "Landscape Architecture", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/landscape-architecture/landscape-architecture/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Landscape Architecture | 4-Year Professional Program", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGDCP/LAE_BLAE/", level: "bachelor", area: "Landscape Architecture" },
  { name: "Latin", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/classics/latin/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Latin American Studies", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/center-latin-american-studies/latin-american-studies/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Linguistics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/LIN_BA/", level: "bachelor", area: "Linguistics" },
  { name: "Linguistics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/linguistics/linguistics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "M.E. Rinker, Sr. School of Construction Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/construction-management/", level: "graduate", area: "College of Design, Construction and Planning" },
  { name: "Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/MGT_BSBA/", level: "bachelor", area: "Management" },
  { name: "Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/management/management/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Marine Sciences | CALS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/MAS_BS/", level: "bachelor", area: "" },
  { name: "Marine Sciences | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/MAR_BS/", level: "bachelor", area: "" },
  { name: "Marketing", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGBUS/MKG_BSBA/", level: "bachelor", area: "Marketing" },
  { name: "Marriage and Family Counseling", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/marriage-family-counseling/", level: "graduate", area: "College of Education", credential: "Master, Specialist" },
  { name: "Mass Communication", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/journalism-communications/mass-communication/", level: "graduate", area: "College of Journalism and Communications", credential: "Doctor, Master" },
  { name: "Materials Science and Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/MSE_BSMS/", level: "bachelor", area: "Materials Science and Engineering" },
  { name: "Mathematics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/MAT_BA_BS/", level: "bachelor", area: "Mathematics" },
  { name: "Mathematics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/mathematics/mathematics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Mathematics Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/mathematics/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Mechanical Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/MCE_BSME/", level: "bachelor", area: "Mechanical & Aerospace Engineering" },
  { name: "Media Production, Management, and Technology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/TEL_BSTE/", level: "bachelor", area: "Media Production, Management, and Technology" },
  { name: "Media Production, Management, and Technology | Media Management and Technology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/TEL_BSTE_UFO/", level: "bachelor", area: "Media Production, Management, and Technology" },
  { name: "Medical Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/medicine/interdisciplinary-departments/medical/", level: "graduate", area: "College of Medicine", credential: "Doctor, Master" },
  { name: "Mental Health Counseling", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/mental-health-counseling/", level: "graduate", area: "College of Education", credential: "Master, Specialist" },
  { name: "Meteorology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/MET_BS/", level: "bachelor", area: "Geography" },
  { name: "Microbiology and Cell Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/MCB_BS_UFO/", level: "bachelor", area: "Microbiology & Cell Science" },
  { name: "Microbiology and Cell Science", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/microbiology-cell/microbiology-cell/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Microbiology and Cell Science | CALS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/MCB_BS/", level: "bachelor", area: "Microbiology & Cell Science" },
  { name: "Microbiology and Cell Science | CLAS", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/MCY_BS/", level: "bachelor", area: "Microbiology & Cell Science" },
  { name: "Museology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/art-history/museology/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Music", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/music/music/", level: "graduate", area: "College of the Arts", credential: "Doctor, Master" },
  { name: "Music | Bachelor of Arts", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/MUS_BA/", level: "bachelor", area: "Music, School of" },
  { name: "Music | Bachelor of Music", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/MUS_BMUS/", level: "bachelor", area: "Music, School of" },
  { name: "Music Business and Entrepreneurship", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/MBE_BS/", level: "bachelor", area: "Music, School of" },
  { name: "Music Education", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/MUE_BMUE/", level: "bachelor", area: "Music, School of" },
  { name: "Music Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/music/education/", level: "graduate", area: "College of the Arts", credential: "Doctor, Master" },
  { name: "Natural Resource Conservation", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/NRC_BSF/", level: "bachelor", area: "Wildlife Ecology and Conservation" },
  { name: "Nuclear Engineering", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGENG/NUE_BSNE/", level: "bachelor", area: "Materials Science and Engineering" },
  { name: "Nursing", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGNUR/NSG_BSN/", level: "bachelor", area: "Nursing" },
  { name: "Nursing | RN to BSN", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGNUR/NSG_BSN01_UFO/", level: "bachelor", area: "Nursing" },
  { name: "Nursing Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/nursing/nursing-sciences/", level: "graduate", area: "College of Nursing", credential: "Doctor" },
  { name: "Nutritional Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/NUT_BS/", level: "bachelor", area: "Food Science and Human Nutrition" },
  { name: "Nutritional Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/food-science-human-nutrition/nutritional/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Pharmaceutical Sciences (Cellular and Systems Pharmacology Department Concentrations)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/pharmacy/pharmacodynamics/pharmaceutical/", level: "graduate", area: "College of Pharmacy", credential: "Doctor, Master" },
  { name: "Pharmaceutical Sciences (Medicinal Chemistry Department Concentrations)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/pharmacy/medicinal-chemistry/pharmaceutical/", level: "graduate", area: "College of Pharmacy", credential: "Doctor, Master" },
  { name: "Pharmaceutical Sciences (Pharmaceutical Outcomes and Policy Department Concentrations)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/pharmacy/pharmaceutical-outcomes-policy/pharmaceutical/", level: "graduate", area: "College of Pharmacy", credential: "Doctor, Master" },
  { name: "Pharmaceutical Sciences (Pharmaceutics Department Concentrations)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/pharmacy/pharmaceutics/pharmaceutical/", level: "graduate", area: "College of Pharmacy", credential: "Doctor, Master" },
  { name: "Pharmaceutical Sciences (Pharmacotherapy and Translational Research Department Concentrations)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/pharmacy/pharmacotherapy-translational-research/pharmaceutical/", level: "graduate", area: "College of Pharmacy", credential: "Doctor, Master" },
  { name: "Pharmacy | Preprofessional", url: "https://catalog.ufl.edu/UGRD/academic-programs/UGPHM/PHA_NOD/", level: "bachelor", area: "Pharmacy" },
  { name: "Philosophy", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/PPY_BA/", level: "bachelor", area: "Philosophy" },
  { name: "Philosophy", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/philosophy/philosophy/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Philosophy, Politics, Economics, and Law", url: "https://catalog.ufl.edu/UGRD/colleges-schools/hamilton/PPE_BA/", level: "bachelor", area: "Hamilton School" },
  { name: "Physics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/PS_BA_BS/", level: "bachelor", area: "Physics" },
  { name: "Physics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/physics/physics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Plant Breeding", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/horticultural/plantbreeding/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Plant Medicine", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/entomology-nematology/plant-medicine/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Plant Molecular and Cellular Biology (CALS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/plant-molecular-cellular-biology/plant-molecular-cellular-biology/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Plant Molecular and Cellular Biology (CLAS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/plant-molecular-cellular-biology/plant-molecular-cellular-biology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor" },
  { name: "Plant Pathology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/plant-pathology/plant-pathology/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Plant Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/PLS_BS/", level: "bachelor", area: "Agronomy" },
  { name: "Political Science", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/POL_BA/", level: "bachelor", area: "Political Science" },
  { name: "Political Science", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/political-science/political-science/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Political Science - International Relations", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/political-science/political-science-international-relations/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Portuguese", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HLL_BA02/", level: "bachelor", area: "Spanish and Portuguese Studies" },
  { name: "Program Evaluation in Educational Environments", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/evaluation-educational-environments/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Psychology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/PSY_BS/", level: "bachelor", area: "Psychology" },
  { name: "Psychology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/PSY_BA_UFO/", level: "bachelor", area: "Psychology" },
  { name: "Psychology (CLAS)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/psychology/psychology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Psychology (Clinical and Health Psychology - PHHP)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/clinical-psychology/psychology/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Health", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGPBH/PBH_BPH/", level: "bachelor", area: "Public Health" },
  { name: "Public Health (M.P.H.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/interdisciplinary-departments/public-health-mph/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Health (Ph.D. - Environmental and Global Health)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/environmental-global/public-health-phd-environmental-global/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Health (Ph.D. - One Health)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/environmental-global/public-health-phd/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Health (Ph.D. - Social and Behavioral Sciences)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/behavioral-science-community/public-health/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Health (Ph.D.)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/interdisciplinary-departments/public-health-phd/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor, Master" },
  { name: "Public Relations", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/PR_BSPR/", level: "bachelor", area: "Public Relations" },
  { name: "Public Relations", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGJRC/PR_BSPR_UFO/", level: "bachelor", area: "Public Relations" },
  { name: "Reading Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/reading/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Real Estate", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/business/finance-insurance-real-estate/real-estate/", level: "graduate", area: "Warrington College of Business", credential: "Master" },
  { name: "Rehabilitation Science", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/public-health-professions/interdisciplinary-departments/rehabilitation-science/", level: "graduate", area: "College of Public Health and Health Professions", credential: "Doctor" },
  { name: "Religion", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/RLN_BA/", level: "bachelor", area: "Religion" },
  { name: "Research and Evaluation Methodology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/research-evaluation-methodology/", level: "graduate", area: "College of Education", credential: "Doctor, Master" },
  { name: "Romance Languages (Language, Literature and Culture)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/languages-literatures-cultures/romance-languages/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor" },
  { name: "Romance Languages (Spanish and Portuguese Studies)", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/spanish-portuguese-studies/romance-languages/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor" },
  { name: "Russian", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/FRU_BA/", level: "bachelor", area: "Languages, Literatures, and Cultures" },
  { name: "School Counseling and Guidance", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/counseling-guidance/", level: "graduate", area: "College of Education", credential: "Master, Specialist" },
  { name: "School of Architecture", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/architecture/", level: "graduate", area: "College of Design, Construction and Planning" },
  { name: "School of Forest, Fisheries, and Geomatics Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/forest-resources-conservation/", level: "graduate", area: "College of Agricultural and Life Sciences" },
  { name: "School of Natural Resources and Environment", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/natural-resources-environment/", level: "graduate", area: "College of Agricultural and Life Sciences" },
  { name: "School Psychology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/special-education-psychology-early-childhood-studies/psychology/", level: "graduate", area: "College of Education", credential: "Doctor, Master, Specialist" },
  { name: "Science Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/science/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Social Studies Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/teaching-learning/social-studies/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Sociology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/SOC_BA/", level: "bachelor", area: "Sociology and Criminology & Law" },
  { name: "Sociology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/SOC_BA_UFO/", level: "bachelor", area: "Sociology and Criminology & Law" },
  { name: "Sociology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/sociology-criminology-law/sociology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Soil, Water, and Ecosystem Sciences", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/SWS_BS/", level: "bachelor", area: "Soil, Water, and Ecosystem Sciences" },
  { name: "Soil, Water, and Ecosystem Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/soil-water/soil-water/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Soil, Water, and Ecosystem Sciences Department", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/soil-water/", level: "graduate", area: "College of Agricultural and Life Sciences" },
  { name: "Spanish", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HLL_BA01/", level: "bachelor", area: "Spanish and Portuguese Studies" },
  { name: "Spanish", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/spanish-portuguese-studies/spanish/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Spanish and Portuguese", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/HLL_BA/HLL_BA03/", level: "bachelor", area: "Spanish and Portuguese Studies" },
  { name: "Special Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/special-education-psychology-early-childhood-studies/special/", level: "graduate", area: "College of Education", credential: "Doctor, Master, Specialist" },
  { name: "Sport Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/SPM_BSSP/", level: "bachelor", area: "Sport Management" },
  { name: "Sport Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/SPM_BSSP_UFO/", level: "bachelor", area: "Sport Management" },
  { name: "Sport Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/health-human-performance/sport-management/sport/", level: "graduate", area: "College of Health and Human Performance", credential: "Master" },
  { name: "Statistics", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/STA_BA_BS/", level: "bachelor", area: "Statistics" },
  { name: "Statistics", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/statistics/statistics/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
  { name: "Student Personnel in Higher Education", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/education/human-development-organizational-studies/student-personnel-higher-education/", level: "graduate", area: "College of Education", credential: "Master" },
  { name: "Sustainability and the Built Environment", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGDCP/SUB_BSUB_BSUB01/", level: "bachelor", area: "Sustainability and the Built Environment" },
  { name: "Sustainability Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/SST_BA/", level: "bachelor", area: "Sustainability Studies" },
  { name: "Sustainable Construction", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/construction-management/sustainable/", level: "graduate", area: "College of Design, Construction and Planning" },
  { name: "Sustainable Development Practice", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/center-latin-american-studies/sustainable-development-practice/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Theatre", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/THE_BA/", level: "bachelor", area: "Theatre + Dance, School of" },
  { name: "Theatre", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/arts/theatre-dance/theatre/", level: "graduate", area: "College of the Arts", credential: "Master" },
  { name: "Theatre Performance", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/THF_BFA/", level: "bachelor", area: "Theatre + Dance, School of" },
  { name: "Theatre Production", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGART/TPR_BFA/", level: "bachelor", area: "Theatre + Dance, School of" },
  { name: "Tourism and Hospitality Management", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/health-human-performance/tourism-hospitality/tourism-recreation/", level: "graduate", area: "College of Health and Human Performance" },
  { name: "Tourism, Hospitality and Event Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/TRM_BSTM/", level: "bachelor", area: "Tourism, Hospitality and Event Management" },
  { name: "Tourism, Hospitality and Event Management", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGHHU/TRM_BSTM_UFO/", level: "bachelor", area: "Tourism, Hospitality and Event Management" },
  { name: "Urban and Regional Planning", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/design-construction-planning/urban-regional-planning/urban-regional-planning/", level: "graduate", area: "College of Design, Construction and Planning", credential: "Master" },
  { name: "Urban Sciences and Planning", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGDCP/USP_BUSP/", level: "bachelor", area: "" },
  { name: "Veterinary Medical Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/veterinary-medicine/interdisciplinary-department/veterinary-medical-sciences/", level: "graduate", area: "College of Veterinary Medicine", credential: "Doctor, Master" },
  { name: "War, Statecraft and Strategy", url: "https://catalog.ufl.edu/UGRD/colleges-schools/hamilton/WSS_BA/", level: "bachelor", area: "Hamilton School" },
  { name: "Wildlife Ecology and Conservation", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGAGL/WEC_BS/", level: "bachelor", area: "Wildlife Ecology and Conservation" },
  { name: "Wildlife Ecology and Conservation", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/wildlife-ecology-conservation/wildlife-ecology-conservation/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor, Master" },
  { name: "Women's Studies", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/WMS_BA/", level: "bachelor", area: "Gender, Sexuality, and Women’s Studies, Department of" },
  { name: "Women's Studies", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/gender-sexualities-womens-studies-research/womens-studies/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Master" },
  { name: "Youth Development and Family Sciences", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/agricultural-life-sciences/family-youth-community/youth-development-family/", level: "graduate", area: "College of Agricultural and Life Sciences", credential: "Doctor" },
  { name: "Zoology", url: "https://catalog.ufl.edu/UGRD/colleges-schools/UGLAS/ZLY_BS/", level: "bachelor", area: "Biology" },
  { name: "Zoology", url: "https://gradcatalog.ufl.edu/graduate/colleges-departments/liberal-arts-sciences/biology/zoology/", level: "graduate", area: "College of Liberal Arts and Sciences", credential: "Doctor, Master" },
];

// UF is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of same name.
export const ufCatalog = createProgramCatalog(UF_PROGRAMS, { preferred: "bachelor" });
