// University of South Florida degree catalog: program name -> official
// program page.
//
// HAND-VERIFIED, not scraped — no committed scraper exists for this school.
// catalog.usf.edu is Acalog behind AWS WAF Bot Control, which blocks both
// fetch() and curl (see HANDOFF.md §13) — the same platform and symptom as
// FAMU and FlPoly. Its data is real and clean (same shape as the state
// colleges' preview_program.php?catoid=X&poid=Y pattern), so — as with
// FlPoly — this was built by having a real browser navigate to USF's
// undergraduate and graduate "Majors (A-Z)" pages and reading the rendered
// DOM (2026-07-26). Real top-level navigation gets through the WAF even
// though fetch()/curl do not.
//
// Source (undergraduate, catoid=25):
//   content.php?catoid=25&navoid=4346  Programs (A-Z)
// Source (graduate, catoid=28):
//   content.php?catoid=28&navoid=5315  Majors (A-Z)
//
// Minors, certificates, ROTC tracks, and "Exploratory Curriculum" (undeclared)
// entries were excluded — none of them are a real degree pathway on their
// own. If USF changes its catalog, re-verify by hand — a plain scraper
// cannot reach this site.
//
// Programs: 428 (243 bachelor, 185 graduate)
//
// USF is a four-year university (like FIU/UCF/UF/FGCU/UWF/NCF/UNF/FlPoly), so
// pathways start at the bachelor's rather than an associate degree. Every
// entry's own credential comes straight from USF's A-Z program listings.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const USF_PROGRAMS: SchoolProgram[] = [
  { name: "Accountancy and Analytics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13161", level: "bachelor", credential: "B.S." },
  { name: "Accountancy and Analytics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16081", level: "graduate", credential: "M.S.A.A." },
  { name: "Advertising", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13773", level: "bachelor", credential: "B.S." },
  { name: "Advertising", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16010", level: "graduate", credential: "M.S." },
  { name: "Aerospace Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13987", level: "bachelor", credential: "B.S.A.E." },
  { name: "Aerospace Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16255", level: "graduate", credential: "M.S.A.E." },
  { name: "Aerospace Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16256", level: "graduate", credential: "Ph.D." },
  { name: "Africana Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12931", level: "bachelor", credential: "B.A." },
  { name: "Aging Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16066", level: "graduate", credential: "Ph.D." },
  { name: "AI and Learning Design", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17012", level: "graduate", credential: "Ed.D." },
  { name: "Anthropology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12932", level: "bachelor", credential: "B.A." },
  { name: "Applied Anthropology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=15963", level: "graduate", credential: "M.A." },
  { name: "Applied Anthropology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16019", level: "graduate", credential: "Ph.D." },
  { name: "Applied Behavior Analysis", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16067", level: "graduate", credential: "M.A." },
  { name: "Applied Behavior Analysis", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16068", level: "graduate", credential: "M.S." },
  { name: "Applied Behavior Analysis", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16069", level: "graduate", credential: "Ph.D." },
  { name: "Applied Mathematics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16213", level: "graduate", credential: "M.A." },
  { name: "Applied Science, Aging Sciences Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13102", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Applied Behavior Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13741", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Behavioral Healthcare Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13103", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Criminal Justice Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13104", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Environmental Policy Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13105", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Hospitality Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13742", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Information Studies: Information Architecture Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13106", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Leadership Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13171", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Public Health Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13107", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Public Service and Leadership Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13108", level: "bachelor", credential: "B.S.A.S." },
  { name: "Applied Science, Urban Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13109", level: "bachelor", credential: "B.S.A.S." },
  { name: "Architecture", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=17014", level: "bachelor", credential: "B.Des." },
  { name: "Architecture", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16145", level: "graduate", credential: "M.Arch." },
  { name: "Art", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16146", level: "graduate", credential: "M.F.A." },
  { name: "Art History", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13085", level: "bachelor", credential: "B.A." },
  { name: "Art History", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16147", level: "graduate", credential: "M.A." },
  { name: "Artificial Intelligence", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16257", level: "graduate", credential: "M.S.A.I." },
  { name: "Artificial Intelligence (AI)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13990", level: "bachelor", credential: "B.S.A.I." },
  { name: "Artificial Intelligence (AI) and Business Analytics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13761", level: "bachelor", credential: "B.S." },
  { name: "Artificial Intelligence in Business and Digital Transformation", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17013", level: "graduate", credential: "M.S." },
  { name: "Artificial Intelligence in Business and Enterprise Integration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16085", level: "graduate", credential: "M.S." },
  { name: "ASL Interpreting", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13256", level: "bachelor", credential: "B.A." },
  { name: "Athletic Training", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16113", level: "graduate", credential: "M.S." },
  { name: "Audiology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16070", level: "graduate", credential: "Au.D." },
  { name: "Behavioral and Community Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16071", level: "graduate", credential: "Ph.D." },
  { name: "Behavioral Healthcare, Applied Behavior Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13027", level: "bachelor", credential: "B.S." },
  { name: "Behavioral Healthcare, Behavioral Health Across the Lifespan Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13257", level: "bachelor", credential: "B.S." },
  { name: "Behavioral Healthcare, Children's Behavioral Healthcare Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13253", level: "bachelor", credential: "B.S." },
  { name: "Bioinformatics and Computational Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16114", level: "graduate", credential: "M.S.B.C.B." },
  { name: "Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13236", level: "bachelor", credential: "B.S." },
  { name: "Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16020", level: "graduate", credential: "M.S." },
  { name: "Biology, Animal Biology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13149", level: "bachelor", credential: "B.S." },
  { name: "Biology, Ecology and Evolution Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13150", level: "bachelor", credential: "B.S." },
  { name: "Biology, Medical Biology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13151", level: "bachelor", credential: "B.S." },
  { name: "Biology, Plant Biology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13152", level: "bachelor", credential: "B.S." },
  { name: "Biomedical Anthropology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13260", level: "bachelor", credential: "B.S." },
  { name: "Biomedical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13131", level: "bachelor", credential: "B.S.B.E." },
  { name: "Biomedical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16119", level: "graduate", credential: "M.S.B.E." },
  { name: "Biomedical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16120", level: "graduate", credential: "Ph.D." },
  { name: "Biomedical Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12923", level: "bachelor", credential: "B.S." },
  { name: "Biotechnology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16118", level: "graduate", credential: "M.S.B." },
  { name: "Business Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16083", level: "graduate", credential: "D.B.A." },
  { name: "Business Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16082", level: "graduate", credential: "M.B.A." },
  { name: "Business Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16084", level: "graduate", credential: "Ph.D." },
  { name: "Business Analytics and Information Systems", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13132", level: "bachelor", credential: "B.S." },
  { name: "Business Analytics and Information Systems, Cybersecurity Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13233", level: "bachelor", credential: "B.S." },
  { name: "Cancer Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16021", level: "graduate", credential: "Ph.D." },
  { name: "Cancer Chemical Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16022", level: "graduate", credential: "Ph.D." },
  { name: "Cancer Immunology and Immunotherapy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16023", level: "graduate", credential: "Ph.D." },
  { name: "Career and Technical Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16091", level: "graduate", credential: "M.A." },
  { name: "Cell and Molecular Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12924", level: "bachelor", credential: "B.S." },
  { name: "Cell and Molecular Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17018", level: "graduate", credential: "M.S." },
  { name: "Cell and Molecular Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=15965", level: "graduate", credential: "Ph.D." },
  { name: "Chemical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13064", level: "bachelor", credential: "B.S.C.H." },
  { name: "Chemical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16121", level: "graduate", credential: "M.S.Ch." },
  { name: "Chemical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16122", level: "graduate", credential: "Ph.D." },
  { name: "Chemistry", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12933", level: "bachelor", credential: "B.A." },
  { name: "Chemistry", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12935", level: "bachelor", credential: "B.S." },
  { name: "Chemistry", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16024", level: "graduate", credential: "M.A." },
  { name: "Chemistry", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16025", level: "graduate", credential: "M.S." },
  { name: "Chemistry", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16026", level: "graduate", credential: "Ph.D." },
  { name: "Chemistry, Biochemistry/Biotechnology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12934", level: "bachelor", credential: "B.A." },
  { name: "Child and Adolescent Behavioral Health", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16072", level: "graduate", credential: "M.S." },
  { name: "Civil Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13065", level: "bachelor", credential: "B.S.C.E." },
  { name: "Civil Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16123", level: "graduate", credential: "M.S.C.E." },
  { name: "Civil Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16124", level: "graduate", credential: "Ph.D." },
  { name: "Clinical Rehabilitation and Mental Health Counseling", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16077", level: "graduate", credential: "M.A." },
  { name: "Cognitive Science", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16989", level: "bachelor", credential: "B.S." },
  { name: "College Student Affairs", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17019", level: "graduate", credential: "M.Ed." },
  { name: "Communication", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12936", level: "bachelor", credential: "B.A." },
  { name: "Communication", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16027", level: "graduate", credential: "M.A." },
  { name: "Communication", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16028", level: "graduate", credential: "Ph.D." },
  { name: "Communication Sciences and Disorders", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16073", level: "graduate", credential: "Ph.D." },
  { name: "Computer Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13066", level: "bachelor", credential: "B.S.C.P." },
  { name: "Computer Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16125", level: "graduate", credential: "M.S.C.P." },
  { name: "Computer Engineering Systems", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16992", level: "bachelor", credential: "B.S.Cp.E." },
  { name: "Computer Engineering Systems", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17020", level: "graduate", credential: "M.S.Cp.E." },
  { name: "Computer Science", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13067", level: "bachelor", credential: "B.S.C.S." },
  { name: "Computer Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16126", level: "graduate", credential: "M.S.C.S." },
  { name: "Computer Science and Business, Accountancy and Analytics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14015", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Business, Business Analytics and Information Systems Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16474", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Business, Digital Marketing and Analytics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16475", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Business, Fintech Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16476", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Business, Supply Chain Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16477", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Criminology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14013", level: "bachelor", credential: "B.S." },
  { name: "Computer Science and Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16995", level: "bachelor", credential: "B.S.C.S.E." },
  { name: "Computer Science and Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17021", level: "graduate", credential: "M.S.C.S.E." },
  { name: "Computer Science and Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16127", level: "graduate", credential: "Ph.D." },
  { name: "Computer Science and Interdisciplinary Social Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14014", level: "bachelor", credential: "B.S." },
  { name: "Computer Science Education (K-12)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=17026", level: "bachelor", credential: "B.S." },
  { name: "Conservation Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16207", level: "graduate", credential: "M.S." },
  { name: "Counselor Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16092", level: "graduate", credential: "M.A." },
  { name: "Counselor Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16260", level: "graduate", credential: "Ph.D." },
  { name: "Creative Writing", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16029", level: "graduate", credential: "M.F.A." },
  { name: "Criminal Justice", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16201", level: "graduate", credential: "M.A." },
  { name: "Criminology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13028", level: "bachelor", credential: "B.A." },
  { name: "Criminology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16074", level: "graduate", credential: "M.A." },
  { name: "Criminology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16075", level: "graduate", credential: "Ph.D." },
  { name: "Criminology, Cybercrime Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13261", level: "bachelor", credential: "B.A." },
  { name: "Curriculum and Instruction", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16009", level: "graduate", credential: "Ed.S." },
  { name: "Curriculum and Instruction", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16156", level: "graduate", credential: "M.Ed." },
  { name: "Curriculum and Instruction", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16011", level: "graduate", credential: "Ph.D." },
  { name: "Cybercrime", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16109", level: "graduate", credential: "M.S." },
  { name: "Cybersecurity", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13068", level: "bachelor", credential: "B.S.C.Y.S." },
  { name: "Cybersecurity", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16224", level: "graduate", credential: "M.S.C.Y.S." },
  { name: "Cybersecurity Intelligence and Information Security", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16215", level: "graduate", credential: "M.S." },
  { name: "Dance, Ballet Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13087", level: "bachelor", credential: "B.F.A." },
  { name: "Dance, Contemporary Dance Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13088", level: "bachelor", credential: "B.F.A." },
  { name: "Dance, Dance Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13086", level: "bachelor", credential: "B.A." },
  { name: "Data Intelligence", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16236", level: "graduate", credential: "M.S.D.I." },
  { name: "Data Science and AI", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16199", level: "graduate", credential: "Ph.D." },
  { name: "Design", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14007", level: "bachelor", credential: "B.S." },
  { name: "Digital Communication and Multimedia Journalism", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13205", level: "bachelor", credential: "B.A." },
  { name: "Digital Journalism and Design", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16205", level: "graduate", credential: "M.A." },
  { name: "Early Childhood Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13052", level: "bachelor", credential: "B.S." },
  { name: "Econometrics and Quantitative Economics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12991", level: "bachelor", credential: "B.S." },
  { name: "Economics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12930", level: "bachelor", credential: "B.A." },
  { name: "Economics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16030", level: "graduate", credential: "M.A." },
  { name: "Economics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16031", level: "graduate", credential: "Ph.D." },
  { name: "Educational Leadership", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16102", level: "graduate", credential: "Ed.S." },
  { name: "Educational Leadership", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16006", level: "graduate", credential: "M.Ed." },
  { name: "Educational Leadership", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16103", level: "graduate", credential: "Ph.D." },
  { name: "Educational Program Development", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16093", level: "graduate", credential: "Ed.D." },
  { name: "Educational Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16211", level: "graduate", credential: "M.A." },
  { name: "Electrical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13069", level: "bachelor", credential: "B.S.E.E." },
  { name: "Electrical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16128", level: "graduate", credential: "M.S.E.E." },
  { name: "Electrical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16129", level: "graduate", credential: "Ph.D." },
  { name: "Elementary Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13053", level: "bachelor", credential: "B.S." },
  { name: "Elementary Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16104", level: "graduate", credential: "M.A.T." },
  { name: "Engineering Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16130", level: "graduate", credential: "M.S.E.M." },
  { name: "English", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16032", level: "graduate", credential: "M.A." },
  { name: "English", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16033", level: "graduate", credential: "Ph.D." },
  { name: "English Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13054", level: "bachelor", credential: "B.S." },
  { name: "English, Creative Writing Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12921", level: "bachelor", credential: "B.A." },
  { name: "English, Literary Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12922", level: "bachelor", credential: "B.A." },
  { name: "Entrepreneurship", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13146", level: "bachelor", credential: "B.S." },
  { name: "Entrepreneurship in Applied Technologies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16008", level: "graduate", credential: "M.S." },
  { name: "Environmental Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13251", level: "bachelor", credential: "B.S.E.V." },
  { name: "Environmental Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16131", level: "graduate", credential: "M.S.E.V." },
  { name: "Environmental Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16132", level: "graduate", credential: "Ph.D." },
  { name: "Environmental Science and Policy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16034", level: "graduate", credential: "M.S." },
  { name: "Environmental Science and Policy, Environmental Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13154", level: "bachelor", credential: "B.S." },
  { name: "Environmental Science and Policy, Environmental Policy and Sustainability Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13155", level: "bachelor", credential: "B.S." },
  { name: "Environmental Science and Policy, Environmental Science Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13153", level: "bachelor", credential: "B.S." },
  { name: "Exceptional Student Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16111", level: "graduate", credential: "M.A." },
  { name: "Exceptional Student Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13055", level: "bachelor", credential: "B.S." },
  { name: "Exceptional Student Education (ESOL and Reading Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16112", level: "graduate", credential: "M.A.T." },
  { name: "Executive", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16086", level: "graduate", credential: "M.B.A." },
  { name: "Exercise Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16095", level: "graduate", credential: "M.S." },
  { name: "Exercise Science and Kinesiology, Exercise and Wellness Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13958", level: "bachelor", credential: "B.S." },
  { name: "Exercise Science and Kinesiology, Sports Nutrition Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13960", level: "bachelor", credential: "B.S." },
  { name: "Exercise Science and Kinesiology, Strength and Conditioning Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13962", level: "bachelor", credential: "B.S." },
  { name: "Finance", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13133", level: "bachelor", credential: "B.S." },
  { name: "Finance, Corporate Finance Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13038", level: "bachelor", credential: "B.S." },
  { name: "Finance, FinTech Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13746", level: "bachelor", credential: "B.S." },
  { name: "Finance, Investment Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13139", level: "bachelor", credential: "B.S." },
  { name: "Finance, Real Estate Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13039", level: "bachelor", credential: "B.S." },
  { name: "Financial Analytics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16087", level: "graduate", credential: "M.S." },
  { name: "Fintech", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=17010", level: "bachelor", credential: "B.S." },
  { name: "Fintech", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16258", level: "graduate", credential: "M.S." },
  { name: "General Business Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13163", level: "bachelor", credential: "B.S." },
  { name: "General Studies, Aging Sciences Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13110", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Applied Behavior Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13743", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Behavioral Healthcare Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13111", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Business Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13112", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Criminal Justice Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13113", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Educational Foundations Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13114", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Environmental Policy Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13115", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Hospitality Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13744", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Information Studies: Information Architecture Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13116", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Leadership Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13170", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Public Health Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13118", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Public Service and Leadership Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13117", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Urban Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13119", level: "bachelor", credential: "B.G.S." },
  { name: "General Studies, Women's, Gender, and Sexuality Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13120", level: "bachelor", credential: "B.G.S." },
  { name: "Geography", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16036", level: "graduate", credential: "M.A." },
  { name: "Geography and Environmental Science and Policy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16037", level: "graduate", credential: "Ph.D." },
  { name: "Geography and Geographic Information Systems, Geographic Information Systems Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13159", level: "bachelor", credential: "B.A." },
  { name: "Geography and Geographic Information Systems, Geography Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13158", level: "bachelor", credential: "B.A." },
  { name: "Geography and Geographic Information Systems, Society and Environment Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13259", level: "bachelor", credential: "B.A." },
  { name: "Geology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12938", level: "bachelor", credential: "B.A." },
  { name: "Geology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12937", level: "bachelor", credential: "B.S." },
  { name: "Geology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16038", level: "graduate", credential: "M.S." },
  { name: "Geology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16039", level: "graduate", credential: "Ph.D." },
  { name: "Gerontology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16076", level: "graduate", credential: "M.A." },
  { name: "Global Business, Business Analytics and Information Systems Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13040", level: "bachelor", credential: "B.A." },
  { name: "Global Business, Finance Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13041", level: "bachelor", credential: "B.A." },
  { name: "Global Business, Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13042", level: "bachelor", credential: "B.A." },
  { name: "Global Business, Marketing Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13043", level: "bachelor", credential: "B.A." },
  { name: "Global Sustainability", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16007", level: "graduate", credential: "M.A." },
  { name: "Global Sustainability", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16214", level: "graduate", credential: "M.S." },
  { name: "Graphic Arts, Graphic Design Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13210", level: "bachelor", credential: "B.F.A." },
  { name: "Graphic Arts, Illustration Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13211", level: "bachelor", credential: "B.F.A." },
  { name: "Health Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16105", level: "graduate", credential: "M.H.A." },
  { name: "Health and Nutrition Science", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14003", level: "bachelor", credential: "B.S." },
  { name: "Health and Physical Rehabilitation Science", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13982", level: "bachelor", credential: "B.S." },
  { name: "Health Care Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13029", level: "bachelor", credential: "B.S." },
  { name: "Health Informatics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16115", level: "graduate", credential: "M.S.H.I." },
  { name: "Health Sciences, Biological Health Sciences Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12941", level: "bachelor", credential: "B.S." },
  { name: "Health Sciences, Health Care Administration Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13164", level: "bachelor", credential: "B.S." },
  { name: "Health Sciences, Health Information Technology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12944", level: "bachelor", credential: "B.S." },
  { name: "Health Sciences, Healthcare Simulation Science Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13979", level: "bachelor", credential: "B.S." },
  { name: "Health Sciences, Social and Behavioral Health Sciences Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12943", level: "bachelor", credential: "B.S." },
  { name: "Higher Education Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17022", level: "graduate", credential: "M.Ed." },
  { name: "Higher Education Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16249", level: "graduate", credential: "Ph.D." },
  { name: "History", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12948", level: "bachelor", credential: "B.A." },
  { name: "History", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16041", level: "graduate", credential: "M.A." },
  { name: "History", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16042", level: "graduate", credential: "Ph.D." },
  { name: "Hospitality Management", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13144", level: "bachelor", credential: "B.S." },
  { name: "Hospitality Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16202", level: "graduate", credential: "M.S." },
  { name: "Humanities and Cultural Studies, American Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12949", level: "bachelor", credential: "B.A." },
  { name: "Humanities and Cultural Studies, Film and New Media Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12950", level: "bachelor", credential: "B.A." },
  { name: "Humanities and Cultural Studies, Humanities Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12951", level: "bachelor", credential: "B.A." },
  { name: "Industrial Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13070", level: "bachelor", credential: "B.S.I.E." },
  { name: "Industrial Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16133", level: "graduate", credential: "M.S.I.E." },
  { name: "Industrial Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16134", level: "graduate", credential: "Ph.D." },
  { name: "Informal and Community-Based/K-6 Elementary Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13140", level: "bachelor", credential: "B.S." },
  { name: "Information Assurance and Cybersecurity Management", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13222", level: "bachelor", credential: "B.S." },
  { name: "Information Assurance and Cybersecurity Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16225", level: "graduate", credential: "M.S." },
  { name: "Information Science, Data Science and Analytics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13241", level: "bachelor", credential: "B.S." },
  { name: "Information Science, Health Informatics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13242", level: "bachelor", credential: "B.S." },
  { name: "Information Science, Information Security Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13244", level: "bachelor", credential: "B.S." },
  { name: "Information Science, Intelligence Analysis Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13243", level: "bachelor", credential: "B.S." },
  { name: "Information Science, Web Development Technologies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13245", level: "bachelor", credential: "B.S." },
  { name: "Information Technology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13071", level: "bachelor", credential: "B.S.I.T." },
  { name: "Integrated Mathematical Oncology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16158", level: "graduate", credential: "Ph.D." },
  { name: "Integrated Public Relations and Advertising, Advertising Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13764", level: "bachelor", credential: "B.S." },
  { name: "Integrated Public Relations and Advertising, Public Relations Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13765", level: "bachelor", credential: "B.S." },
  { name: "Integrative Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16043", level: "graduate", credential: "Ph.D." },
  { name: "Intelligence Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16044", level: "graduate", credential: "M.S." },
  { name: "Interdisciplinary Natural Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12952", level: "bachelor", credential: "B.S." },
  { name: "Interdisciplinary Social Sciences, Africana Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12953", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Aging Sciences Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12954", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, American Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12955", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Anthropology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12956", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Behavioral Healthcare Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12969", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Communication Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12976", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Communication Sciences and Disorders Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12959", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Criminology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12957", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Deaf Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12960", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Economics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12961", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Environmental Science and Policy Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12962", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Geography Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12963", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Government and Global Affairs Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13254", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, History Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12965", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Humanities Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12964", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Information Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12966", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Integrated Community Research Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13147", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, International Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12967", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Latin American, Caribbean, and Latino Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12968", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Mass Communications Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12958", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Political Science Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12971", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Psychology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12972", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Public Administration Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12970", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Public Health Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12973", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Religious Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12974", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Social Relations and Policy Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13148", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Sociology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12975", level: "bachelor", credential: "B.A." },
  { name: "Interdisciplinary Social Sciences, Women's, Gender, and Sexuality Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12977", level: "bachelor", credential: "B.A." },
  { name: "International Affairs", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16057", level: "graduate", credential: "M.A." },
  { name: "International Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12978", level: "bachelor", credential: "B.A." },
  { name: "K-6 Elementary and K-12 Exceptional Student Education (w/ Reading and ESOL Endorsements)", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13175", level: "bachelor", credential: "B.S." },
  { name: "Language, Speech, and Hearing Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13169", level: "bachelor", credential: "B.A." },
  { name: "Latin American, Caribbean, and Latino Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16045", level: "graduate", credential: "M.A." },
  { name: "Learning Design and Technology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16096", level: "graduate", credential: "M.S." },
  { name: "Liberal Arts", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16046", level: "graduate", credential: "M.A." },
  { name: "Library and Information Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16018", level: "graduate", credential: "M.A." },
  { name: "Linguistics and Applied Language Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16048", level: "graduate", credential: "Ph.D." },
  { name: "Linguistics: English as a Second Language", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16047", level: "graduate", credential: "M.A." },
  { name: "Management", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13134", level: "bachelor", credential: "B.S." },
  { name: "Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16088", level: "graduate", credential: "M.S." },
  { name: "Management, Aging Services Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13172", level: "bachelor", credential: "B.S." },
  { name: "Management, Human Resources Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13044", level: "bachelor", credential: "B.S." },
  { name: "Management, Organizational Leadership Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13262", level: "bachelor", credential: "B.S." },
  { name: "Management, Project Management Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13045", level: "bachelor", credential: "B.S." },
  { name: "Marine Biology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13239", level: "bachelor", credential: "B.S." },
  { name: "Marine Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16138", level: "graduate", credential: "M.S." },
  { name: "Marine Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16139", level: "graduate", credential: "Ph.D." },
  { name: "Marketing", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16089", level: "graduate", credential: "M.S.M." },
  { name: "Marketing, Digital Marketing and Analytics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13948", level: "bachelor", credential: "B.S." },
  { name: "Marketing, Market Development Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13946", level: "bachelor", credential: "B.S." },
  { name: "Marriage and Family Therapy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16197", level: "graduate", credential: "M.S." },
  { name: "Mass Communications", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16049", level: "graduate", credential: "M.A." },
  { name: "Mass Communications, News and Content Creation Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12979", level: "bachelor", credential: "B.A." },
  { name: "Mass Communications, Video and Documentary Production Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12980", level: "bachelor", credential: "B.A." },
  { name: "Materials Science and Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16135", level: "graduate", credential: "M.S.M.S.E." },
  { name: "Mathematics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16050", level: "graduate", credential: "M.A." },
  { name: "Mathematics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16051", level: "graduate", credential: "Ph.D." },
  { name: "Mathematics Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13246", level: "bachelor", credential: "B.S." },
  { name: "Mathematics Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16097", level: "graduate", credential: "M.A.T." },
  { name: "Mathematics Education, Middle School Mathematics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13056", level: "bachelor", credential: "B.S." },
  { name: "Mathematics, Applied/Computational Mathematics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12981", level: "bachelor", credential: "B.A." },
  { name: "Mathematics, General Mathematics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12982", level: "bachelor", credential: "B.A." },
  { name: "Mathematics, Pure Mathematics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12928", level: "bachelor", credential: "B.A." },
  { name: "Mathematics: Computational and Applied, Actuarial Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13237", level: "bachelor", credential: "B.S." },
  { name: "Mathematics: Computational and Applied, Discrete Mathematics and Cryptography Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13238", level: "bachelor", credential: "B.S." },
  { name: "Mechanical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13072", level: "bachelor", credential: "B.S.M.E." },
  { name: "Mechanical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16136", level: "graduate", credential: "M.S.M.E." },
  { name: "Mechanical Engineering", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16137", level: "graduate", credential: "Ph.D." },
  { name: "Medical Laboratory Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13740", level: "bachelor", credential: "B.S." },
  { name: "Medical Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16140", level: "graduate", credential: "M.S.M.S." },
  { name: "Medical Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16141", level: "graduate", credential: "Ph.D." },
  { name: "Medicine", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16142", level: "graduate", credential: "M.D." },
  { name: "Microbiology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12984", level: "bachelor", credential: "B.S." },
  { name: "Microbiology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16052", level: "graduate", credential: "M.S." },
  { name: "Music", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16149", level: "graduate", credential: "M.M." },
  { name: "Music", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16150", level: "graduate", credential: "Ph.D." },
  { name: "Music Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13089", level: "bachelor", credential: "B.S." },
  { name: "Music Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16148", level: "graduate", credential: "M.A." },
  { name: "Music Performance, Acoustic & Electronic Composition Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13092", level: "bachelor", credential: "B.M." },
  { name: "Music Performance, Contemporary Commercial Music Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13729", level: "bachelor", credential: "B.M." },
  { name: "Music Performance, Jazz Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13090", level: "bachelor", credential: "B.M." },
  { name: "Music Performance, Performance Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13091", level: "bachelor", credential: "B.M." },
  { name: "Music Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13093", level: "bachelor", credential: "B.A." },
  { name: "Musical Theatre", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13770", level: "bachelor", credential: "B.A." },
  { name: "Nurse Anesthesiology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16116", level: "graduate", credential: "D.N.P." },
  { name: "Nursing", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16155", level: "graduate", credential: "D.N.P." },
  { name: "Nursing", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16117", level: "graduate", credential: "M.S.N." },
  { name: "Nursing Science", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16154", level: "graduate", credential: "Ph.D." },
  { name: "Nursing: Accelerated Second Bachelor's Degree Pathway", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13077", level: "bachelor", credential: "B.S.N." },
  { name: "Nursing: Upper Division Pathway", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13078", level: "bachelor", credential: "B.S.N." },
  { name: "Nursing: V-CARE", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13076", level: "bachelor", credential: "B.S.N." },
  { name: "Personal Financial Planning", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13240", level: "bachelor", credential: "B.S." },
  { name: "Pharmaceutical Nanotechnology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16143", level: "graduate", credential: "M.S." },
  { name: "Pharmacy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16106", level: "graduate", credential: "Pharm.D." },
  { name: "Philosophy", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12985", level: "bachelor", credential: "B.A." },
  { name: "Philosophy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16053", level: "graduate", credential: "M.A." },
  { name: "Philosophy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16054", level: "graduate", credential: "Ph.D." },
  { name: "Physical Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13135", level: "bachelor", credential: "B.A." },
  { name: "Physical Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13136", level: "bachelor", credential: "B.S." },
  { name: "Physical Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16012", level: "graduate", credential: "M.A." },
  { name: "Physical Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12986", level: "bachelor", credential: "B.A." },
  { name: "Physical Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12987", level: "bachelor", credential: "B.S." },
  { name: "Physical Therapy", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16107", level: "graduate", credential: "D.P.T." },
  { name: "Physician Assistant Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16108", level: "graduate", credential: "M.P.A.S." },
  { name: "Physics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12989", level: "bachelor", credential: "B.A." },
  { name: "Physics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12988", level: "bachelor", credential: "B.S." },
  { name: "Physics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16055", level: "graduate", credential: "M.S." },
  { name: "Physics (Applied Physics)", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16056", level: "graduate", credential: "Ph.D." },
  { name: "Political Science", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12990", level: "bachelor", credential: "B.A." },
  { name: "Politics and International Affairs", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16040", level: "graduate", credential: "Ph.D." },
  { name: "Professional and Technical Communication", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13201", level: "bachelor", credential: "B.A." },
  { name: "Psychological Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16204", level: "graduate", credential: "M.A." },
  { name: "Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13209", level: "bachelor", credential: "B.A." },
  { name: "Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16152", level: "graduate", credential: "M.A." },
  { name: "Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16153", level: "graduate", credential: "Ph.D." },
  { name: "Psychology, Advanced Research Experience in Psychology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13157", level: "bachelor", credential: "B.A." },
  { name: "Psychology, Diversity Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13156", level: "bachelor", credential: "B.A." },
  { name: "Public Administration", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16058", level: "graduate", credential: "M.P.A." },
  { name: "Public Health", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13079", level: "bachelor", credential: "B.S." },
  { name: "Public Health", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16099", level: "graduate", credential: "Dr.P.H." },
  { name: "Public Health", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16144", level: "graduate", credential: "M.P.H." },
  { name: "Public Health", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16101", level: "graduate", credential: "M.S.P.H." },
  { name: "Public Health", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16100", level: "graduate", credential: "Ph.D." },
  { name: "Reading Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16013", level: "graduate", credential: "M.A." },
  { name: "Rehabilitation Counseling and Disability Sciences", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16226", level: "graduate", credential: "M.A." },
  { name: "Religion and Health", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=14012", level: "bachelor", credential: "B.S." },
  { name: "Religious Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12992", level: "bachelor", credential: "B.A." },
  { name: "Religious Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16059", level: "graduate", credential: "M.A." },
  { name: "Risk Management and Insurance", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13145", level: "bachelor", credential: "B.S." },
  { name: "School Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16250", level: "graduate", credential: "Ed.S." },
  { name: "School Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16015", level: "graduate", credential: "M.A." },
  { name: "School Psychology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16016", level: "graduate", credential: "Ph.D." },
  { name: "Science Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16098", level: "graduate", credential: "M.A.T." },
  { name: "Science Education, Biology Education Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13057", level: "bachelor", credential: "B.S." },
  { name: "Science Education, Chemistry Education Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13058", level: "bachelor", credential: "B.S." },
  { name: "Science Education, Physics Education Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13059", level: "bachelor", credential: "B.S." },
  { name: "Secondary English Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16203", level: "graduate", credential: "M.A." },
  { name: "Secondary English Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=17017", level: "graduate", credential: "M.A.T." },
  { name: "Social Science Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13060", level: "bachelor", credential: "B.S." },
  { name: "Social Science Education", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16014", level: "graduate", credential: "M.A.T." },
  { name: "Social Work", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13030", level: "bachelor", credential: "B.S.W." },
  { name: "Social Work", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16078", level: "graduate", credential: "M.S.W." },
  { name: "Social Work", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16079", level: "graduate", credential: "Ph.D." },
  { name: "Sociology", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13137", level: "bachelor", credential: "B.A." },
  { name: "Sociology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16060", level: "graduate", credential: "M.A." },
  { name: "Sociology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16061", level: "graduate", credential: "Ph.D." },
  { name: "Sociology, Identity and Community Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12993", level: "bachelor", credential: "B.A." },
  { name: "Sociology, Inequality and Social Justice Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12994", level: "bachelor", credential: "B.A." },
  { name: "Spanish", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16062", level: "graduate", credential: "M.A." },
  { name: "Speech-Language Pathology", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16080", level: "graduate", credential: "M.S." },
  { name: "Sport and Entertainment Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16090", level: "graduate", credential: "M.S." },
  { name: "Statistics", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12995", level: "bachelor", credential: "B.A." },
  { name: "Statistics", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16063", level: "graduate", credential: "M.A." },
  { name: "Studies in Education", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=16990", level: "bachelor", credential: "B.S." },
  { name: "Studio Art", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13094", level: "bachelor", credential: "B.A." },
  { name: "Studio Art", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13095", level: "bachelor", credential: "B.F.A." },
  { name: "Studio Art, Animation and Digital Modeling Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13732", level: "bachelor", credential: "B.F.A." },
  { name: "Supply Chain Management", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13138", level: "bachelor", credential: "B.S." },
  { name: "Supply Chain Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16196", level: "graduate", credential: "M.S." },
  { name: "Sustainability Management", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16259", level: "graduate", credential: "M.S." },
  { name: "Sustainability Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13141", level: "bachelor", credential: "B.A." },
  { name: "Technology in Education and Second Language Acquisition (TESLA)", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16017", level: "graduate", credential: "Ph.D." },
  { name: "Theatre, Design and Technology Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13255", level: "bachelor", credential: "B.A." },
  { name: "Theatre, Performance Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13096", level: "bachelor", credential: "B.A." },
  { name: "Theatre, Theatre Arts Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13097", level: "bachelor", credential: "B.A." },
  { name: "Urban and Community Design", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16151", level: "graduate", credential: "M.U.C.D." },
  { name: "Urban and Regional Planning", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16064", level: "graduate", credential: "M.U.R.P." },
  { name: "Urban Educational Leadership", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16233", level: "graduate", credential: "M.A." },
  { name: "Women's, Gender, and Sexuality Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=12996", level: "bachelor", credential: "B.A." },
  { name: "Women's, Gender, and Sexuality Studies", url: "https://catalog.usf.edu/preview_program.php?catoid=28&poid=16065", level: "graduate", credential: "M.A." },
  { name: "World Languages and Cultures, Applied Linguistics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13223", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Chinese Language and Culture Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13224", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Classics Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13225", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, East Asian Languages and Cultures Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13226", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, French and Francophone Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13227", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, German Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13228", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Interdisciplinary Classical Civilizations Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13229", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Italian Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13230", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Russian Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13231", level: "bachelor", credential: "B.A." },
  { name: "World Languages and Cultures, Spanish and Latin American Studies Concentration", url: "https://catalog.usf.edu/preview_program.php?catoid=25&poid=13232", level: "bachelor", credential: "B.A." },
];

// USF is a four-year university, so an unqualified program name should
// resolve to the bachelor's rather than the graduate program of the same name.
export const usfCatalog = createProgramCatalog(USF_PROGRAMS, { preferred: "bachelor" });
