// VALENCIA program catalog.
//
// GENERATED FILE — do not edit by hand.
//
// Source:   https://catalog.valenciacollege.edu/degrees/ (Degrees and Certificate Programs)
// Scraped:  2026-07-25
// Programs: 158 (48 associate, 7 bachelor, 103 certificate)
//
// Cost: not set per-program. This school (like most FCS schools) publishes
// tuition as a single flat per-credit-hour rate for the whole college rather
// than a distinct price per program, so repeating an identical costNote on
// every entry would only be noise.
// Certificate names were split from Valencia's markup, which lists several certificates as consecutive links sharing one parent program page; each was verified as a distinct entry before splitting.

import { createProgramCatalog, type SchoolProgram } from "@/app/lib/programCatalog";

export const VALENCIA_PROGRAMS: SchoolProgram[] = [
  { name: "Associate in Arts", url: "https://catalog.valenciacollege.edu/degrees/associateinarts/", level: "associate", credential: "A.A." },
  { name: "Accounting Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/accountingtechnology/", level: "associate", credential: "A.S." },
  { name: "Administrative Office Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/administrativeofficemanagement/", level: "associate", credential: "A.S." },
  { name: "Advanced Manufacturing & Automation Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/engineeringtechnology/", level: "associate", credential: "A.S." },
  { name: "Baking and Pastry Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/bakingandpastrymanagement/", level: "associate", credential: "A.S." },
  { name: "Biotechnology Laboratory Sciences", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/biotechnologylabsciences/index.html", level: "associate", credential: "A.S." },
  { name: "Business Administration", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "associate", credential: "A.S." },
  { name: "Cardiovascular Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/cardiovasculartechnology/", level: "associate", credential: "A.S." },
  { name: "Computer-Aided Drafting and Design Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/draftinganddesigntechnology/", level: "associate", credential: "A.S." },
  { name: "Computer Information Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerinformationtechnology/", level: "associate", credential: "A.S." },
  { name: "Computer Programming and Analysis", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerprogramminganalysis/", level: "associate", credential: "A.S." },
  { name: "Construction and Civil Engineering Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/buildingconstructiontechnology/", level: "associate", credential: "A.S." },
  { name: "Criminal Justice", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticetechnology/", level: "associate", credential: "A.S." },
  { name: "Criminal Justice Law Enforcement Academy Track", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/cjlawenforcementacademytrack/", level: "associate", credential: "A.S." },
  { name: "Culinary Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/culinarymanagement/", level: "associate", credential: "A.S." },
  { name: "Cybersecurity & Network Engineering Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "associate", credential: "A.S." },
  { name: "Dental Hygiene", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/dentalhygiene/", level: "associate", credential: "A.S." },
  { name: "Diagnostic Medical Sonography", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/diagnosticmedicalsonography/", level: "associate", credential: "A.S." },
  { name: "Digital Media Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "associate", credential: "A.S." },
  { name: "Electrical and Computer Engineering Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/electronicsengineeringtechnology/", level: "associate", credential: "A.S." },
  { name: "Emergency Medical Services Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/emergencymedicalservicestechnology/", level: "associate", credential: "A.S." },
  { name: "Energy Management and Controls Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/energymanagement/", level: "associate", credential: "A.S." },
  { name: "Film Production Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/filmproductiontechnology/", level: "associate", credential: "A.S." },
  { name: "Fire Science Academy Track", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/firesciencetechnologyacademy/", level: "associate", credential: "A.S." },
  { name: "Fire Science Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/firesciencetechnology/", level: "associate", credential: "A.S." },
  { name: "Graphic and Interactive Design", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/graphicandinteractivedesign/", level: "associate", credential: "A.S." },
  { name: "Health Information Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/healthinformationtechnology/", level: "associate", credential: "A.S." },
  { name: "Health Navigator", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/healthnavigator/", level: "associate", credential: "A.S." },
  { name: "Hospitality and Tourism Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "associate", credential: "A.S." },
  { name: "Live Entertainment Design and Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/entertainmentdesigntechnology/", level: "associate", credential: "A.S." },
  { name: "Medical Administration", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/medicalofficeadministration/", level: "associate", credential: "A.S." },
  { name: "New Media Communication", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/newmediacommunication/", level: "associate", credential: "A.S." },
  { name: "Nursing, Traditional Track", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/nursing/nursing/", level: "associate", credential: "A.S." },
  { name: "Paralegal Studies", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/paralegalstudies/", level: "associate", credential: "A.S." },
  { name: "Plant Science and Agricultural Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/landscapehorticulturetechnology/", level: "associate", credential: "A.S." },
  { name: "Property Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/rpm/", level: "associate", credential: "A.S." },
  { name: "Radiography", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/radiography/", level: "associate", credential: "A.S." },
  { name: "Respiratory Care", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/respiratorycare/", level: "associate", credential: "A.S." },
  { name: "Science, Technology, Engineering and Math", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/stem/", level: "associate", credential: "A.S." },
  { name: "Semiconductor Engineering Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/semiconductorengineering/", level: "associate", credential: "A.S." },
  { name: "Sound Production Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/soundandmusictechnology/", level: "associate", credential: "A.S." },
  { name: "Supervision and Management for Industry", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/industrialmanagementtechnology/", level: "associate", credential: "A.S." },
  { name: "Nursing, Accelerated Track", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/nursing/nursingadvancedstandingtrack/", level: "associate", credential: "A.S." },
  { name: "Biology (S.A.A.T.)", url: "https://catalog.valenciacollege.edu/degrees/saatdegree/biologysaat/", level: "associate", credential: "S.A.A.T." },
  { name: "Civil Engineering (S.A.A.T.)", url: "https://catalog.valenciacollege.edu/degrees/saatdegree/civilengineeringsaat/", level: "associate", credential: "S.A.A.T." },
  { name: "Electrical Engineering (S.A.A.T.)", url: "https://catalog.valenciacollege.edu/degrees/saatdegree/electricalengineeringsaat/", level: "associate", credential: "S.A.A.T." },
  { name: "Health Sciences (S.A.A.T.)", url: "https://catalog.valenciacollege.edu/degrees/saatdegree/healthsciencessaat/", level: "associate", credential: "S.A.A.T." },
  { name: "Mechanical Engineering (S.A.A.T.)", url: "https://catalog.valenciacollege.edu/degrees/saatdegree/mechanicalengineeringsaat/", level: "associate", credential: "S.A.A.T." },
  { name: "Business and Organizational Leadership", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/bas/", level: "bachelor", credential: "B.A.S." },
  { name: "Computing Technology and Software Development", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/computingtechnologyandsoftwaredesign/", level: "bachelor", credential: "B.A.S." },
  { name: "Public Safety Administration", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/publicsafetyadministration/", level: "bachelor", credential: "B.A.S." },
  { name: "Cardiopulmonary Sciences", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/astobscardiopulmonarysciences/", level: "bachelor", credential: "B.S." },
  { name: "Electrical and Computer Engineering Technology", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/electricalcomputerengineeringtechnology/", level: "bachelor", credential: "B.S." },
  { name: "Radiologic and Imaging Sciences", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/astobsradiologicimagingsciences/", level: "bachelor", credential: "B.S." },
  { name: "Nursing", url: "https://catalog.valenciacollege.edu/degrees/bachelorofscience/bsn/", level: "bachelor", credential: "B.S.N." },
  { name: "Bread Baking", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/breadbaking/", level: "certificate", credential: "A.T.C." },
  { name: "Cake Artistry", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/cakeartistry/", level: "certificate", credential: "A.T.C." },
  { name: "Chocolate and Confectionery Arts", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/advancedchocholates/", level: "certificate", credential: "A.T.C." },
  { name: "Computed Tomography (CT)", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/computedtomography/", level: "certificate", credential: "A.T.C." },
  { name: "Echocardiography", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/echocardiography/", level: "certificate", credential: "A.T.C." },
  { name: "Human Resource Management", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/humanresourcemanagement/", level: "certificate", credential: "A.T.C." },
  { name: "Magnetic Resonance Imaging", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/magneticresonanceimaging/", level: "certificate", credential: "A.T.C." },
  { name: "Mammography", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/mammography/", level: "certificate", credential: "A.T.C." },
  { name: "Vascular Sonography", url: "https://catalog.valenciacollege.edu/degrees/advancedtechnicalcertificates/vascularsonography/", level: "certificate", credential: "A.T.C." },
  { name: "Accounting Applications", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/accountingtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Operations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/accountingtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Accounting Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/accountingtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Advanced Computer Aided Design", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/draftinganddesigntechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Advanced Electronics Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/electronicsengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Artificial Intelligence Foundations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerprogramminganalysis/", level: "certificate", credential: "C.C.C." },
  { name: "Audio Electronics Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/soundandmusictechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Audiovisual Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/soundandmusictechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Baking and Pastry Arts", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/bakingandpastrymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Baking and Pastry Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/bakingandpastrymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Basic Electronics Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/electronicsengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Biotechnology Laboratory Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/biotechnologylabsciences/", level: "certificate", credential: "C.C.C." },
  { name: "Biotechnology Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/biotechnologylabsciences/", level: "certificate", credential: "C.C.C." },
  { name: "Business Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Business Operations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Business Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Chef's Apprentice", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/culinarymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Cloud Computing Architecture", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Aided Design", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/draftinganddesigntechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Information Data Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerinformationtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Information Technology Analyst", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerinformationtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Information Technology Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerinformationtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerprogramminganalysis/", level: "certificate", credential: "C.C.C." },
  { name: "Computer Programming Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/informationtechnology/computerprogramminganalysis/", level: "certificate", credential: "C.C.C." },
  { name: "Construction Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/buildingconstructiontechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Criminal Justice Institute", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticeinstitute/", level: "certificate", credential: "Cert." },
  { name: "Criminal Justice Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Culinary Arts", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/culinarymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Culinary Arts Management Operations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/culinarymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Customer Service Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Customer Service Operations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Customer Service Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Cyber Security", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Broadcast Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Motion Graphics Development", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Motion Graphics Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Media Video Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Music Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/soundandmusictechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Video Editing and Post-Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Digital Video Fundamentals", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/digitalmediatechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Emergency Medical Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/emergencymedicalservicestechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Engineering Technology Support Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/engineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Entertainment – Stage Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/entertainmentdesigntechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Entrepreneurship", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Field Survey Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/buildingconstructiontechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Film Production Fundamentals", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/filmproductiontechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Firefighter - Emergency Medical Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/firesciencetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Firefighter  - Minimum Standards", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/firesciencetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Fire Officer Supervisor", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/firesciencetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Graphic Design Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/graphicandinteractivedesign/", level: "certificate", credential: "C.C.C." },
  { name: "Graphic Design Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/graphicandinteractivedesign/", level: "certificate", credential: "C.C.C." },
  { name: "Health Care Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/healthnavigator/", level: "certificate", credential: "C.C.C." },
  { name: "Homeland Security", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Homeland Security Law Enforcement Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality - Bar and Beverage Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality – Event Planning and Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality – Guest Services Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality – Hotel Operations and Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality – Theme Park and Attractions Management Technical Certificate Restaurant and Foodservice Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/hospitalityandtourismmanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Hospitality Security Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/criminaljusticeparalegalstudies/criminaljusticetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Human Resources Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Human Resources Operations", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Human Resources Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Interactive Design Production", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/graphicandinteractivedesign/", level: "certificate", credential: "C.C.C." },
  { name: "Interactive Design Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/graphicandinteractivedesign/", level: "certificate", credential: "C.C.C." },
  { name: "International Business Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Laser and Photonics Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/electronicsengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Lean Manufacturing", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/engineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Linux Enterprise Server Administration", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Mechatronics", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/engineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Medical Information Coder/Biller", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/healthinformationtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Medical Office Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/medicalofficeadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Medical Office Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/medicalofficeadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Medical Office Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/medicalofficeadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Network Administration", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Network Infrastructure", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Network Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/networkengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Office Management", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/administrativeofficemanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Office Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/administrativeofficemanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Office Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/administrativeofficemanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Operations Support and Services", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/industrialmanagementtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Paramedic Technology", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/alliedhealth/emergencymedicalservicestechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Pastry Chef's Apprentice", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/hospitalityculinary/bakingandpastrymanagement/", level: "certificate", credential: "C.C.C." },
  { name: "Plant Science Professional", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/landscapehorticulturetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Plant Science Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/landscapehorticulturetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Plant Science Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/landscapehorticulturetechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Property Management Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/rpm/", level: "certificate", credential: "C.C.C." },
  { name: "Rapid Prototyping Specialist - 3-D Printing", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/draftinganddesigntechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Real Estate Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Robotics Applications Technician", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/electronicsengineeringtechnology/", level: "certificate", credential: "C.C.C." },
  { name: "Social Entrepreneurship Specialist", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/businessaccountingofficerelated/businessadministration/", level: "certificate", credential: "C.C.C." },
  { name: "Social Media Communication Support", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/artsentertainment/newmediacommunication/", level: "certificate", credential: "C.C.C." },
  { name: "Semiconductor Cleanroom Operator", url: "https://catalog.valenciacollege.edu/degrees/associateinscience/engineeringtechnology/semiconductorengineering/", level: "certificate", credential: "C.C.C." },
];
