import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Vocation',
  description: 'Terms of Service for Vocation - Education & Career Pathway Planning',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-surface">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold text-on-surface mb-8">Terms of Service</h1>

        <div className="prose prose-slate max-w-none space-y-6 text-on-surface-variant">
          <p className="text-sm text-outline">Last updated: August 10, 2026</p>

          <section>
            <p className="bg-surface-variant border border-outline rounded-lg p-4 text-sm">
              <strong>Independent project notice:</strong> Vocation is an independent project and
              is not affiliated with, endorsed by, or sponsored by Miami Dade College or any other
              educational institution. Program, transfer, and earnings data referenced by the
              service are drawn from institutions&apos; own public catalogs and government data
              sources; their inclusion does not imply any partnership.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Vocation, you accept and agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">2. Description of Service</h2>
            <p>
              Vocation is an independently-built AI-powered educational planning tool that
              generates personalized career pathways using publicly available program and
              transfer data. The service provides informational suggestions and should not be
              considered official academic advice.
            </p>
            <p className="mt-4">
              Vocation is provided free of charge as a non-commercial personal project. We do not
              charge for access, sell your information, run advertising, or accept payment of any
              kind for the service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">3. Eligibility</h2>
            <p>
              Vocation does not currently verify a user&apos;s age when creating an account. If
              you are under 13, you should only use Vocation with the involvement of a parent or
              guardian, and should not create an account without their consent. We do not
              knowingly collect personal information from a child under 13 without such consent —
              see our{' '}
              <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>{' '}
              for how to report an account we should remove.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">4. AI-Generated Content Disclaimer</h2>
            <p>
              <strong>Important:</strong> All pathways and recommendations generated by Vocation
              are AI-generated suggestions and may contain inaccuracies. You must verify all
              information with official academic advisors and official school resources before
              making any academic decisions.
            </p>
            <p className="mt-4">
              Vocation is not responsible for any decisions made based on AI-generated content.
              Always consult with academic advisors for official degree requirements, transfer
              agreements, and program information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">5. Educational &amp; Earnings Data Disclaimer</h2>
            <p>
              Cost, wage, and earnings figures shown by Vocation come from third-party sources,
              including government labor statistics and college outcome data. These figures
              reflect historical data about past students or workers and are not a prediction,
              promise, or guarantee of your own future earnings or outcomes. Official degree
              requirements, transfer agreements, and program information should be confirmed
              with:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Your school&apos;s academic advisors</li>
              <li>Official degree catalogs and resources</li>
              <li>Partner universities for transfer information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">6. Accounts &amp; User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Provide accurate information and keep your login credentials confidential</li>
              <li>Use the service only for lawful purposes</li>
              <li>Not attempt to disrupt, overload, or gain unauthorized access to the service</li>
              <li>Verify all AI-generated information with official sources before relying on it</li>
              <li>Not rely solely on AI-generated pathways for academic planning</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">7. Disclaimer of Warranties</h2>
            <p>
              Vocation is provided &quot;as is&quot; and &quot;as available,&quot; without
              warranties of any kind, express or implied, including but not limited to
              accuracy, availability, merchantability, or fitness for a particular purpose. We do
              not warrant that the service will be uninterrupted, error-free, or secure.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">8. Limitation of Liability</h2>
            <p>
              Vocation shall not be liable for any indirect, incidental, special, consequential,
              or punitive damages resulting from your use of or inability to use the service,
              including but not limited to decisions made based on AI-generated content. Because
              Vocation is offered free of charge, our total liability to you for any claim
              arising from your use of the service is limited to the greater of $0 or the amount,
              if any, you paid to use the service in the twelve months before the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">9. Termination</h2>
            <p>
              You may delete your account at any time from Account Settings, which permanently
              removes your account and the data linked to it. We may suspend or terminate access
              for anyone who violates these terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">10. Third-Party Services</h2>
            <p>
              Vocation uses Google Gemini AI for content generation, along with other third-party
              infrastructure providers described in our{' '}
              <a href="/privacy" className="text-primary hover:underline">Privacy Policy</a>.
              Your use of this service is also subject to those providers&apos; own terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">11. Intellectual Property</h2>
            <p>
              All content, features, and functionality of Vocation are owned by the operator of
              Vocation and are protected by copyright, trademark, and other intellectual property
              laws. Program names, transfer agreements, and other institutional data referenced by
              the service remain the property of their respective institutions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">12. Governing Law</h2>
            <p>
              These terms are governed by the laws of the State of Florida, USA, without regard to
              its conflict-of-law principles. Any dispute arising from these terms or your use of
              Vocation will be subject to the exclusive jurisdiction of the state and federal
              courts located in Florida.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">13. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of any
              material changes by posting the updated terms on this page and updating the
              &quot;Last updated&quot; date above.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">14. Severability</h2>
            <p>
              If any provision of these terms is found unenforceable, the remaining provisions
              will remain in full effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-on-surface mt-8 mb-4">15. Contact Information</h2>
            <p>
              For questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:privacy@vocation.bz" className="text-primary hover:underline">privacy@vocation.bz</a>.
            </p>
          </section>
        </div>

        <div className="mt-12">
          <a
            href="/"
            className="text-primary hover:text-primary-container font-medium"
          >
            ← Back to Vocation
          </a>
        </div>
      </div>
    </div>
  )
}
