import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Vocation',
  description: 'Terms of Service for Vocation - Career Planning for Miami Dade College',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms of Service</h1>
        
        <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
          <p className="text-sm text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>
          
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Vocation, you accept and agree to be bound by the terms and provision of this agreement. 
              If you do not agree to these terms, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
            <p>
              Vocation is an AI-powered educational planning tool that generates personalized career pathways for 
              Miami Dade College students. The service provides informational suggestions and should not be considered 
              official academic advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">3. AI-Generated Content Disclaimer</h2>
            <p>
              <strong>Important:</strong> All pathways and recommendations generated by Vocation are AI-generated suggestions 
              and may contain inaccuracies. You must verify all information with official MDC academic advisors and 
              official MDC resources before making any academic decisions.
            </p>
            <p className="mt-4">
              Vocation is not responsible for any decisions made based on AI-generated content. Always consult with 
              academic advisors for official degree requirements, transfer agreements, and program information.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">4. Educational Disclaimer</h2>
            <p>
              This tool provides informational pathways only. Official degree requirements, transfer agreements, 
              and program information should be confirmed with:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>MDC academic advisors</li>
              <li>Official MDC degree catalogs and resources</li>
              <li>Partner universities for transfer information</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">5. User Responsibilities</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4">
              <li>Use the service only for lawful purposes</li>
              <li>Verify all AI-generated information with official sources</li>
              <li>Not rely solely on AI-generated pathways for academic planning</li>
              <li>Consult with academic advisors before making academic decisions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">6. Limitation of Liability</h2>
            <p>
              Vocation and Miami Dade College shall not be liable for any indirect, incidental, special, consequential, 
              or punitive damages resulting from your use of or inability to use the service, including but not limited 
              to decisions made based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">7. Third-Party Services</h2>
            <p>
              Vocation uses Google Gemini AI for content generation. Your use of this service is also subject to 
              Google's terms of service and privacy policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">8. Intellectual Property</h2>
            <p>
              All content, features, and functionality of Vocation are owned by Miami Dade College and are protected 
              by copyright, trademark, and other intellectual property laws.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">9. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. We will notify users of any material changes 
              by posting the updated terms on this page.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">10. Contact Information</h2>
            <p>
              For questions about these Terms of Service, please contact us at{' '}
              <a href="mailto:advisement@mdc.edu" className="text-blue-600 hover:underline">advisement@mdc.edu</a>.
            </p>
          </section>
        </div>

        <div className="mt-12">
          <a 
            href="/" 
            className="text-blue-600 hover:text-blue-700 font-medium"
          >
            ← Back to Vocation
          </a>
        </div>
      </div>
    </div>
  )
}

