"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { isComplete, summarize, type IntakeAnswers } from "@/app/lib/intake";
import { clearIntake, loadIntake } from "@/app/lib/intakeStorage";
import { TRACK_BADGES, type PlanTrack, type ResolvedTracks } from "@/app/lib/planTypes";
import type { PathwayData, PathwayOption } from "@/app/lib/types";
import { estimatePlanCost, formatCostRangeShort } from "@/app/lib/planCost";
import { PathwayFlow } from "@/app/components/plan/PathwayFlow";
import { CostPanel } from "@/app/components/plan/CostPanel";

// The payoff screen: the same career, planned three ways.
//
// Each track is generated by the SAME /api/generate-pathway route 1.0 used —
// one call per school, in parallel. That's deliberate. The route already has
// canonicalization, three cache layers, and rate limiting wired correctly, and
// a track whose school someone else already generated for this career costs
// nothing. Building a new "generate three at once" endpoint would have meant
// reimplementing all of that and would have put three sequential Gemini calls
// inside one serverless invocation's timeout.
//
// The tracks are de-duped server-side before we get here, so a student whose
// local school IS their cheapest option and IS the one they named generates
// once and sees one honest card, not three copies.

type TrackState =
  | { status: "pending" }
  | { status: "done"; data: PathwayData; selected: number }
  | { status: "error"; message: string };

export default function PlanPage() {
  const router = useRouter();

  const [answers, setAnswers] = useState<IntakeAnswers | null>(null);
  const [resolved, setResolved] = useState<ResolvedTracks | null>(null);
  const [states, setStates] = useState<Record<string, TrackState>>({});
  const [activeSchoolId, setActiveSchoolId] = useState<string | null>(null);
  const [fatal, setFatal] = useState<string | null>(null);

  // --- Load the intake, then resolve which schools to plan against ----------

  useEffect(() => {
    const stored = loadIntake();
    if (!isComplete(stored)) {
      // Landing here directly (a bookmark, a refresh after clearing the tab)
      // means there's nothing to plan. Send them to question one rather than
      // rendering an empty page.
      router.replace("/");
      return;
    }
    setAnswers(stored);
  }, [router]);

  useEffect(() => {
    if (!answers) return;
    let cancelled = false;

    (async () => {
      try {
        const response = await fetch("/api/plan-tracks", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(answers),
        });
        if (!response.ok) {
          const body = await response.json().catch(() => ({}));
          throw new Error(body.error || `Request failed (${response.status})`);
        }
        const result = (await response.json()) as ResolvedTracks;
        if (cancelled) return;

        setResolved(result);
        setActiveSchoolId(result.tracks[0]?.schoolId ?? null);
        setStates(
          Object.fromEntries(
            result.tracks.map((track) => [track.schoolId, { status: "pending" } as TrackState])
          )
        );
      } catch (err: any) {
        if (!cancelled) setFatal(err.message || "Something went wrong.");
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [answers]);

  // --- Generate one pathway per track, in parallel --------------------------

  const career = answers?.career?.resolved ?? "";

  const generate = useCallback(
    async (track: PlanTrack) => {
      try {
        const response = await fetch("/api/generate-pathway", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ career, school: track.schoolId }),
        });

        const body = await response.json().catch(() => ({}));
        if (!response.ok) {
          throw new Error(body.error || `Request failed (${response.status})`);
        }

        // 1.0 shipped a pre-`pathways` shape for a while and some seeded
        // entries still carry it. Normalize rather than crash on old data.
        const data: PathwayData =
          "pathways" in body
            ? body
            : { title: body.title ?? career, pathways: [{ title: body.title ?? career, isPrimary: true, steps: body.steps ?? [] }] };

        const primary = data.pathways.findIndex((p) => p.isPrimary);

        setStates((current) => ({
          ...current,
          [track.schoolId]: {
            status: "done",
            data,
            selected: primary >= 0 ? primary : 0,
          },
        }));
      } catch (err: any) {
        setStates((current) => ({
          ...current,
          [track.schoolId]: {
            status: "error",
            message: err.message || "Couldn't generate this route.",
          },
        }));
      }
    },
    [career]
  );

  useEffect(() => {
    if (!resolved || !career) return;
    // Fired once per resolve. Each track settles its own state, so a slow or
    // failing one never blocks the others from rendering.
    resolved.tracks.forEach((track) => void generate(track));
  }, [resolved, career, generate]);

  // --- Derived --------------------------------------------------------------

  const activeTrack = useMemo(
    () => resolved?.tracks.find((t) => t.schoolId === activeSchoolId) ?? null,
    [resolved, activeSchoolId]
  );
  const activeState = activeSchoolId ? states[activeSchoolId] : undefined;

  const selectPathway = (schoolId: string, index: number) =>
    setStates((current) => {
      const state = current[schoolId];
      if (state?.status !== "done") return current;
      return { ...current, [schoolId]: { ...state, selected: index } };
    });

  const startOver = () => {
    clearIntake();
    router.push("/");
  };

  if (!answers) return null;

  return (
    <div className="flex min-h-screen flex-col bg-gray-50">
      <header className="border-b border-gray-200 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <Link href="/" className="text-2xl font-bold text-school-600">
            Vocation
          </Link>
          <button
            type="button"
            onClick={startOver}
            className="text-sm text-gray-500 transition-colors hover:text-gray-800"
          >
            Start over
          </button>
        </div>
      </header>

      <main className="mx-auto w-full max-w-7xl flex-1 px-6 py-10">
        <p className="text-sm font-medium uppercase tracking-wide text-gray-500">
          Your plan
        </p>
        <h1 className="mt-1 text-3xl font-bold text-gray-900 md:text-4xl">
          Becoming {article(career)} {career}
        </h1>

        <div className="mt-3 flex flex-wrap gap-2">
          {summarize(answers).map((chip) => (
            <span
              key={chip}
              className="rounded-full bg-white px-3 py-1 text-xs text-gray-600 ring-1 ring-gray-200"
            >
              {chip}
            </span>
          ))}
        </div>

        {fatal && (
          <div className="mt-8 rounded-xl border border-red-200 bg-red-50 p-6">
            <p className="font-semibold text-red-800">We couldn&apos;t build your plan.</p>
            <p className="mt-1 text-sm text-red-700">{fatal}</p>
            <button
              type="button"
              onClick={startOver}
              className="mt-4 rounded-lg bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-700"
            >
              Start over
            </button>
          </div>
        )}

        {resolved?.notes.map((note) => (
          <p
            key={note}
            className="mt-6 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-relaxed text-amber-900"
          >
            {note}
          </p>
        ))}

        {!resolved && !fatal && (
          <p className="mt-10 text-gray-500">Working out which schools fit…</p>
        )}

        {/* The comparison row. This is the whole point of the redesign: three
            real routes to the same job, priced side by side. */}
        {resolved && resolved.tracks.length > 0 && (
          <div className="mt-8 grid gap-4 md:grid-cols-3">
            {resolved.tracks.map((track) => (
              <TrackCard
                key={track.schoolId}
                track={track}
                state={states[track.schoolId]}
                active={track.schoolId === activeSchoolId}
                onSelect={() => setActiveSchoolId(track.schoolId)}
              />
            ))}
          </div>
        )}

        {/* The selected route, in full. */}
        {activeTrack && (
          <section className="mt-12">
            <h2 className="text-2xl font-bold text-gray-900">
              {activeTrack.schoolName}
            </h2>
            <p className="mt-2 max-w-3xl text-gray-600">{activeTrack.why}</p>

            {activeState?.status === "pending" && (
              <div className="mt-8 flex items-center gap-3 text-gray-500">
                <span className="h-4 w-4 animate-spin rounded-full border-2 border-school-600 border-t-transparent" />
                Generating this route…
              </div>
            )}

            {activeState?.status === "error" && (
              <div className="mt-8 rounded-xl border border-red-200 bg-red-50 p-6">
                <p className="font-semibold text-red-800">
                  This route couldn&apos;t be generated.
                </p>
                <p className="mt-1 text-sm text-red-700">{activeState.message}</p>
              </div>
            )}

            {activeState?.status === "done" && (
              <>
                {activeState.data.pathways.length > 1 && (
                  <nav
                    className="mt-6 flex gap-1 overflow-x-auto border-b border-gray-200"
                    aria-label="Alternative routes at this school"
                  >
                    {activeState.data.pathways.map((option, index) => (
                      <button
                        key={index}
                        type="button"
                        onClick={() => selectPathway(activeTrack.schoolId, index)}
                        className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium transition-colors ${
                          activeState.selected === index
                            ? "border-school-500 text-school-600"
                            : "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"
                        }`}
                      >
                        {option.isPrimary && (
                          <span className="mr-2 rounded bg-school-100 px-2 py-0.5 text-xs text-school-700">
                            Recommended
                          </span>
                        )}
                        {option.title}
                      </button>
                    ))}
                  </nav>
                )}

                <div className="mt-6">
                  <PathwayFlow
                    pathway={activeState.data.pathways[activeState.selected]}
                    schoolId={activeTrack.schoolId}
                    showStepCosts
                  />
                </div>

                <div className="mt-8">
                  <CostPanel
                    pathway={activeState.data.pathways[activeState.selected]}
                    schoolId={activeTrack.schoolId}
                    incomeBand={answers.incomeBand}
                  />
                </div>
              </>
            )}
          </section>
        )}
      </main>

      <footer className="border-t border-gray-200 bg-white">
        <div className="mx-auto max-w-7xl px-6 py-6">
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-gray-500">
            <Link href="/privacy" className="transition-colors hover:text-school-600">
              Privacy
            </Link>
            <Link href="/terms" className="transition-colors hover:text-school-600">
              Terms
            </Link>
            <Link href="/team" className="transition-colors hover:text-school-600">
              Meet the team
            </Link>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-gray-500">
            <strong>Disclaimer:</strong> pathways and costs are AI-generated
            estimates built from real program catalogs. Verify programs,
            requirements, and prices with an academic advisor and the
            school&apos;s own site before making decisions.
          </p>
        </div>
      </footer>
    </div>
  );
}

/** "a Nurse" / "an Architect" — cheap, and wrong often enough to be worth it. */
function article(career: string): "a" | "an" {
  return /^[aeiou]/i.test(career.trim()) ? "an" : "a";
}

function TrackCard({
  track,
  state,
  active,
  onSelect,
}: {
  track: PlanTrack;
  state: TrackState | undefined;
  active: boolean;
  onSelect: () => void;
}) {
  // The headline figure comes from the pathway the student is looking at, so
  // the card and the detail below it can never disagree.
  const pathway: PathwayOption | null =
    state?.status === "done" ? state.data.pathways[state.selected] : null;
  const cost = pathway ? estimatePlanCost(pathway.steps, track.schoolId) : null;

  return (
    <button
      type="button"
      onClick={onSelect}
      aria-pressed={active}
      className={`rounded-xl border p-5 text-left transition-all ${
        active
          ? "border-school-600 bg-white ring-2 ring-school-600"
          : "border-gray-200 bg-white hover:border-school-400 hover:shadow-md"
      }`}
    >
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="rounded-full bg-school-100 px-2.5 py-0.5 text-xs font-semibold text-school-700">
          {TRACK_BADGES[track.kind]}
        </span>
        {/* A school that satisfies more than one track earned both badges —
            saying so is more useful than showing the same card twice. */}
        {track.alsoCovers.map((kind) => (
          <span
            key={kind}
            className="rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-600"
          >
            {TRACK_BADGES[kind]}
          </span>
        ))}
      </div>

      <p className="mt-3 font-bold text-gray-900">{track.schoolName}</p>
      <p className="mt-0.5 text-sm text-gray-500">
        {track.distanceMiles === null
          ? track.title
          : `${track.title} · ${Math.round(track.distanceMiles)} mi`}
      </p>

      <div className="mt-4 border-t border-gray-100 pt-4">
        {state?.status === "pending" && (
          <span className="text-sm text-gray-400">Generating…</span>
        )}
        {state?.status === "error" && (
          <span className="text-sm text-red-600">Couldn&apos;t generate</span>
        )}
        {cost && (
          <>
            <p className="text-2xl font-bold text-gray-900">
              {formatCostRangeShort(cost.total)}
            </p>
            <p className="text-xs text-gray-500">
              tuition &amp; fees · ~{cost.years} yrs
            </p>
          </>
        )}
      </div>
    </button>
  );
}
