// Pulls everything real users generated out of the durable store and merges it
// into data/seed-cache.json.
//
// This is the cheap half of seeding. scripts/seed-pathways.mjs generates from
// scratch and bills Gemini for every entry; this script bills nothing, because
// the generation already happened when a student asked for it. The durable
// store (app/lib/durableCache.ts) kept the result instead of letting it die
// with the serverless instance.
//
// The intended loop:
//   1. Students use the site. Misses are generated once and stored.
//   2. npm run export-cache          (pulls them into the seed file)
//   3. Review the diff, commit.      (now permanent, reviewable, and free)
//
// Usage:
//   npm run export-cache                  merge into the seed file
//   npm run export-cache -- --dry-run     show what would change, write nothing
//
// Needs the same credentials the deployment uses. Either put them in
// .env.local as KV_REST_API_URL / KV_REST_API_TOKEN, or run:
//   vercel env pull .env.local

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SEED_FILE = path.join(ROOT, "data", "seed-cache.json");
const ENV_FILE = path.join(ROOT, ".env.local");

const PREFIX = "vocation:";

// Minimal .env.local reader. Next.js loads that file for the app, but a plain
// node script gets no such treatment, and pulling in dotenv for four lines
// isn't worth a dependency.
async function loadEnvLocal() {
  if (!existsSync(ENV_FILE)) return;
  const text = await readFile(ENV_FILE, "utf8");
  for (const line of text.split("\n")) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!match) continue;
    const [, name, rawValue] = match;
    if (process.env[name] !== undefined) continue; // real env wins
    process.env[name] = rawValue.replace(/^["']|["']$/g, "");
  }
}

async function command(url, token, args) {
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(args),
  });
  if (!response.ok) {
    throw new Error(`${args[0]} failed: HTTP ${response.status} ${await response.text()}`);
  }
  const payload = await response.json();
  return payload.result;
}

async function main() {
  const dryRun = process.argv.includes("--dry-run");
  await loadEnvLocal();

  const url = process.env.KV_REST_API_URL;
  const token = process.env.KV_REST_API_TOKEN;

  if (!url || !token) {
    console.error(
      "No durable store configured.\n\n" +
        "Set KV_REST_API_URL and KV_REST_API_TOKEN in .env.local, or run:\n" +
        "  vercel env pull .env.local\n"
    );
    process.exit(1);
  }

  const keys = await command(url, token, ["KEYS", `${PREFIX}*`]);
  if (!Array.isArray(keys) || keys.length === 0) {
    console.log("Durable store is empty — nothing generated by users yet.");
    return;
  }

  const values = await command(url, token, ["MGET", ...keys]);

  const seed = existsSync(SEED_FILE)
    ? JSON.parse(await readFile(SEED_FILE, "utf8"))
    : {};

  const before = Object.keys(seed).length;
  const added = [];
  // A key already in the seed file has been through review; the stored copy
  // has not. Never let an unreviewed entry overwrite a reviewed one.
  const skipped = [];
  const unparseable = [];

  for (const [index, fullKey] of keys.entries()) {
    const key = fullKey.slice(PREFIX.length);
    const raw = values[index];

    if (typeof raw !== "string") continue;

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      unparseable.push(key);
      continue;
    }

    if (seed[key] !== undefined) {
      skipped.push(key);
      continue;
    }

    seed[key] = parsed;
    added.push(key);
  }

  added.sort();
  for (const key of added) console.log(`  + ${key}`);

  console.log(
    `\n${added.length} new, ${skipped.length} already seeded` +
      (unparseable.length ? `, ${unparseable.length} unparseable` : "")
  );

  if (unparseable.length) {
    console.warn("Unparseable entries (left in the store, not merged):");
    for (const key of unparseable) console.warn(`  ! ${key}`);
  }

  if (dryRun) {
    console.log("\n--dry-run: seed file not written.");
    return;
  }

  if (added.length === 0) {
    console.log("Seed file unchanged.");
    return;
  }

  // Sorted so the committed file has a stable order and diffs stay readable.
  const ordered = {};
  for (const key of Object.keys(seed).sort()) ordered[key] = seed[key];

  await writeFile(SEED_FILE, JSON.stringify(ordered, null, 2) + "\n", "utf8");
  console.log(
    `\nSeed file: ${before} -> ${Object.keys(ordered).length} entries.\n` +
      "Review the diff before committing — these went straight from Gemini to\n" +
      "students with no human check, and become the permanent answer once merged."
  );
}

main().catch((error) => {
  console.error(error.message ?? error);
  process.exit(1);
});
